---
title: "xdata_determine"
format: html
editor: visual
---

#### Load packages, functions and datasets

```{r}
packages <- c("ggplot2", "tidyverse", "lubridate", "sf", "sp", "dplyr", "rnaturalearth", "readr", "readxl", "spatialEco", "rstatix", "viridis", "BBmisc", "corrplot", "mgcv", "GGally", "gjam")
invisible(lapply(packages, library, character.only= TRUE))

standard_theme <- theme_bw() + theme(panel.border = element_rect(fill=NA, colour = "black")) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.text.align= 0, legend.title= element_text(size = 12), legend.text = element_text(size= 10), axis.text=element_text(size=10), axis.title=element_text(size=12))

source("~/Documents/GitHub/NCBlueCrab_Predators/Scripts/Load.SDM.R")
```

#### Data set up 
```{r}
xdata <- df_count_wide_both %>% dplyr::select(avgdepth, avgstemp, avgssal, avgsdo, SAVkm, NoFishRest, Sedsizecommon) %>% mutate_at(vars(Sedsizecommon), as.factor)
ydata <- df_count_wide_both %>% dplyr::select(atlanticcroakerP915:blackdrumP915forage) 

#Reduce # of species included 
species <- gjamTrimY(ydata, 30, OTHER = FALSE)$y %>% colnames() #minimum # of non-zero observations: 20
ydata <- ydata[, species] %>% as.data.frame()
ydata <- ydata %>% dplyr::select(-c(bluecrabP915, gizzardshadP915, reddrumP915forage:blackdrumP915forage))
```

### Env all model
```{r}
ml <- list(ng = 60000, burnin = 50000, typeNames = 'DA')

formula_str <- paste("~", paste(colnames(xdata), collapse = " + "))

modo_allx <- gjam(formula= as.formula(formula_str), xdata = xdata, ydata = ydata, modelList = ml)
#only lets you run with 26 variables
save(modo_allx, file= "~/Desktop/Ch1Data/gJam/10km/Updated_results/xdata_determine/modo_allx.RData")

plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = '~/Desktop/Ch1Data/gJam/10km/Updated_results/xdata_determine/modo_allx_plots2/')
gjamPlot(output = modo_allx, plotPars = plot)

modo_allx$fit$DIC
modo_allx$fit$rmspeAll
modo_allx$fit$rmspeBySpec

# md <- ggplot() +
#   geom_point(aes(x = model_choose_out_con_rd$inputs$y[,1],
#                  y = model_choose_out_con_rd$prediction$ypredMu[,1])) +
#   labs(x = "observed", y = "predicted", title = paste0(colnames(model_choose_out_con_rd$inputs$y)[1], ", common"))
```

### Env important model
```{r}
#change this! 
xdata <- df_count_wide_both %>% dplyr::select(avgssal, avgstemp, avgdepth, SAVkm)

formula_str <- paste("~", paste(colnames(xdata), collapse = " + "))

modo_allximp <- gjam(formula= as.formula(formula_str), xdata = xdata, ydata = ydata, modelList = ml)
#only lets you run with 26 variables
save(modo_allximp, file= "~/Desktop/Ch1Data/gJam/10km/Updated_results/xdata_determine/modo_allximp.RData")

plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = '~/Desktop/Ch1Data/gJam/10km/Updated_results/xdata_determine/modo_allximp_plots2/')
gjamPlot(output = modo_allximp, plotPars = plot)
```

