---
title: "Abundance_length_environmental"
format: html
editor: visual
---

#### Load packages and datasets

```{r}
packages <- c("ggplot2", "tidyverse", "lubridate", "sf", "sp", "dplyr", "rnaturalearth", "readr", "readxl", "spatialEco", "rstatix", "viridis", "BBmisc", "corrplot")
invisible(lapply(packages, library, character.only= TRUE))

standard_theme <- theme_bw() + theme(panel.border = element_rect(fill=NA, colour = "black")) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.text.align= 0, legend.title= element_text(size = 12), legend.text = element_text(size= 10), axis.text=element_text(size=10), axis.title=element_text(size=12))

p915_CPUE <- read_csv("/users/sallydowd/Desktop/Ch1Data/P915/p915_CPUE_new.csv")
setwd("~/Documents/GitHub/NCBlueCrab_Predators")
p120_CPUE <- read_csv("Data/P120/Finalized/p120_CPUE.csv")
p195_CPUE <- read_csv("Data/P195/Finalized/p195_CPUE.csv")

p915_CPUEedt <- p915_CPUE %>% filter(between(Year, 2001, 2021), Month %in% c(5,6,9))
p120_CPUEedt <- p120_CPUE %>% filter(between(Year, 2000, 2021), Month %in% c(5,6))
p195_CPUEedt <- p195_CPUE %>%  filter(between(Year, 2000, 2021), Month %in% c(6,9))
```

#### Abundance

```{r}
interest_spp <- c("brown shrimp", "bluefish", "atlantic croaker", "southern flounder", "red drum", "black drum", "blue catfish", "gizzard shad", "american shad", "cownose ray", "blue crab", "atlantic menhaden", "spot", "summer flounder", "shads", "american eel", "adult blue crab", "atlantic brief squid", "atlantic thread herring", "lesser blue crab", "pink shrimp", "silver perch", "southern flounder",  "weakfish", "white shrimp", "cephalopod mullusc", "periwinkles", "alewife", "atlantic silverside", "bonnethead shark", "channel catfish", "hickory shad", "oyster toadfish", "sheepshead", "silver perch", "silversides", "striped mullet", "white mullet", "pinfish", "southern kingfish", "striped bass", "bay anchovy", "striped anchovy")

p195_nums <- p195_CPUEedt %>% filter(Speciescommonname %in% interest_spp, Month %in% c(6,9)) %>% group_by(Speciescommonname, Month) %>% summarise(Sum_colnum= sum(Numbertotal)) %>% mutate(Survey= "P195") 

p120_nums <- p120_CPUEedt %>% filter(Speciescommonname %in% interest_spp, Month %in% c(5,6)) %>% group_by(Speciescommonname, Month) %>% drop_na(Colnum) %>% summarise(Sum_colnum= sum(Colnum)) %>% mutate(Survey= "P120") 

p915_nums <- p915_CPUEedt %>% filter(Month %in% c(5,6,9), Speciescommonname %in% interest_spp) %>% group_by(Speciescommonname, Month) %>% summarise(Sum_colnum= sum(Colnum)) %>% mutate(Survey= "P915")

combo <- rbind(p195_nums, p120_nums, p915_nums)
combo <- combo %>% arrange(Speciescommonname, Month)
11
```

#### Length

```{r}
#P195
p195_lengthfreq <- read_csv("~/Documents/GitHub/NCBlueCrab_Predators/Data/P195/Finalized/p195_lengthfreq.csv")

p195_lengthfreq %>% filter(Speciescommonname %in% interest_spp) %>% drop_na(Length) %>% group_by(Speciescommonname) %>% ggplot() + geom_histogram(aes(x= Length)) + facet_wrap(~Speciescommonname, scale= "free") + xlab("Length (mm)") + ylab("Count") + standard_theme
ggsave("~/Desktop/p195_length.png", width= 10, height= 10)

#P120
P120_bioledt <- read_csv("~/Desktop/Ch1Data/P120/p120_biol_new.csv")

P120_bioledt %>% filter(Speciescommonname %in% interest_spp, Year >=2001) %>% drop_na(Length) %>% group_by(Speciescommonname) %>% ggplot() + geom_histogram(aes(x= Length)) + facet_wrap(~Speciescommonname, scale= "free") + xlab("Length (in)") + ylab("Count") + standard_theme
ggsave("~/Desktop/p120_length.png", width= 10, height= 10)

P120_bioledt %>% filter(Speciescommonname %in% c("atlantic menhaden", "atlantic croaker"), Year >= 2001) %>% drop_na(Length) %>% group_by(Speciescommonname) %>% ggplot() + geom_histogram(aes(x= Length)) + facet_wrap(~Speciescommonname, scale= "free") + xlab("Length (in)") + ylab("Count") + standard_theme + xlim(0,300)
#P915
p915_len_f <- read.csv("~/Desktop/Ch1Data/P915/p915_length_final.csv")

p915_len_f %>% drop_na(Length) %>% filter(Speciescommonname %in% interest_spp, ! Speciescommonname %in% c("cownose ray", "striped bass", "pinfish"), Length < 900) %>% group_by(Speciescommonname) %>% ggplot() + geom_histogram(aes(x= Length)) + facet_wrap(~Speciescommonname, scales= "free") + xlab("Length (mm)") + ylab("Count") + standard_theme + scale_x_continuous(breaks=seq(0, 500, 50))
ggsave("~/Desktop/p915_length.png", width= 10, height= 10)
```

##### P915 length division 
```{r}
#Black drum
min(p915_len_f %>% filter(Speciescommonname %in% "black drum") %>% dplyr::select(Length))
max(p915_len_f %>% filter(Speciescommonname %in% "black drum", Length < 9999) %>% dplyr::select(Length))

values <- 1:883
breaks <- seq(0, 883, by = 50)
assigned_values <- seq(50, 850, by = 50)
result <- cut(values, breaks, labels = assigned_values) #cut values based on cut points (breaks), labels for resulting category, default is (a, b)
result_numeric <- as.numeric(as.character(result))
df <- data.frame(Length = values, Assigned_length = result_numeric)

t2 <- p915_len_f %>% filter(Speciescommonname %in% "black drum")  %>% left_join(df, by= "Length")
t2_summary <- t2 %>% group_by(Assigned_length) %>% summarize(count= n())

ggplot(t2, aes(x = Assigned_length)) +
  geom_histogram(binwidth = 50) + standard_theme

#Red drum
min(p915_len_f %>% filter(Speciescommonname %in% "red drum") %>% dplyr::select(Length))
max(p915_len_f %>% filter(Speciescommonname %in% "red drum", Length < 9999) %>% dplyr::select(Length))

values <- 1:883
breaks <- seq(0, 883, by = 50)
assigned_values <- seq(50, 850, by = 50)

values <- 114:1257
breaks <- seq(0, 1300, by = 50)
assigned_values <- seq(50, 1300, by = 50)
result <- cut(values, breaks, labels = assigned_values) #cut values based on cut points (breaks), labels for resulting category, default is (a, b)
result_numeric <- as.numeric(as.character(result))
df <- data.frame(Length = values, Assigned_length = result_numeric)

t2 <- p915_len_f %>% filter(Speciescommonname %in% "red drum")  %>% left_join(df, by= "Length")
t2_summary <- t2 %>% group_by(Assigned_length) %>% summarize(count= n())

ggplot(t2, aes(x = Assigned_length)) +
  geom_histogram(binwidth = 50) + standard_theme


ggplot(p915_len_f %>% filter(Speciescommonname %in% "spotted seatrout"), aes(x = Length)) +
  geom_histogram(binwidth = 50) + standard_theme

```

#### Environmental

```{r}
p915_CPUEedt %>% ggplot() + geom_histogram(aes(x= Ssal)) + standard_theme
p915_CPUEedt %>% ggplot() + geom_histogram(aes(x= Depth)) + standard_theme
p915_CPUEedt %>% ggplot() + geom_histogram(aes(x= Stemp)) + standard_theme
p915_CPUEedt %>% ggplot() + geom_histogram(aes(x= Sdo)) + standard_theme

p120_CPUEedt %>% ggplot() + geom_histogram(aes(x= Ssal)) + standard_theme
p120_CPUEedt %>% ggplot() + geom_histogram(aes(x= Depth)) + standard_theme
p120_CPUEedt %>% ggplot() + geom_histogram(aes(x= Stemp)) + standard_theme
p120_CPUEedt %>% ggplot() + geom_histogram(aes(x= Sdo)) + standard_theme

p195_CPUEedt %>% ggplot() + geom_histogram(aes(x= Salinitysurface)) + standard_theme
p195_CPUEedt %>% ggplot() + geom_histogram(aes(x= Depthstart)) + standard_theme
p195_CPUEedt %>% ggplot() + geom_histogram(aes(x= Tempsurface)) + standard_theme
p195_CPUEedt %>% ggplot() + geom_histogram(aes(x= Sdo)) + standard_theme
```

Conclusion here is that the values are consistent throughout the surveys in May, June and September. My main concern was that surface salinity reached 0 in P915, but this is consistent throughout surveys.
