---
title: "gJam_inference_burn"
format: html
editor: visual
---

```{r}
source("~/Documents/GitHub/NCBlueCrab_Predators/Scripts/Load.SDM.Final.R")

df <- df_CPUE_length_wide_both

df <- df %>% mutate(logsmallbluecrabP120= log(smallbluecrabP120+1), logreddrumP915forageP915= log(reddrumP915forageP915+1), logreddrumP915forageP120= log(reddrumP915forageP120+1))
```

#### Red drum 

##### Modo1
```{r}
#5000, 800
xdata <- df %>% dplyr::select(avgdepth, avgstemp, avgssal, avgsdo, NoFishRest, Yearfactor)
ydata <- df %>% dplyr::select(reddrumP915, logsmallbluecrabP120, logreddrumP915forageP120, logreddrumP915forageP915) 
ml <- list(ng = 5000, burnin = 800, typeNames = 'CA')
formula_str <- paste("~", paste(colnames(xdata), collapse = " + "))
modo1 <- gjam(formula= as.formula(formula_str), xdata = xdata, ydata = ydata, modelList = ml)
save(modo_env, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Red_drum/Env_bc_forage/modo1/modo1.RData")
plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = '/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Red_drum/Env_bc_forage/modo1')
gjamPlot(output = modo_env, plotPars = plot)
```

##### Modo2
```{r}
#10,000, 400

```

##### Modo3
```{r}
#20,000, 8,000
xdata <- df %>% dplyr::select(avgdepth, avgstemp, avgssal, avgsdo, NoFishRest, Yearfactor)
ydata <- df %>% dplyr::select(reddrumP915, logsmallbluecrabP120) 
ml <- list(ng = 5000, burnin = 800, typeNames = 'CA')
formula_str <- paste("~", paste(colnames(xdata), collapse = " + "))
modo_env_bc2 <- gjam(formula= as.formula(formula_str), xdata = xdata, ydata = ydata, modelList = ml)
save(modo_env_bc2, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Env_bc/modo2/modo_env_bc2.RData")
plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = '/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Env_bc/modo2')
gjamPlot(output = modo_env, plotPars = plot)
```

##### Modo4
```{r}

```

