---
title: "Boxplots"
format: html
editor: visual
---

```{r}
packages <- c("ggplot2", "tidyverse", "lubridate", "sf", "sp", "dplyr", "rnaturalearth", "readr", "readxl", "spatialEco", "rstatix", "viridis", "BBmisc", "corrplot")
invisible(lapply(packages, library, character.only= TRUE))
library(ggpubr)

standard_theme <- theme_bw() + theme(panel.border = element_rect(fill=NA, colour = "black")) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.text.align= 0, legend.title= element_text(size = 14), legend.text = element_text(size= 12), axis.text=element_text(size=12), axis.title=element_text(size=14))
```

```{r}
prediction_boxplot <- read_excel("/users/sallydowd/Google Drive/My Drive/Research/Ch1Data/Tables/prediction_new.xlsx", sheet=1) 
df <- prediction_boxplot %>% filter(!Model %in% c("Environment", "Blue crab", "Prey"))
df$Model < - factor(df$Model, levels=c("Environment + BC", "Environment + prey", "Environment + BC + prey"))
```

#### Original: Part 1

##### Env+BC

```{r}
#Environment + BC
t1 <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Red drum" & Model %in% "Environment + BC")) + ggtitle(expression(paste("Red drum"))) + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.20, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.25, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.20, label= "") + ylim(-0.30, 0.30) +theme(axis.text.x=element_blank())

t2 <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Southern kingfish" & Model %in% "Environment + BC")) + ggtitle(expression(paste("Southern kingfish"))) + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.26, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.26, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.28, label= "") + ylim(-0.02, 0.285) +theme(axis.text.x=element_blank())

t3 <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Black drum" & Model %in% "Environment + BC")) + ggtitle(expression(paste("Black drum"))) + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + ylim(-1.2, 0.8) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.6, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.6, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.75, label= "") +theme(axis.text.x=element_blank())
library(grid)
fig1 <- ggarrange(t1 + rremove("ylab") + rremove("xlab"),t2 + rremove("ylab") + rremove("xlab"),t3 + rremove("ylab") + rremove("xlab"), nrow= 1, labels= "A)", font.label= list(face= "plain"))
```

##### Env+forage

```{r}
#Environment + forage
t1_prey <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Red drum" & Model %in% "Environment + prey")) + ggtitle(expression(paste("Red drum"))) + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.20, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.25, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.20, label= "") + ylim(-0.30, 0.30) +theme(axis.text.x=element_blank())

t2_prey <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Southern kingfish" & Model %in% "Environment + prey")) + ggtitle(expression(paste("Southern kingfish"))) + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.26, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.26, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.28, label= "") + ylim(-0.02, 0.285) +theme(axis.text.x=element_blank())

t3_prey <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Black drum" & Model %in% "Environment + prey")) + ggtitle(expression(paste("Black drum"))) + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + ylim(-1.2, 0.8) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.6, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.6, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.75, label= "") +theme(axis.text.x=element_blank())

fig2 <- ggarrange(t1_prey + rremove("ylab") + rremove("xlab"),t2_prey + rremove("ylab") + rremove("xlab"),t3_prey + rremove("ylab") + rremove("xlab"), nrow= 1, labels= "B)", font.label= list(face= "plain"))
```

##### Env+BC+forage

```{r}
#Environment + BC + forage
t1_BC_prey <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Red drum" & Model %in% "Environment + BC + prey")) + ggtitle(expression(paste("Red drum"))) + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.20, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.25, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.20, label= "") + ylim(-0.30, 0.30)

t2_BC_prey <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Southern kingfish" & Model %in% "Environment + BC + prey")) + ggtitle(expression(paste("Southern kingfish"))) + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.26, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.26, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.28, label= "") + ylim(-0.02, 0.285)

t3_BC_prey <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Black drum" & Model %in% "Environment + BC + prey")) + ggtitle(expression(paste("Black drum"))) + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + ylim(-1.2, 0.8) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.6, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.6, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.75, label= "")

fig3 <- ggarrange(t1_BC_prey + rremove("ylab") + rremove("xlab"),t2_BC_prey + rremove("ylab") + rremove("xlab"),t3_BC_prey + rremove("ylab") + rremove("xlab"), nrow= 1, labels= "C)", font.label= list(face= "plain"))
```

#####Combo

```{r}
#combo
final <- ggarrange(fig1,fig2,fig3, nrow=3)
annotate_figure(final, left= textGrob(expression(paste("R"^"2")), rot= 90), bottom= textGrob("Model type"))
ggsave("/users/sallydowd/Desktop/test.png", width= 9,height= 10, dpi= 300)
```

#### New: Part 1

##### Red drum

```{r}
rd1 <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Red drum")) + ggtitle(expression(paste("Red drum"))) + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + labs(tag= "A)") + facet_wrap(~factor(Model, c("Environment + BC", "Environment + prey", "Environment + BC + prey")))+ geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.16, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.16, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.21, label= "") + ylim(-0.30, 0.23)

rd2 <- ggplot(subset(df, Species %in% "Red drum")) + geom_boxplot(aes(lower= meanRMSE - sdRMSE, upper= meanRMSE + sdRMSE, middle= meanRMSE, ymin= meanRMSE- 1.5*sdRMSE, ymax= meanRMSE+1.5*sdRMSE, x= Model_type), stat= "identity") + ggtitle("Red drum") + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab("RMSE") + labs(tag= "B)") + expand_limits(y= c(0.0015, 0.0083)) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.0072, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.0072, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.0080, label= "") +  facet_wrap(~factor(Model, c( "Environment + BC", "Environment + prey", "Environment + BC + prey")))
fig <- ggarrange(rd1, rd2, nrow= 2)
ggsave("/users/sallydowd/Google Drive/My Drive/Research/Ch1Data/Figures/To_edit/reddrum_metrics.pdf", width= 9, height= 10, dpi= 500)
```

##### Southern kingfish

```{r}
sk1 <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Southern kingfish")) + ggtitle(expression(paste("Southern kingfish"))) + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + labs(tag= "A)") + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.18, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.18, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.20, label= "") + ylim(-0.02, 0.22) + facet_wrap(~factor(Model, c("Environment + BC", "Environment + prey", "Environment + BC + prey")))

sk2 <- ggplot(subset(df, Species %in% "Southern kingfish")) + geom_boxplot(aes(lower= meanRMSE - sdRMSE, upper= meanRMSE + sdRMSE, middle= meanRMSE, ymin= meanRMSE- 1.5*sdRMSE, ymax= meanRMSE+1.5*sdRMSE, x= Model_type), stat= "identity") + ggtitle("Southern kingfish") + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab("RMSE") + labs(tag= "B)") + expand_limits(y= c(0.00050, 0.00105)) +  facet_wrap(~factor(Model, c( "Environment + BC", "Environment + prey", "Environment + BC + prey"))) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.00097, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.00097, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.00102, label= "") 
ggarrange(sk1, sk2, nrow= 2)
ggsave("/users/sallydowd/Google Drive/My Drive/Research/Ch1Data/Figures/To_edit/sk_metrics.pdf", width= 9, height= 10, dpi= 500)
```

##### Black drum

```{r}
bd1 <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Black drum")) + ggtitle(expression(paste("Black drum"))) + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + labs(tag= "A)") + facet_wrap(~factor(Model, c("Environment + BC", "Environment + prey", "Environment + BC + prey"))) + ylim(-1.2, 0.9) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.65, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.65, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.83, label= "") + facet_wrap(~factor(Model, c("Environment + BC", "Environment + prey", "Environment + BC + prey")))

bd2 <- ggplot(subset(df, Species %in% "Black drum")) + geom_boxplot(aes(lower= meanRMSE - sdRMSE, upper= meanRMSE + sdRMSE, middle= meanRMSE, ymin= meanRMSE- 1.5*sdRMSE, ymax= meanRMSE+1.5*sdRMSE, x= Model_type), stat= "identity") + ggtitle("Black drum") + scale_x_discrete(labels= c("GAM", "gJam traditional", "gJam conditional")) + standard_theme+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab("RMSE") + labs(tag= "B)") +  facet_wrap(~factor(Model, c( "Environment + BC", "Environment + prey", "Environment + BC + prey"))) + ylim(0.000, 0.0113) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.0095, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.0095, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.0106, label= "") 
ggarrange(bd1, bd2, nrow= 2)
ggsave("/users/sallydowd/Google Drive/My Drive/Research/Ch1Data/Figures/To_edit/bd_metrics.pdf", width= 9, height= 10, dpi= 500)
```

#### Part 2

```{r}
prediction_boxplot2 <- read_excel("/users/sallydowd/Google Drive/My Drive/Research/Ch1Data/Tables/prediction_new.xlsx", sheet=2) 
df <- prediction_boxplot2
df$Prediction < - factor(df$Prediction, levels=c("Traditional", "Conditional"))
```

##### R2

```{r}
rd_p2 <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Red drum")) + scale_x_discrete(labels= c("1a", "2a", "3a")) + standard_theme+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + labs(tag= "A)") + facet_wrap(~factor(Prediction, c("Traditional", "Conditional"))) + 
geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.80, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.95, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.80, label= "") + ylim(-1.2, 1.0) + theme(axis.text.x = element_text(angle = 360)) + ggtitle("Red drum")

sk_p2 <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Southern kingfish")) + scale_x_discrete(labels= c("1a", "2a", "3a")) + standard_theme+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + labs(tag= "B)") + facet_wrap(~factor(Prediction, c("Traditional", "Conditional"))) + expand_limits(y= c(0.0015, 0.23)) + 
geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.20, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.22, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 0.20, label= "") + theme(axis.text.x = element_text(angle = 360)) + ggtitle("Southern kingfish")

bd_p2 <- ggplot() + geom_boxplot(aes(lower= meanR2 - sdR2, upper= meanR2 + sdR2, middle= meanR2, ymin= meanR2- 1.5*sdR2, ymax= meanR2+1.5*sdR2, x= Model_type), stat= "identity", data= subset(df, Species %in% "Black drum")) + scale_x_discrete(labels= c("1a", "2a", "3a")) + standard_theme+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("R"^"2"))) + labs(tag= "C)") + facet_wrap(~factor(Prediction, c("Traditional", "Conditional"))) + expand_limits(y= c(-1, 2.5)) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 2, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 2.4, label= "") + geom_bracket(xmin= 2.1, xmax=3, y.position= 2, label= "")  + theme(axis.text.x = element_text(angle = 360)) + ggtitle("Black drum")

fig <- ggarrange(rd_p2 + rremove("xlab") + rremove("ylab"), sk_p2 + rremove("xlab") + rremove("ylab"), bd_p2 + rremove("xlab") + rremove("ylab"), ncol= 3)
library(grid)
annotate_figure(fig, bottom= textGrob("Model type"), left= textGrob(expression(paste("R"^"2")), rot= 90))
ggsave("/users/sallydowd/Google Drive/My Drive/Research/Ch1Data/Figures/To_edit/CV_p2_metrics.pdf", width= 12, height= 5, dpi= 500)
```

##### RMSE

```{r}
rd_p3 <- ggplot() + geom_boxplot(aes(lower= meanRMSE - sdRMSE, upper= meanRMSE + sdRMSE, middle= meanRMSE, ymin= meanRMSE- 1.5*sdRMSE, ymax= meanRMSE+1.5*sdRMSE, x= Model_type), stat= "identity", data= subset(df, Species %in% "Red drum")) + scale_x_discrete(labels= c("1", "2", "3")) + standard_theme+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("RMSE"))) + labs(tag= "A)") + facet_wrap(~factor(Prediction, c("Traditional", "Conditional"))) + theme(axis.text.x = element_text(angle = 360)) + expand_limits(y= c(0, 0.015)) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.0135, label= "") + geom_bracket(xmin= 1, xmax=3, y.position= 0.0145, label= "") + geom_bracket(xmin= 2.1, xmax= 2.9, y.position= 0.0135, label= "") + ggtitle("Red drum")

sk_p3 <- ggplot() + geom_boxplot(aes(lower= meanRMSE - sdRMSE, upper= meanRMSE + sdRMSE, middle= meanRMSE, ymin= meanRMSE- 1.5*sdRMSE, ymax= meanRMSE+1.5*sdRMSE, x= Model_type), stat= "identity", data= subset(df, Species %in% "Southern kingfish")) + scale_x_discrete(labels= c("1", "2", "3")) + standard_theme+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("RMSE"))) + labs(tag= "B)") + facet_wrap(~factor(Prediction, c("Traditional", "Conditional"))) + theme(axis.text.x = element_text(angle = 360)) + expand_limits(y= c(0.0004, 0.00155)) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.00145, label= "") + geom_bracket(xmin= 1, xmax=3, y.position=0.00152, label= "") + geom_bracket(xmin= 2.1, xmax= 2.9, y.position= 0.00145, label= "") + ggtitle("Southern kingfish")

bd_p3 <- ggplot() + geom_boxplot(aes(lower= meanRMSE - sdRMSE, upper= meanRMSE + sdRMSE, middle= meanRMSE, ymin= meanRMSE- 1.5*sdRMSE, ymax= meanRMSE+1.5*sdRMSE, x= Model_type), stat= "identity", data= subset(df, Species %in% "Black drum")) + scale_x_discrete(labels= c("1", "2", "3")) + standard_theme+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Model type") + ylab(expression(paste("RMSE"))) + labs(tag= "C)") + facet_wrap(~factor(Prediction, c("Traditional", "Conditional"))) + theme(axis.text.x = element_text(angle = 360)) + expand_limits(y= c(0.0004, 0.0115)) + geom_bracket(xmin= 1, xmax= 1.9, y.position= 0.0098, label= "") + geom_bracket(xmin= 1, xmax=3, y.position=0.011, label= "") + geom_bracket(xmin= 2.1, xmax= 2.9, y.position= 0.0098, label= "") + ggtitle("Black drum")

fig <- ggarrange(rd_p3 + rremove("xlab") + rremove("ylab"), sk_p3 + rremove("xlab") + rremove("ylab"), bd_p3 + rremove("xlab") + rremove("ylab"), ncol= 3)
library(grid)
annotate_figure(fig, bottom= textGrob("Model type"), left= textGrob(expression(paste("RMSE")), rot= 90))
ggsave("/users/sallydowd/Google Drive/My Drive/Research/Ch1Data/Figures/To_edit/CV_p3_metrics.pdf", width= 12, height= 5, dpi= 500)
```
