---
title: "Data.inclusion"
format: html
editor: visual
---

```{r}
#Load packages and functions 
packages <- c("ggplot2", "tidyverse", "lubridate", "sf", "sp", "dplyr", "rnaturalearth", "readr", "readxl", "spatialEco", "rstatix", "viridis", "BBmisc", "corrplot")
invisible(lapply(packages, library, character.only= TRUE))

standard_theme <- theme_bw() + theme(panel.border = element_rect(fill=NA, colour = "black")) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.text.align= 0, legend.title= element_text(size = 12), legend.text = element_text(size= 10), axis.text=element_text(size=10), axis.title=element_text(size=12))
world <- ne_countries(scale = "medium", returnclass = "sf")

#Load in dataset pre averaging on environmental variables
CPUE_dfs_gridded_final_length <- read.csv("~/Desktop/Ch1Data/CPUE/CPUE_all_grid_pred_multi.02.12.24.csv")
CPUE_dfs_gridded_final_length <- CPUE_dfs_gridded_final_length[,-1]

#Load in gridIDs
grid_ids <- read.csv("/Users/sallydowd/Documents/GitHub/NCBlueCrab_Predators/Data/gridIDs.csv")

df <- CPUE_dfs_gridded_final_length %>% filter(Month %in% c(5,6)) %>% filter(gridID %in% grid_ids$grid_cells)
```

```{r}
ggplot(data = world) + geom_sf() + geom_sf(data = subset(globe_grid_30, ID %in% grid_ids$grid_cells), fill = NA) + geom_point(aes(y= Latitude, x= Longitude, col= Survey), data=df) + coord_sf(xlim=c(-78, -75), ylim=c(33.5,37), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + standard_theme + scale_color_manual(values= c("steelblue", "#009E73", "#E69F00"), name= "Survey") + coord_sf(xlim=c(-78.900147, -75.263672), ylim=c(33.802938,36.672128), expand = TRUE) + guides(color = guide_legend(override.aes = list(size = 2)))
ggsave("~/Desktop/Ch1Data/Figures/survey_env_determination.jpeg", width= 7, height=5)
```

```{r}
#Just without P120 
ggplot(data = world) + geom_sf() + geom_sf(data = subset(globe_grid_30, ID %in% grid_ids$grid_cells), fill = NA) + geom_point(aes(y= Latitude, x= Longitude, col= Survey), data=subset(df, !Survey %in% "P195")) + coord_sf(xlim=c(-78, -75), ylim=c(33.5,37), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + standard_theme + scale_color_manual(values= c("steelblue", "#E69F00"), name= "Survey") + coord_sf(xlim=c(-78.900147, -75.263672), ylim=c(33.802938,36.672128), expand = TRUE) + guides(color = guide_legend(override.aes = list(size = 2)))
ggsave("~/Desktop/Ch1Data/Figures/survey_env_determination2.jpeg", width= 7, height=5)
```

