---
title: "Grid_ss"
format: html
editor: visual
---

#### Load in data

```{r}
packages <- c("ggplot2", "tidyverse", "lubridate", "sf", "sp", "dplyr", "rnaturalearth", "readr", "readxl", "spatialEco", "rstatix", "viridis", "BBmisc", "corrplot")
invisible(lapply(packages, library, character.only= TRUE))

standard_theme <- theme_bw() + theme(panel.border = element_rect(fill=NA, colour = "black")) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.text.align= 0, legend.title= element_text(size = 12), legend.text = element_text(size= 10), axis.text=element_text(size=10), axis.title=element_text(size=12))

#Load CPUE datasets
p915_CPUE <- read_csv("/users/sallydowd/Google Drive/My Drive/Research/Ch1Data/P915/p915_CPUE_new.csv")
setwd("~/Documents/GitHub/NCBlueCrab_Predators")
p120_CPUE <- read_csv("Data/P120/Finalized/p120_CPUE.csv")
p195_CPUE <- read_csv("Data/P195/Finalized/p195_CPUE.csv")

#Filter datasets: leave it as year-around!
p915_CPUEedt <- p915_CPUE %>% dplyr::select(-...1, -Obs, -Weather, -Weather, -Sedsize, -Btmcomp, -doy, -Wbdytype, -Wbd, -Sample, -Ph, -Quad, -Secchi) %>% rename("Location" = "Area", "Strata/station"= "Strata") %>% filter(between(Year, 2001, 2021),Month== c(5,6)) 
p120_CPUEedt <- p120_CPUE %>% filter(Core== 1|Core==2) %>% dplyr::select(-...1, -Program, -Nbrrec3, -Time, -Duration, -doy, -Core, -Sedsize, -Btmcomp, -Secchi) %>% rename("Strata/station"= "Station") %>% filter(between(Year, 2001, 2021), Month== c(5,6)) %>% dplyr::select(-Photoperiod)
p195_CPUEedt <- p195_CPUE %>% dplyr::select(-...1, -Timestart, -Duration, -Depthend, -Wbdytype, -Wbd, -Speciesscientificname, -Depthzone, -Secchi_depthcm) %>% rename("Ssal" = "Salinitysurface", "Bsal"= "Salinitybottom", "Stemp"= "Tempsurface", "Btemp"= "Tempbottom", "Latitude"= "Latitudestart", "Longitude"= "Longitudestart", "Colnum"= "Numbertotal", "Control1"= "Eventname", "Strata/station"= "Stationcode", "Depth"= "Depthstart") %>% filter(between(Year, 2001, 2021)) %>% dplyr::select(-Photoperiod)

##All same column names! 
colnames(p915_CPUEedt)
colnames(p120_CPUEedt)
colnames(p195_CPUEedt)

p915_CPUEedt <- p915_CPUEedt %>% drop_na(Latitude, Longitude)
p915_CPUEedt$Survey <- "P915"
p120_CPUEedt <- p120_CPUEedt  %>% drop_na(Latitude, Longitude)
p120_CPUEedt$Survey <- "P120"
p195_CPUEedt <- p195_CPUEedt  %>% drop_na(Latitude, Longitude)
p195_CPUEedt$Survey <- "P195"

CPUE_all <- rbind(p915_CPUEedt, p120_CPUEedt, p195_CPUEedt)
CPUE_all$lat_lon <- paste(CPUE_all$Latitude, CPUE_all$Longitude, sep= "_")

##Load grids
globe_bb <- matrix(c(-78.900147,33.802938,
                      -78.900147,36.672128,
                      -75.263672,36.672128,
                     -75.263672, 33.802938,
                     -78.900147,33.802938), byrow = TRUE, ncol = 2) %>% list() %>% st_polygon() %>% st_sfc(., crs = 4326)
globe_grid_30 <- st_make_grid(x= globe_bb, n = c(30,30), crs = 4326, what = 'polygons') %>% st_sf('geometry' = ., data.frame('ID' = 1:length(.))) #grid is 0.13° by 0.13° (14.4 km)

globe_grid_60 <- st_make_grid(x= globe_bb, n = c(60,60), crs = 4326, what = 'polygons') %>% st_sf('geometry' = ., data.frame('ID' = 1:length(.))) #grid is 0.06° by 0.06° (5.5 km b/c half of 0.13 which was 10)

globe_grid_15 <- st_make_grid(x= globe_bb, n = c(15,15), crs = 4326, what = 'polygons') %>% st_sf('geometry' = ., data.frame('ID' = 1:length(.))) 
```

#### 0.06 x 0.06 size

```{r}
gridded_0.06 <- read.csv("~/Documents/GitHub/NCBlueCrab_Predators/Data/gridded_10.02.23.5km.csv")
#Join CPUE data to gridded dataset

#Join CPUE dataset to lat/lons and grid IDs
CPUE_all_grid <- CPUE_all %>% left_join(gridded_0.06, by= "lat_lon") %>% dplyr::select(-X) %>% drop_na(gridID)
summary(is.na(CPUE_all_grid))

#Small outlier filtering through CPUE and count dataset formation 
CPUE_grid_count <- CPUE_all_grid %>% group_by(gridID, Month, Survey, Year, Speciescommonname) %>% mutate(avg_count= mean(Colnum))

CPUE_grid_count_avg <- CPUE_grid_count %>% ungroup() %>% mutate(Stemp= ifelse(CPUE_grid_count$Stemp <= 11.8, NA, CPUE_grid_count$Stemp), Ssal= ifelse(CPUE_grid_count$Ssal==0.0, NA, CPUE_grid_count$Ssal), Sdo= ifelse(CPUE_grid_count$Sdo==0.0, NA, CPUE_grid_count$Sdo), Depth= ifelse(CPUE_grid_count$Depth==0.0, NA, CPUE_grid_count$Depth)) %>% group_by(Year, gridID, Month) %>% mutate(avg_depth= mean(Depth, na.rm= TRUE), avg_ssal= mean(Ssal, na.rm= TRUE), avg_bsal= mean(Bsal, na.rm= TRUE), avg_stemp= mean(Stemp, na.rm= TRUE), avg_btemp= mean(Btemp, na.rm= TRUE), avg_sdo= mean(Sdo, na.rm= TRUE), avg_bdo= mean(Bdo, na.rm= TRUE), avg_latitude= mean(Latitude, na.rm= TRUE), avg_longitude= mean(Longitude), na.rm= TRUE) %>% dplyr::select(-avg_bsal, -avg_btemp, -avg_bdo, -Stemp, -Btemp, -Sdo, -Bdo, -Ssal, -Bsal, -Season, -Sedsize_new, -Btmcomp_new, -Depth, -na.rm, -avg_latitude, -avg_longitude)

summary(is.na(CPUE_grid_count_avg))
CPUE_grid_count_avg <- CPUE_grid_count_avg %>% mutate_all(~ifelse(is.nan(.), NA, .)) %>% drop_na() #drops 4610 points 

CPUE_grid_count_avg_edt <- CPUE_grid_count_avg %>% dplyr::select(-Latitude, -Longitude, -lat_lon, -Day, -Location, -Colnum, -Date, -Ym_date, -Sciname, -"Strata/station", -Month, -Control1)
CPUE_grid_count_avg_edt <- CPUE_grid_count_avg_edt %>% group_by(Year, gridID, Speciescommonname, Survey, Month) %>% distinct(avg_count, .keep_all= TRUE)

df_count <- CPUE_grid_count_avg_edt 
df_count$Speciescommonname <- gsub(" ", "", df_count$Speciescommonname)
colnames(df_count) <- gsub(pattern = "_", replacement = "", colnames(df_count))
df_count$SpeciesSurvey <- paste(df_count$Speciescommonname, df_count$Survey, sep= "")
df_count_wide_both06 <- df_count %>% filter(Survey == "P915"|Survey == "P120") %>% ungroup() %>% dplyr::select(-c(Speciescommonname, Survey)) %>% pivot_wider(names_from = "SpeciesSurvey", values_from = "avgcount") %>% drop_na()
```

#### 0.24 x 0.24 size

```{r}
gridded_0.24 <- read.csv("~/Documents/GitHub/NCBlueCrab_Predators/Data/gridded_24km.01.30.24.csv")

#Join CPUE dataset to lat/lons and grid IDs
CPUE_all_grid <- CPUE_all %>% left_join(gridded_0.24, by= "lat_lon") %>% dplyr::select(-X) %>% drop_na(gridID)
summary(is.na(CPUE_all_grid))

#Small outlier filtering through CPUE and count dataset formation 
CPUE_grid_count <- CPUE_all_grid %>% group_by(gridID, Month, Survey, Year, Speciescommonname) %>% mutate(avg_count= mean(Colnum))

CPUE_grid_count_avg <- CPUE_grid_count %>% ungroup() %>% mutate(Stemp= ifelse(CPUE_grid_count$Stemp <= 11.8, NA, CPUE_grid_count$Stemp), Ssal= ifelse(CPUE_grid_count$Ssal==0.0, NA, CPUE_grid_count$Ssal), Sdo= ifelse(CPUE_grid_count$Sdo==0.0, NA, CPUE_grid_count$Sdo), Depth= ifelse(CPUE_grid_count$Depth==0.0, NA, CPUE_grid_count$Depth)) %>% group_by(Year, gridID, Month) %>% mutate(avg_depth= mean(Depth, na.rm= TRUE), avg_ssal= mean(Ssal, na.rm= TRUE), avg_bsal= mean(Bsal, na.rm= TRUE), avg_stemp= mean(Stemp, na.rm= TRUE), avg_btemp= mean(Btemp, na.rm= TRUE), avg_sdo= mean(Sdo, na.rm= TRUE), avg_bdo= mean(Bdo, na.rm= TRUE), avg_latitude= mean(Latitude, na.rm= TRUE), avg_longitude= mean(Longitude), na.rm= TRUE) %>% dplyr::select(-avg_bsal, -avg_btemp, -avg_bdo, -Stemp, -Btemp, -Sdo, -Bdo, -Ssal, -Bsal, -Season, -Sedsize_new, -Btmcomp_new, -Depth, -na.rm, -avg_latitude, -avg_longitude)

summary(is.na(CPUE_grid_count_avg))
CPUE_grid_count_avg <- CPUE_grid_count_avg %>% mutate_all(~ifelse(is.nan(.), NA, .)) %>% drop_na() #drops 4610 points 

CPUE_grid_count_avg_edt <- CPUE_grid_count_avg %>% dplyr::select(-Latitude, -Longitude, -lat_lon, -Day, -Location, -Colnum, -Date, -Ym_date, -Sciname, -"Strata/station", -Month, -Control1)
CPUE_grid_count_avg_edt <- CPUE_grid_count_avg_edt %>% group_by(Year, gridID, Speciescommonname, Survey, Month) %>% distinct(avg_count, .keep_all= TRUE)

df_count <- CPUE_grid_count_avg_edt 
df_count$Speciescommonname <- gsub(" ", "", df_count$Speciescommonname)
colnames(df_count) <- gsub(pattern = "_", replacement = "", colnames(df_count))
df_count$SpeciesSurvey <- paste(df_count$Speciescommonname, df_count$Survey, sep= "")
df_count_wide_both24 <- df_count %>% filter(Survey == "P915"|Survey == "P120") %>% ungroup() %>% dplyr::select(-c(Speciescommonname, Survey)) %>% pivot_wider(names_from = "SpeciesSurvey", values_from = "avgcount") %>% drop_na()
```

#### 0.12 x 0.12 size

```{r}
#Load data
df_count <- read_csv("~/Google Drive/My Drive/Research/Ch1Data/CPUE/CPUE_grid_count_avg_edt.11.21.23.csv")

df_count <- df_count %>% dplyr::select(-c(...1, CPUE, CPUE_stdzd, mean_CPUE, mean_CPUE_stdzd)) #need to remove or R will get confused 
df_count$Speciescommonname <- gsub(" ", "", df_count$Speciescommonname)
colnames(df_count) <- gsub(pattern = "_", replacement = "", colnames(df_count))
df_count$SpeciesSurvey <- paste(df_count$Speciescommonname, df_count$Survey, sep= "")
df_count_wide_both <- df_count %>% filter(Survey %in% "P915"|Survey %in% "P120") %>% dplyr::select(-Speciescommonname, -Survey) %>% ungroup() %>% pivot_wider(names_from = "SpeciesSurvey", values_from = "avgcount") %>% drop_na()
```

#### Fig. 1: bar plot

```{r}
#0.12: 
data <- data.frame(species = c("Red drum", "Black drum", "Southern kingfish", "Red drum", "Black drum", "Southern kingfish"), count = c(572,572,572, 181, 112, 68), pattern= c("0", "0", "0", "pos", "pos", "pos"), grid = c(.12,.12,.12,.12,.12,.12))

#0.06
df_count_wide_both06 %>% filter(blackdrumP915 > 0)
##397 observations total 
##Positive observations: red drum: 164, black drum: 130, southern kingfish: 65
##Zero observations: 233, 267, 332

data2 <- data.frame(species = c("Red drum", "Black drum", "Southern kingfish", "Red drum", "Black drum", "Southern kingfish"), count = c(397,397,397, 164, 130, 65), pattern= c("0", "0", "0", "pos", "pos", "pos"), grid = c(.06,.06,.06,.06,.06,.06))
data_t <- rbind(data, data2)

#0.24
df_count_wide_both24  %>% filter(southernkingfishP915 > 0)

data3 <- data.frame(species = c("Red drum", "Black drum", "Southern kingfish", "Red drum", "Black drum", "Southern kingfish"), count = c(432, 432, 432, 258, 220, 130), pattern= c("0", "0", "0", "pos", "pos", "pos"), grid = c(.24,.24,.24,.24,.24,.24))
data_t <- rbind(data, data2, data3)

data_t$grid <- factor(data_t$grid, levels = c(0.06, 0.12, 0.24))

ggplot(data_t, aes(x= grid, y = count, fill = species, alpha= pattern)) + standard_theme + labs(x= "Grid cell size", y= "Number of data records", fill= "Species") + scale_fill_manual(values= c("#0072B2", "#009E73", "#CC6666"), name= "Species") + geom_bar(stat= "identity") + guides(alpha = guide_legend(title = "Type of observation")) + scale_alpha_manual(values = c("pos" = 0.6, "neg" = 1), labels= "Positive encounter") + scale_x_discrete(labels= c("0.06° x 0.06°", "0.12° x 0.12°", "0.24° x 0.24°"))
ggsave("/Users/sallydowd/Desktop/Ch1Data/Figures/gridcell_just.jpeg", height= 5, width=7)
```

#### Fig. 2: grid pts

```{r}
#0.24
#join P915 CPUE and P120 CPUE with gridID dataset
gridID_both24 <- unique(df_count_wide_both24$gridID) 
gridded24 <- read.csv("~/Documents/GitHub/NCBlueCrab_Predators/Data/gridded_24km.01.30.24.csv")

p915_CPUEedt$lat_lon <- paste(p915_CPUEedt$Latitude, p915_CPUEedt$Longitude, sep= "_")
p915_CPUEedt_fig24 <- p915_CPUEedt %>% left_join(gridded24, by= "lat_lon") %>% filter(gridID %in% gridID_both24)

p120_CPUEedt$lat_lon <- paste(p120_CPUEedt$Latitude, p120_CPUEedt$Longitude, sep= "_")
p120_CPUEedt_fig24 <- p120_CPUEedt %>% left_join(gridded24, by= "lat_lon") %>% filter(gridID %in% gridID_both24)

#filter gridID dataset for only gridIDs with data
globe_grid_15_edt <- globe_grid_15 %>% rename("gridID"= "ID") %>% filter(gridID %in% gridID_both24)

t1 <- ggplot(data = world) + geom_sf() + geom_sf(data = globe_grid_15_edt, fill = NA) + coord_sf(xlim=c(-85, -70), ylim=c(25,40), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + geom_point(data = p915_CPUEedt_fig24, aes(x = Longitude, y = Latitude, colour= Survey), size = .5) + geom_point(data = p120_CPUEedt_fig24, aes(x = Longitude, y = Latitude, colour= Survey), size = .5) + scale_color_manual(values= c("steelblue", "#E69F00"), name= "Survey") + standard_theme + theme(legend.title= element_text(size = 14), legend.text = element_text(size= 12), axis.text=element_text(size=12),axis.title=element_text(size=14)) + guides(color = guide_legend(override.aes = list(size = 2))) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_sf(xlim=c(-78.5, -75.4), ylim=c(33.802938,36.672128), expand = TRUE) + ggtitle("D) 0.24° x 0.24°") 
```

```{r}
#0.12
#join P915 CPUE and P120 CPUE with gridID dataset
gridID_both <- unique(df_count_wide_both$gridID) 
gridded12 <- read.csv("~/Documents/GitHub/NCBlueCrab_Predators/Data/gridded_11.20.23.csv")

p915_CPUEedt$lat_lon <- paste(p915_CPUEedt$Latitude, p915_CPUEedt$Longitude, sep= "_")
p915_CPUEedt_fig12 <- p915_CPUEedt %>% left_join(gridded12, by= "lat_lon") %>% filter(gridID %in% gridID_both)

p120_CPUEedt$lat_lon <- paste(p120_CPUEedt$Latitude, p120_CPUEedt$Longitude, sep= "_")
p120_CPUEedt_fig12 <- p120_CPUEedt %>% left_join(gridded12, by= "lat_lon") %>% filter(gridID %in% gridID_both)

#filter gridID dataset for only gridIDs with data
globe_grid_30_edt <- globe_grid_30 %>% rename("gridID"= "ID") %>% filter(gridID %in% gridID_both)

t2 <- ggplot(data = world) + geom_sf() + geom_sf(data = globe_grid_30_edt, fill = NA) + coord_sf(xlim=c(-85, -70), ylim=c(25,40), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + geom_point(data = p915_CPUEedt_fig12, aes(x = Longitude, y = Latitude, colour= Survey), size = .5) + geom_point(data = p120_CPUEedt_fig12, aes(x = Longitude, y = Latitude, colour= Survey), size = .5)  + scale_color_manual(values= c("steelblue", "#E69F00"), name= "Survey") + standard_theme + theme(legend.title= element_text(size = 14), legend.text = element_text(size= 12), axis.text=element_text(size=12),axis.title=element_text(size=14)) + guides(color = guide_legend(override.aes = list(size = 2))) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_sf(xlim=c(-78.5, -75.4), ylim=c(33.802938,36.672128), expand = TRUE) + ggtitle("C) 0.12° x 0.12°") 

```

```{r}
#0.06
#join P915 CPUE and P120 CPUE with gridID dataset
gridID_both06 <- unique(df_count_wide_both06$gridID) 
gridded06 <- read.csv("~/Documents/GitHub/NCBlueCrab_Predators/Data/gridded_10.02.23.5km.csv")

p915_CPUEedt$lat_lon <- paste(p915_CPUEedt$Latitude, p915_CPUEedt$Longitude, sep= "_")
p915_CPUEedt_fig06 <- p915_CPUEedt %>% left_join(gridded06, by= "lat_lon") %>% filter(gridID %in% gridID_both06)

p120_CPUEedt$lat_lon <- paste(p120_CPUEedt$Latitude, p120_CPUEedt$Longitude, sep= "_")
p120_CPUEedt_fig06 <- p120_CPUEedt %>% left_join(gridded06, by= "lat_lon") %>% filter(gridID %in% gridID_both06)

#filter gridID dataset for only gridIDs with data
globe_grid_60_edt <- globe_grid_60 %>% rename("gridID"= "ID") %>% filter(gridID %in% gridID_both06)

t3 <- ggplot(data = world) + geom_sf() + geom_sf(data = globe_grid_60_edt, fill = NA) + coord_sf(xlim=c(-85, -70), ylim=c(25,40), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + geom_point(data = p915_CPUEedt_fig06, aes(x = Longitude, y = Latitude, colour= Survey), size = .5) + geom_point(data = p120_CPUEedt_fig06, aes(x = Longitude, y = Latitude, colour= Survey), size = .5)  + scale_color_manual(values= c("steelblue", "#E69F00"), name= "Survey") + standard_theme + theme(legend.title= element_text(size = 14), legend.text = element_text(size= 12), axis.text=element_text(size=12),axis.title=element_text(size=14)) + guides(color = guide_legend(override.aes = list(size = 2))) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_sf(xlim=c(-78.5, -75.4), ylim=c(33.802938,36.672128), expand = TRUE) + ggtitle("B) 0.06° x 0.06°")
```

```{r}
t4 <- ggplot(data = world) + geom_sf() + theme(panel.background = element_rect(fill = "white", colour = "black")) + geom_point(data = filter(p915_CPUEedt, !Latitude== 33.72389, !Latitude == 35.95528, !Latitude == 36.04694, !(Latitude > 34.5 & Longitude < -77.5)), aes(x = Longitude, y = Latitude, colour= Survey), size = .5) + geom_point(data = p120_CPUEedt, aes(x = Longitude, y = Latitude, colour= Survey), size = .5) + coord_sf(xlim=c(-78.5, -75.4), ylim=c(33.802938,36.672128), expand = TRUE)  + scale_color_manual(values= c("steelblue", "#E69F00"), name= "Survey") + standard_theme + theme(legend.title= element_text(size = 14), legend.text = element_text(size= 12), axis.text=element_text(size=12),axis.title=element_text(size=14)) + guides(color = guide_legend(override.aes = list(size = 2))) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ggtitle("A) Sampling points")
```

```{r}
library(ggpubr)
library(grid)

ya <- ggarrange(t4 + rremove("ylab") + rremove("xlab"), t3 + rremove("ylab") + rremove("xlab"), t2 + rremove("ylab") + rremove("xlab"), t1 + rremove("ylab") + rremove("xlab"), ncol= 4, nrow=1, common.legend=T) + theme(plot.margin = margin(0.25,0.25,0.25,0.25, "cm"))
annotate_figure(ya, left= textGrob("Latitude", rot= 90), bottom= textGrob("Longitude"))
ggsave("~/Desktop/gridded_map_compare.png", width= 12, height=4, dpi=300)


annotate_figure(figure, left = textGrob("Common y-axis", rot = 90, vjust = 1, gp = gpar(cex = 1.3)),
                    bottom = textGrob("Common x-axis", gp = gpar(cex = 1.3)))


#Save legend separately 
leg <- get_legend(t3)
as_ggplot(leg)
ggsave("~/Desktop/gridded_map_compare_legend.png", dpi=300, width=3, height=2)
```
