---
title: "Prey_abundance"
format: html
editor: visual
---

```{r}
packages <- c("ggplot2", "tidyverse", "lubridate", "sf", "sp", "dplyr", "rnaturalearth", "readr", "readxl", "spatialEco", "rstatix", "viridis", "BBmisc", "corrplot")
invisible(lapply(packages, library, character.only= TRUE))

standard_theme <- theme_bw() + theme(panel.border = element_rect(fill=NA, colour = "black")) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.text.align= 0, legend.title= element_text(size = 12), legend.text = element_text(size= 10), axis.text=element_text(size=10), axis.title=element_text(size=12))
```

```{r}
source("~/Documents/GitHub/NCBlueCrab_Predators/Scripts/Load.SDM.Final.R")
```

#### Appendix A: 

##### Figure 4:

```{r}
newdf <- df_CPUE_length_wide_both %>% group_by(Month, Year) %>% summarize(reddrumP915forage = sum(logreddrumP915forageP915), reddrumP120forage = sum(logreddrumP915forageP120), southernkingfishP915forage = sum(logsouthernkingfishP915forageP915), southernkingfishP120forage = sum(logsouthernkingfishP915forageP120), blackdrumP120forage = sum(logblackdrumP915forageP120)) %>% pivot_longer(cols= c(reddrumP915forage, reddrumP120forage, southernkingfishP915forage, southernkingfishP120forage, blackdrumP120forage), names_to= "Speciesforage", values_to= "Value") %>% mutate(Month=ifelse(Month == 5, "May", "June"))

newdf <- newdf %>% mutate(Speciesforage= fct_relevel(Speciesforage, "reddrumP120forage", "southernkingfishP120forage", "blackdrumP120forage", "southernkingfishP915forage", "reddrumP915forage")) 

cbPalette <- c("#999999", "#56B4E9", "#009E73", "#D55E00", "#CC79A7")

t3<- newdf %>% ungroup() %>% ggplot(aes(fill= Speciesforage, y= Value, x= Year)) + geom_bar(position="stack", stat="identity") + facet_wrap(~factor(Month, levels= c("May", "June")), scales= "free") + theme(panel.spacing= unit(1,"lines")) + standard_theme + scale_fill_manual(values=cbPalette) + scale_y_continuous(expand = c(0, 0)) + labs(fill= "Total prey index")
t3 + theme(legend.position = "none")
ggsave("/users/sallydowd/Desktop/test.jpeg", width= 8, height= 5, dpi= 300)
library(cowplot)
library(ggpubr)
leg <- get_legend(t3 + labs(fill= "Prey items consumed"))
as_ggplot(leg)
ggsave("~/Desktop/t32_legend.png", dpi=300, width=6, height=4)
```

##### Figure 6:
```{r}
t1 <- ggplot() + geom_histogram(aes(x= reddrumP915forageP915), data= df_CPUE_length_wide_both) + standard_theme + xlab("Red drum P915 total prey CPUE P915") + ylab("Count") + labs(tag= "A)")
ggplot() + geom_histogram(aes(x= logreddrumP915forageP915), data= df_CPUE_length_wide_both) + standard_theme + xlab("Log Red drum P915 total prey CPUE P915") + ylab("Count") + labs(tag= "A)")

t2 <- ggplot() + geom_histogram(aes(x= reddrumP915forageP120), data= df_CPUE_length_wide_both) + standard_theme + xlab("Red drum P120 total prey CPUE") + ylab("Count")
ggplot() + geom_histogram(aes(x= logreddrumP915forageP120), data= df_CPUE_length_wide_both) + standard_theme + xlab("Log Red drum P120 total prey CPUE") + ylab("Count")

t3 <- ggplot() + geom_histogram(aes(x= southernkingfishP915forageP915), data= df_CPUE_length_wide_both) + standard_theme + xlab("Southern kingfish P915 total prey CPUE") + ylab("Count") + labs(tag= "B)")
ggplot() + geom_histogram(aes(x= logsouthernkingfishP915forageP120), data= df_CPUE_length_wide_both) + standard_theme + xlab("Log Southern kingfish P120 total prey CPUE") + ylab("Count")

t4 <- ggplot() + geom_histogram(aes(x= southernkingfishP915forageP120), data= df_CPUE_length_wide_both) + standard_theme + xlab("Southern kingfish P120 total prey CPUE") + ylab("Count")
ggplot() + geom_histogram(aes(x= logsouthernkingfishP915forageP120), data= df_CPUE_length_wide_both) + standard_theme + xlab("Log southern kingfish P120 total prey CPUE") + ylab("Count")

t5 <- ggplot() + geom_histogram(aes(x= blackdrumP915forageP120), data= df_CPUE_length_wide_both) + standard_theme + xlab("Black drum P120 total prey CPUE") + ylab("Count") + labs(tag= "C)")
ggplot() + geom_histogram(aes(x= logblackdrumP915forageP120), data= df_CPUE_length_wide_both) + standard_theme + xlab("Log black drum P120 total prey CPUE") + ylab("Count") + labs(tag= "C)")


t6 <- ggplot() + geom_histogram(aes(x= smallbluecrabP120), data= df_CPUE_length_wide_both) + standard_theme + xlab("Blue crab P120 CPUE") + ylab("Count") + labs(tag= "D)")
ggplot() + geom_histogram(aes(x= logsmallbluecrabP120), data= df_CPUE_length_wide_both) + standard_theme + xlab("Log blue crab P120 CPUE") + ylab("Count") + labs(tag= "D)")
```

```{r}
library(ggpubr)
library(grid)
ya <- ggarrange(t1 + rremove("ylab"), t2 + rremove("ylab"), t3 + rremove("ylab"), t4 + rremove("ylab"), t5 + rremove("ylab"), t6 + rremove("ylab"), ncol= 2, nrow=3) + theme(plot.margin = margin(0.25,0.25,0.25,0.25, "cm"))
annotate_figure(ya, left= textGrob("Count", rot= 90))
ggsave("/users/sallydowd/Google Drive/My Drive/Research/Ch1Data/Figures/preyabundance.png", width= 13, height=12, dpi=300)
```
