---
title: "Tables"
format: html
editor: visual
---

```{r}
library(readxl)
library(sp)
library(gt)
```

#### Main text

##### Table 1:

```{r}
Species_foodweb <- read_excel("/users/sallydowd/Desktop/Ch1Data/Tables/Species_foodweb.xlsx")
tbl1 <- Species_foodweb %>% gt() %>% cols_width(Number ~ px(70), Species ~ px(100), "Consumed by" ~ px(150), Survey ~ px(70)) %>% cols_align(align= "center") %>% tab_style(style = cell_text(weight = "bold"), locations = cells_column_labels())
gtsave(data=tbl1, "/users/sallydowd/Desktop/Ch1Data/Tables/Species_foodweb.png")
```

##### Table 2: 
```{r}
GAM_gJam_inf <- read_excel("/users/sallydowd/Desktop/Ch1Data/Tables/GAM_gJam_inf.xlsx")

GAM_gJam_inf <- GAM_gJam_inf %>% mutate_if(is.numeric, as.character)
GAM_gJam_inf[is.na(GAM_gJam_inf)] <- "X"
colnames(GAM_gJam_inf) <- c("Model", "GAM ∆AIC 1", "gJam ∆DIC 1", "GAM ∆AIC 2", "gJam ∆DIC 2", "GAM ∆AIC 3", "gJam ∆DIC 3")

tbl2 <- GAM_gJam_inf %>% gt() %>% cols_width(everything() ~ px(100)) %>% cols_align(align= "center") %>% tab_style(style = cell_text(weight = "bold"), locations = cells_column_labels()) %>% tab_spanner(label= "Red drum", columns= c("GAM ∆AIC 1", "gJam ∆DIC 1")) %>% tab_spanner(label= "Southern kingfish", columns= c("GAM ∆AIC 2", "gJam ∆DIC 2")) %>% tab_spanner(label= "Black drum", columns= c("GAM ∆AIC 3", "gJam ∆DIC 3")) %>%  cols_label("Model" = "Model", "GAM ∆AIC 1" = "GAM ∆AIC", "GAM ∆AIC 2" = "GAM ∆AIC", "GAM ∆AIC 3" = "GAM ∆AIC", "gJam ∆DIC 1" = "gJam ∆DIC", "gJam ∆DIC 2" = "gJam ∆DIC", "gJam ∆DIC 3" = "gJam ∆DIC")
gtsave(data=tbl2, "/users/sallydowd/Desktop/Ch1Data/Tables/GAM_gJam_inf.png")

# %>% cols_width("Model" ~ px(100), "GAM ∆AIC 1" ~ px(70), "gJam ∆DIC 1" ~ px(70), "GAM ∆AIC 2" ~ px(70), "gJam ∆DIC 2" ~ px(70), "GAM ∆AIC 3" ~ px(70), "gJam ∆DIC 3" ~ px(70))
```


#### Appendix A:

##### Table 1:

```{r}
Methods_tbls <- read_excel("/users/sallydowd/Desktop/Ch1Data/Tables/Methods_tbls.xlsx")
tbl1 <- Methods_tbls %>% gt() %>% cols_width(everything() ~ px(120)) %>% cols_align(align= "center") %>% tab_style(style = cell_text(weight = "bold"), locations = cells_column_labels())
gtsave(data=tbl1, "/users/sallydowd/Desktop/Ch1Data/Tables/Methods_tbls.png")
```

##### Table 2: 
```{r}
GAM_inference_rd <- read_excel("/users/sallydowd/Desktop/Ch1Data/Tables/GAM_inference.xlsx", sheet=1)
GAM_inference_sk <- read_excel("/users/sallydowd/Desktop/Ch1Data/Tables/GAM_inference.xlsx", sheet=2)
GAM_inference_bd <- read_excel("/users/sallydowd/Desktop/Ch1Data/Tables/GAM_inference.xlsx", sheet=3)

tbl_rd <- GAM_inference_rd %>% gt() %>% cols_width("Model" ~ px(67), "GAM" ~ px(50), "Dev. explained" ~ px(57), "f(x)" ~ px(50), "s(avgdepth)" ~ px(70), "s(avgssal)" ~ px(65), "s(avgstemp)" ~ px(72), "s(avgsdo)" ~ px(65), "s(NoFishRest)" ~ px(80), "s(bluecrabP120)" ~ px(95), "s(totalpreyP915)" ~ px(95), "s(totalpreyP120)" ~ px(95)) %>% cols_align(align= "center") %>% tab_style(style = cell_text(weight = "bold"), locations = cells_column_labels()) %>% tab_options(table.font.size = px(10.5))
gtsave(data=tbl_rd, "/users/sallydowd/Desktop/Ch1Data/Tables/GAM_inference_rd.png")

tbl_sk <- GAM_inference_sk %>% gt() %>% cols_width("Model" ~ px(67), "GAM" ~ px(50), "Dev. explained" ~ px(57), "f(x)" ~ px(50), "s(avgdepth)" ~ px(70), "s(avgssal)" ~ px(65), "s(avgstemp)" ~ px(72), "s(avgsdo)" ~ px(65), "s(NoFishRest)" ~ px(80), "s(bluecrabP120)" ~ px(95), "s(totalpreyP915)" ~ px(95), "s(totalpreyP120)" ~ px(95)) %>% cols_align(align= "center") %>% tab_style(style = cell_text(weight = "bold"), locations = cells_column_labels()) %>% tab_options(table.font.size = px(10.5))
gtsave(data=tbl_sk, "/users/sallydowd/Desktop/Ch1Data/Tables/GAM_inference_sk.png")

tbl_bd <- GAM_inference_bd %>% gt() %>% cols_width("Model" ~ px(67), "GAM" ~ px(50), "Dev. explained" ~ px(57), "f(x)" ~ px(50), "s(avgdepth)" ~ px(70), "s(avgssal)" ~ px(65), "s(avgstemp)" ~ px(72), "s(avgsdo)" ~ px(65), "s(NoFishRest)" ~ px(80), "s(bluecrabP120)" ~ px(95), "s(totalpreyP915)" ~ px(95), "s(totalpreyP120)" ~ px(95)) %>% cols_align(align= "center") %>% tab_style(style = cell_text(weight = "bold"), locations = cells_column_labels()) %>% tab_options(table.font.size = px(10.5))
gtsave(data=tbl_bd, "/users/sallydowd/Desktop/Ch1Data/Tables/GAM_inference_bd.png")
```

