---
title: "P915DatasetSpecifics"
format: html
editor: visual
---

#### Overall data set description

Sampling for the Pamlico Sound Independent Gill Net Survey began March 1st, 2001 for Hyde and Dare counties (Neuse, New, Pamlico and Pungo River systems). Sampling in the Southern District (Cape Fear and New Rivers) began in April 2008 and 2018 for Back and Core Sound. Starting in 2008, more environmental data has been recorded (e.g: sediment size, bottom composition, depth). Sampling occurs twice a month between February 15th to December 15th (January is skipped). There are 32 core samples in each month as there are 8 areas x 2x a month x 2 samples for F-70 (main region) and then for PNWGNS river system as well. For the New and Cape Fear rivers there are 12 samples per month with 8 from the New River (2 areas x 2x a month x 2 samples- shallow and deep) and 4 from Cape Fear (1 area x 2x a month x 2 shallow samples).

Neuse River is divided into four areas, Pamlico River is divided into 3 areas, and Pungo river consists of 1 area. Overall, there are two regions with Region 1 encompassing areas of eastern Pamlico Sound beside the Outer Banks from southern Roanoke Island to northern end of Portsmouth Island with Region 2 including Hyde County bays from Stumpy Point to Abel's Bay and adjacent areas of western Pamlico.

A one minute by one minute grid was overlayed over the entire region. The two regions were divided into four areas (Hyde 1-4 or Dare 1-4). Grids are randomly selected and then separated into shallow and deep strata. Species are sampling with floating gill nets where the catch from all the nets comprises one sample. Soak times are equal to or under 12 hours. Beginning in 2007, the Southern district soak times are reduced to four hours from April to September to reduce loggerhead bycatch.

#### CPUE dataset specifics

Each line of data in the CPUE dataset represents a single gillnet sampling event. When there are two rows at the same Strata on the same day, it is with the shallow and deep datasets. The set ID is represented by the control number or Sample where Sample = COMPRESS(YEAR\|\|MONTH\|\|DAY\|\|AREA\|\|QUAD\|\|GRID\|\|MODE\|\|TIME). The original datasets requested have an error with the Sample IDs. However, the Control \# is comparable to the Sample ID just utilizing numbers over the compressed format. The Control \# correlates with the record ID in the biological data set and is different for shallow/deep water sets in the same area. However, the Control \# can't be used as when P915 began, each sample was split on data sheets between half and whole mesh sizes. The different mesh sizes received different control numbers even if they were from same sampling event. The sample variable is a way to pool across the half and whole meshes on separate data sheets from earlier years. Therefore the sample id should be used to get the correct number of sampling events by year in CPUE files. Quadrants can be deep (2) or shallow (1) sets. A full day effort can be found from combining the two rows on the same strata/day with deep and shallow sets or keeping them separate. It all depends on how you want to treat the data.

However, the Control \# is representative of an individual sampling event with a unique identifier \# so it is providing the same identifier just in numbers rather than description and will correlate to record id in the other dataset. The Quad represents Deep (2) vs Shallow sets (1); so yes two rows on the same strata/day with quad 1 and 2 will be a full days effort. If you're looking to join the CPUE and overall biological dataset, control1 and record1 only works for the sampling event/environmental data. For the biological data, the record \# represents the control ID and the species ID combined so joining by area and date might be the way to go. The n/a's may stem from the raw data pull representing all effort for the program through the entire time series whereas the CPUE files are limited to years where all sampling efforts and areas occurred simultaneously (e.g. Pamlico sound started in 2001 vs rivers in 2003). In the Cape Fear River system, comparison sets have been done so it might offset the size of the samples. This shows up as REPSIZE= 1.

As of now (05/06/23), the sample IDs for the river systems (only Neuse and Pamlico) have an error. Cara Kowalchyk is planning to send me the updated CPUE data by the end of June. Right now, I can left_join by sample ID for the old CPUE and new biological dataset excluding the Neuse and Pamlico River systems.

### EDA
```{r}
#Load packages, functions, datasets
packages <- c("ggplot2", "tidyverse", "lubridate", "sf", "sp", "dplyr", "rnaturalearth", "readr", "readxl", "spatialEco")

invisible(lapply(packages, library, character.only= TRUE))

standard_theme <- theme_bw() + theme(panel.border = element_rect(fill=NA, colour = "black")) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.text.align= 0, legend.title= element_text(size = 12), legend.text = element_text(size= 10), axis.text=element_text(size=10), axis.title=element_text(size=12))

world <- ne_countries(scale = "medium", returnclass = "sf")

setwd("~/Documents/GitHub/NCBlueCrab_Predators")
p915_CPUEold <- read.csv("Data/P915/Finalized/p915clean.csv")
p915_biolnew1 <- read.csv("Data/P915/Finalized/p915_biolnew1.csv")
p915_biolnew2 <- read.csv("Data/P915/Finalized/p915_biolnew2.csv")
p915_bioln <- rbind(p915_biol1, p915_biol2)

#Presence of NAs
summary(is.na(p915_CPUEold)) #NAs present in Latitude, Longitude, Sedsize, Btmcomp, Winddir, Windspd
summary(is.na(p915_bioln)) #NAs present in Station, Quad, Time, Duration, G1_parm1, G1_parm2, environmental variables, Colnum, biological variables

#Spatial orientation
ggplot(data = world) + geom_sf() + geom_point(data = p915_CPUEold, aes(x = as.numeric(Longitude), y = as.numeric(Latitude), colour = Colnum)) + coord_sf(xlim=c(-78, -75), ylim=c(34,37), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + labs(x= "Longitude", y= "Latitude", colour= "# caught") #CPUE

ggplot(data = world) + geom_sf() + geom_point(data = p915_bioln, aes(x = as.numeric(Longitude), y = as.numeric(Latitude), colour = Colnum)) + coord_sf(xlim=c(-78, -75), ylim=c(34,37), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + labs(x= "Longitude", y= "Latitude", colour= "# caught") #Biological

#Sampling effort 
p915_CPUEold$Date <- as.Date(paste(p915_CPUEold$Month, p915_CPUEold$Day, p915_CPUEold$Year, sep= "-"), "%m-%d-%Y")
p915_CPUEold$Ym_date <- format(p915_CPUEold$Date, "%Y-%m")
ggplot() + geom_histogram(data = p915_CPUEold, stat="count", aes(x=Ym_date)) + standard_theme 
ggplot() + geom_histogram(data = p915_CPUEold, stat="count", aes(x=Ym_date)) + standard_theme + facet_wrap(~Area)

p915_CPUEold %>% group_by(Date, Latitude, Longitude) %>% summarize(abundance= mean(Colnum)) %>% ggplot() + geom_point(aes(x= Date, y= abundance)) + standard_theme
```

EDA revealed sampling consistency throughout the years (except 2020) for all areas except MHC. Sampling in MHC (Back and Core Sounds) began in 2018. After EDA, I have decided there is a need to remove NAs for latitude and longtitude, species, and colnum. One thing that I don't understand is why there are more coordinates for the biological dataset over the CPUE dataset. 
