---
title: "GAM_inference"
format: html
editor: visual
---

```{r}
source("~/Documents/GitHub/NCBlueCrab_Predators/Scripts/Load.SDM.Final.R")
```

#### Red drum

##### Models

```{r}
reddrum_env <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

reddrum_bc <- gam(reddrumP915~ s(log(smallbluecrabP120+1)) + factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

reddrum_forage <- gam(reddrumP915~ s(log(reddrumP915forageP915+1)) + s(log(reddrumP915forageP120+1)) + factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

reddrum_env_bc <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(log(smallbluecrabP120+1)), family= tw(), data=df_CPUE_length_wide_both)

reddrum_env_forage <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(log(reddrumP915forageP915+1)) + s(log(reddrumP915forageP120+1)), family= tw(), data=df_CPUE_length_wide_both)

reddrum_env_bc_forage <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp) + s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(log(reddrumP915forageP120+1)) + s(log(reddrumP915forageP915+1)) + s(log(smallbluecrabP120+1)), family= tw(),  data=df_CPUE_length_wide_both)

AIC(reddrum_env, reddrum_bc, reddrum_forage, reddrum_env_bc, reddrum_env_forage, reddrum_env_bc_forage) %>% arrange(AIC)
```

##### Diagnostics

```{r}
summary(reddrum_env)
summary(reddrum_bc)
summary(reddrum_forage)
summary(reddrum_env_bc)
summary(reddrum_env_forage)
summary(reddrum_env_bc_forage)

anova(reddrum_env) #p-value for year variable across all years
anova(reddrum_bc)
anova(reddrum_forage)
anova(reddrum_env_bc)
anova(reddrum_env_forage)
anova(reddrum_env_bc_forage)

gam.check(reddrum_env)
gam.check(reddrum_bc)
gam.check(reddrum_forage)
gam.check(reddrum_env_bc)
gam.check(reddrum_env_forage)
gam.check(reddrum_env_bc_forage)

vif(reddrum_env)
vif(reddrum_bc)
vif(reddrum_forage)
vif(reddrum_env_bc)
vif(reddrum_env_forage)
vif(reddrum_env_bc_forage)

cor(df_CPUE_length_wide_both %>% dplyr::select(avgdepth,avgssal, avgstemp, avgsdo, NoFishRest, reddrumP915forageP915, reddrumP915forageP120, smallbluecrabP120))

#Partial effect plots
plot(reddrum_env, shade= "true") 
plot(reddrum_bc, shade= "true") 
plot(reddrum_forage, shade= "true") 
plot(reddrum_env_bc, shade= "true") 
plot(reddrum_env_forage, shade= "true") 
plot(reddrum_env_bc_forage, shade= "true") 

#Predictions
df_env <- pred_gam(reddrum_env, c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, Yearfactor, reddrumP915))
df_env_long <- df_env %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, reddrumP915), names_to= "predictor")
graphs(df_env_long, df_env)

ggplot(df_CPUE_length_wide_both) + geom_point() + 

df_bc <- pred_gam(reddrum_bc, c(smallbluecrabP120, Yearfactor, reddrumP915))
df_bc$smallbluecrabP120 <- log(df_bc$smallbluecrabP120+1)
df_bc_long <- df_bc %>% pivot_longer(cols= c(smallbluecrabP120, reddrumP915), names_to= "predictor")
graphs(df_bc_long, df_bc)

df_forage <- pred_gam(reddrum_forage, c(reddrumP915forageP915, reddrumP915forageP120, Yearfactor, reddrumP915))
df_forage$reddrumP915forageP915 <- log(df_forage$reddrumP915forageP915+1)
df_forage$reddrumP915forageP120 <- log(df_forage$reddrumP915forageP120+1)
df_forage_long <- df_forage %>% pivot_longer(cols= c(reddrumP915forageP915, reddrumP915forageP120, reddrumP915), names_to= "predictor")
graphs(df_forage_long, df_forage)

df_env_bc <- pred_gam(reddrum_env_bc, c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, Yearfactor, reddrumP915, smallbluecrabP120))
df_env_bc$smallbluecrabP120 <- log(df_env_bc$smallbluecrabP120+1)
df_env_bc_long <- df_env_bc %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, reddrumP915, smallbluecrabP120), names_to= "predictor")
graphs(df_env_bc_long, df_env_bc)
ggsave("/users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/reddrumbest_partial.jpeg", width= 10, height= 8)
df_env_forage <- pred_gam(reddrum_env_forage, c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, reddrumP915, reddrumP915forageP915, reddrumP915forageP120))
df_env_forage$reddrumP915forageP915 <- log(df_env_forage$reddrumP915forageP915+1)
df_env_forage$reddrumP915forageP120 <- log(df_env_forage$reddrumP915forageP120+1)
df_env_forage_long <- df_env_forage %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, reddrumP915, reddrumP915forageP915, reddrumP915forageP120), names_to= "predictor")
graphs(df_env_forage_long, df_env_forage)
df_env_bc_forage <- pred_gam(reddrum_env_bc_forage, c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, reddrumP915, reddrumP915forageP915, reddrumP915forageP120, smallbluecrabP120))
df_env_bc_forage$smallbluecrabP120 <- log(df_env_bc_forage$smallbluecrabP120+1)
df_env_bc_forage$reddrumP915forageP915 <- log(df_env_bc_forage$reddrumP915forageP915+1)
df_env_bc_forage$reddrumP915forageP120 <- log(df_env_bc_forage$reddrumP915forageP120+1)
df_env_bc_forage_long <- df_env_bc_forage %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, reddrumP915, reddrumP915forageP915, reddrumP915forageP120, smallbluecrabP120), names_to= "predictor")
graphs(df_env_bc_forage_long, df_env_bc_forage)
```

##### year as numeric

```{r}
reddrum_env2 <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+s(Year), family= tw(), data=df_CPUE_length_wide_both)
plot(reddrum_env2, shade= "true") 

blackdrum_env2 <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+s(Year), family= tw(), data=df_CPUE_length_wide_both)
plot(blackdrum_env2, shade= "true") 

blackdrum_env2 <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+s(Year) + s(log(smallbluecrabP120+1)), family= tw(), data=df_CPUE_length_wide_both)
plot(blackdrum_env2, shade= "true") 
```

##### Plots

```{r}
df <- as.data.frame(predict(model), df_CPUE_length_wide_both, type= "response")
df <- df %>% mutate(pred2= exp(prediction))
```

```{r}
df <- df_CPUE_length_wide_both
grid.res <- 22
grid.bin <- data.frame("avgdepth"= mean)

  grid.bin <- data.frame(
  "year"=c(2001:2022),
  "avgdepth"=mean(df$avgdepth), 
  "avgssal"=mean(df$avgssal),
  "avgstemp"=mean(df$avgstemp),
  "avgsdo"=mean(df$julian),
  "NoFishRest"=mean(df$NoFishRest))
  
pred.bin <- predict(reddrum_env, df_CPUE_length_wide_both, type="response", se=T)
niter <- 10000  # number of replicates
pred.bin.boot <- matrix(NA,nrow=grid.res,ncol=niter)
for(i in 1:grid.res){
  pred.bin.boot[i,] <- rnorm(niter, pred.bin$fit[i], pred.bin$se.fit[i])}
pred.mean <- apply(pred.bin.boot,1,mean)
pred.95CI <- apply(pred.bin.boot,1,quantile,probs=c(0.025,0.975)) # to get 95% CIs
plot(grid.bin$year, pred.mean, type="p",mgp=c(2,0.7,0), ylim=c(0,0.31),xlab="",lwd=2,cex.lab=1.4,ylab="",boxwex=0.01,cex.axis=1.1)
points(grid.bin$year,pred.mean, type="p",cex=1.5,pch=19)
points(grid.bin$year,pred.mean, type="l")
lines(grid.bin$year, pred.95CI[1,], lty=2)
lines(grid.bin$year, pred.95CI[2,], lty=2)
```

```{r}
df <- df_CPUE_length_wide_both
pred <- predict(reddrum_env, df_CPUE_length_wide_both, type="response", se=T) 

df$reddrumP915_pred <- pred$fit
df$lower <- pred$fit - 1.96 * pred$se.fit
df$upper <- pred$fit + 1.96 * pred$se.fit

ggplot(df, aes(avgdepth, reddrumP915)) +
  geom_point() +
  geom_ribbon(data = df, alpha = 0.3,
              aes(ymin = lower, ymax = upper, fill = "confidence interval")) +
  geom_line(data = df, aes(color = "GAM")) +
  scale_fill_manual(values = "lightblue", name = NULL) +
  scale_color_manual(values = "darkblue", name = NULL) +
  theme_minimal(base_size = 16)
```

```{r}
df <- gamSim()
m <- gam(y ~ s(x0) + s(x1) + s(x2) + s(x3), data = df, method = "REML")
new_data <- with(df, expand.grid(x2 = seq(min(x2), max(x2), length = 200),
                                 x0 = median(x0),
                                 x1 = median(x1),
                                 x3 = median(x3)))

ilink <- family(m)$linkinv
pred <- predict(m, new_data, type = "link", se.fit = TRUE)
pred <- cbind(pred, new_data)
pred <- transform(pred, lwr_ci = ilink(fit - (2 * se.fit)),
                        upr_ci = ilink(fit + (2 * se.fit)),
                        fitted = ilink(fit))

ggplot(pred, aes(x = x2, y = fitted)) +
  geom_ribbon(aes(ymin = lwr_ci, ymax = upr_ci), alpha = 0.2) +
  geom_line()
```

```{r}
df <- df_CPUE_length_wide_both
new_data <- data.frame("Yearfactor"= c(2001:2019), avgdepth= mean(df$avgdepth), avgssal= mean(df$avgssal), avgstemp= mean(df$avgstemp), avgsdo= mean(df$avgsdo), NoFishRest= mean(df$NoFishRest))

ilink <- family(reddrum_env)$linkinv
pred <- predict(reddrum_env, new_data, type = "link", se.fit = TRUE)
pred <- transform(pred, lwr_ci = ilink(fit - (2 * se.fit)),
                        upr_ci = ilink(fit + (2 * se.fit)),
                        fitted = ilink(fit))

ggplot(aes(x = avgdepth, y = fitted), data= pred) +
  geom_ribbon(aes(ymin = lwr_ci, ymax = upr_ci), data= pred, alpha = 0.2) +
  geom_line()
```

```{r}
df <- df_CPUE_length_wide_both
pred <- predict(reddrum_env, df_CPUE_length_wide_both, type="response", se=T) 
pred <- cbind(pred, df)
pred <- transform(pred, lwr_ci = (fit - (2 * se.fit)),
                        upr_ci = (fit + (2 * se.fit)),
                        fitted = (fit))
ggplot(pred, aes(x = avgdepth, y = fitted)) +
  geom_ribbon(aes(ymin = lwr_ci, ymax = upr_ci), alpha = 0.2) +
  geom_line()
```

#### Southern kingfish

##### Models

```{r}
southernkingfish_env <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_bc <- gam(southernkingfishP915~ s(log(smallbluecrabP120+1)) + factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_forage <- gam(southernkingfishP915~ s(log(southernkingfishP915forageP915+1)) + s(log(southernkingfishP915forageP120+1)) + factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_env_bc <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(log(smallbluecrabP120+1)), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_env_forage <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(log(southernkingfishP915forageP915+1)) + s(log(southernkingfishP915forageP120+1)), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_env_bc_forage <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp) + s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(log(southernkingfishP915forageP120+1)) + s(log(southernkingfishP915forageP915+1)) + s(log(smallbluecrabP120+1)), family= tw(),  data=df_CPUE_length_wide_both)

AIC(southernkingfish_env, southernkingfish_bc, southernkingfish_forage, southernkingfish_env_bc, southernkingfish_env_forage, southernkingfish_env_bc_forage) %>% arrange(AIC)

#Warning: algorithm can't take a step in parameter space that would result in an improvement in the optimizaiton criterion
#technique: increase k until doesn't fail anymore 
```

##### Diagnostics

```{r}
summary(southernkingfish_env)
summary(southernkingfish_bc)
summary(southernkingfish_forage)
summary(southernkingfish_env_bc)
summary(southernkingfish_env_forage)
summary(southernkingfish_env_bc_forage)

anova(southernkingfish_env) #p-value for year variable across all years
anova(southernkingfish_bc)
anova(southernkingfish_forage)
anova(southernkingfish_env_bc)
anova(southernkingfish_env_forage)
anova(southernkingfish_env_bc_forage)

gam.check(southernkingfish_env)
gam.check(southernkingfish_bc)
gam.check(southernkingfish_forage)
gam.check(southernkingfish_env_bc)
gam.check(southernkingfish_env_forage)
gam.check(southernkingfish_env_bc_forage)

vif(southernkingfish_env)
vif(southernkingfish_bc)
vif(southernkingfish_forage)
vif(southernkingfish_env_bc)
vif(southernkingfish_env_forage)
vif(southernkingfish_env_bc_forage)

cor(df_CPUE_length_wide_both %>% dplyr::select(avgdepth,avgssal, avgstemp, avgsdo, NoFishRest, southernkingfishP915forageP915, southernkingfishP915forageP120, smallbluecrabP120))

#Partial effect plots
plot(southernkingfish_env, shade= "true") 
plot(southernkingfish_bc, shade= "true") 
plot(southernkingfish_forage, shade= "true") 
plot(southernkingfish_env_bc, shade= "true") 
plot(southernkingfish_env_forage, shade= "true") 
plot(southernkingfish_env_bc_forage, shade= "true") 

#Predictions
df_env <- pred_gam(southernkingfish_env, c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, Yearfactor, southernkingfishP915))
df_env_long <- df_env %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, southernkingfishP915), names_to= "predictor")
graphs(df_env_long, df_env)

df_bc <- pred_gam(southernkingfish_bc, c(smallbluecrabP120, Yearfactor, southernkingfishP915))
df_bc$smallbluecrabP120 <- log(df_bc$smallbluecrabP120+1)
df_bc_long <- df_bc %>% pivot_longer(cols= c(smallbluecrabP120, southernkingfishP915), names_to= "predictor")
graphs_sk(df_bc_long, df_bc)

df_forage <- pred_gam(southernkingfish_forage, c(southernkingfishP915forageP915, southernkingfishP915forageP120, Yearfactor, southernkingfishP915))
df_forage$southernkingfishP915forageP915 <- log(df_forage$southernkingfishP915forageP915+1)
df_forage$southernkingfishP915forageP120 <- log(df_forage$southernkingfishP915forageP120+1)
df_forage_long <- df_forage %>% pivot_longer(cols= c(southernkingfishP915forageP915, southernkingfishP915forageP120, southernkingfishP915), names_to= "predictor")
graphs(df_forage_long, df_forage)

df_env_bc <- pred_gam(southernkingfish_env_bc, c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, Yearfactor, southernkingfishP915, smallbluecrabP120))
df_env_bc$smallbluecrabP120 <- log(df_env_bc$smallbluecrabP120+1)
df_env_bc_long <- df_env_bc %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, southernkingfishP915, smallbluecrabP120), names_to= "predictor")
graphs(df_env_bc_long, df_env_bc)

df_env_forage <- pred_gam(southernkingfish_env_forage, c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, southernkingfishP915, southernkingfishP915forageP915, southernkingfishP915forageP120))
df_env_forage$southernkingfishP915forageP915 <- log(df_env_forage$southernkingfishP915forageP915+1)
df_env_forage$southernkingfishP915forageP120 <- log(df_env_forage$southernkingfishP915forageP120+1)
df_env_forage_long <- df_env_forage %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, southernkingfishP915, southernkingfishP915forageP915, southernkingfishP915forageP120), names_to= "predictor")
graphs(df_env_forage_long, df_env_forage)

df_env_bc_forage <- pred_gam(southernkingfish_env_bc_forage, c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, southernkingfishP915, southernkingfishP915forageP915, southernkingfishP915forageP120, smallbluecrabP120))
df_env_bc_forage$smallbluecrabP120 <- log(df_env_bc_forage$smallbluecrabP120+1)
df_env_bc_forage$southernkingfishP915forageP915 <- log(df_env_bc_forage$southernkingfishP915forageP915+1)
df_env_bc_forage$southernkingfishP915forageP120 <- log(df_env_bc_forage$southernkingfishP915forageP120+1)
df_env_bc_forage_long <- df_env_bc_forage %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, southernkingfishP915, southernkingfishP915forageP915, southernkingfishP915forageP120, smallbluecrabP120), names_to= "predictor")
graphs(df_env_bc_forage_long, df_env_bc_forage)
```

#### Black drum

##### Models

```{r}
blackdrum_env <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

blackdrum_bc <- gam(blackdrumP915~ s(log(smallbluecrabP120+1)) + factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

blackdrum_forage <- gam(blackdrumP915~ s(log(blackdrumP915forageP120+1)) + factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

blackdrum_env_bc <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(log(smallbluecrabP120+1)), family= tw(), data=df_CPUE_length_wide_both)

blackdrum_env_forage <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(log(blackdrumP915forageP120+1)), family= tw(), data=df_CPUE_length_wide_both)

blackdrum_env_bc_forage <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp) + s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(log(blackdrumP915forageP120+1)) + s(log(smallbluecrabP120+1)), family= tw(),  data=df_CPUE_length_wide_both)

AIC(blackdrum_env, blackdrum_bc, blackdrum_forage, blackdrum_env_bc, blackdrum_env_forage, blackdrum_env_bc_forage) %>% arrange(AIC)
```

##### Diagnostics

```{r}
summary(blackdrum_env)
summary(blackdrum_bc)
summary(blackdrum_forage)
summary(blackdrum_env_bc)
summary(blackdrum_env_forage)
summary(blackdrum_env_bc_forage)

anova(blackdrum_env) #p-value for year variable across all years
anova(blackdrum_bc)
anova(blackdrum_forage)
anova(blackdrum_env_bc)
anova(blackdrum_env_forage)
anova(blackdrum_env_bc_forage)

gam.check(blackdrum_env)
gam.check(blackdrum_bc)
gam.check(blackdrum_forage)
gam.check(blackdrum_env_bc)
gam.check(blackdrum_env_forage)
gam.check(blackdrum_env_bc_forage)

vif(blackdrum_env)
vif(blackdrum_bc)
vif(blackdrum_forage)
vif(blackdrum_env_bc)
vif(blackdrum_env_forage)
vif(blackdrum_env_bc_forage)

cor(df_CPUE_length_wide_both %>% dplyr::select(avgdepth,avgssal, avgstemp, avgsdo, NoFishRest, blackdrumP915forageP120, smallbluecrabP120))

#Partial effect plots
plot(blackdrum_env, shade= "true") 
plot(blackdrum_bc, shade= "true") 
plot(blackdrum_forage, shade= "true") 
plot(blackdrum_env_bc, shade= "true") 
plot(blackdrum_env_forage, shade= "true") 
plot(blackdrum_env_bc_forage, shade= "true") 

#Predictions
df_env <- pred_gam(blackdrum_env, c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, Yearfactor, blackdrumP915))
df_env_long <- df_env %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, blackdrumP915), names_to= "predictor")
graphs(df_env_long, df_env)

df_bc <- pred_gam(blackdrum_bc, c(smallbluecrabP120, Yearfactor, blackdrumP915))
df_bc$smallbluecrabP120 <- log(df_bc$smallbluecrabP120+1)
df_bc_long <- df_bc %>% pivot_longer(cols= c(smallbluecrabP120, blackdrumP915), names_to= "predictor")
graphs(df_bc_long, df_bc)

df_forage <- pred_gam(blackdrum_forage, c(blackdrumP915forageP120, Yearfactor, blackdrumP915))
df_forage$blackdrumP915forageP120 <- log(df_forage$blackdrumP915forageP120+1)
df_forage_long <- df_forage %>% pivot_longer(cols= c(blackdrumP915forageP120, blackdrumP915), names_to= "predictor")
graphs(df_forage_long, df_forage)

df_env_bc <- pred_gam(blackdrum_env_bc, c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, Yearfactor, blackdrumP915, smallbluecrabP120))
df_env_bc$smallbluecrabP120 <- log(df_env_bc$smallbluecrabP120+1)
df_env_bc_long <- df_env_bc %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, blackdrumP915, smallbluecrabP120), names_to= "predictor")
graphs(df_env_bc_long, df_env_bc)

df_env_forage <- pred_gam(blackdrum_env_forage, c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, blackdrumP915, blackdrumP915forageP120))
df_env_forage$blackdrumP915forageP120 <- log(df_env_forage$blackdrumP915forageP120+1)
df_env_forage_long <- df_env_forage %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, blackdrumP915, blackdrumP915forageP120), names_to= "predictor")
graphs(df_env_forage_long, df_env_forage)
ggsave("/users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/blackdrumbest_partial.jpeg", width= 10, height= 8)
df_env_bc_forage <- pred_gam(blackdrum_env_bc_forage, c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, blackdrumP915, blackdrumP915forageP120, smallbluecrabP120))
df_env_bc_forage$smallbluecrabP120 <- log(df_env_bc_forage$smallbluecrabP120+1)
df_env_bc_forage$blackdrumP915forageP120 <- log(df_env_bc_forage$blackdrumP915forageP120+1)
df_env_bc_forage_long <- df_env_bc_forage %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, blackdrumP915, blackdrumP915forageP120, smallbluecrabP120), names_to= "predictor")
graphs(df_env_bc_forage_long, df_env_bc_forage)

df_env_bc_forage_long %>% ggplot(aes(x= value, y= pred2)) + geom_point() + facet_wrap(~predictor, scales= "free") + geom_smooth(method= "gam", formula= blackdrumP915 ~ avgsdo+avgdepth+avgssal+avgstemp+blackdrumP915forageP120+NoFishRest+smallbluecrabP120)

graphs <- function(df, df2){
  plot1 <- df %>% ggplot(aes(x= value, y= pred2)) + geom_point() + geom_smooth(loess=TRUE) + facet_wrap(~predictor, scales= "free") + standard_theme + ylab("Predicted red drum CPUE") + geom_smooth(method= "gam", formula= reddrumP915 ~ avgsdo)
  # plot2 <-df2 %>% ggplot(aes(x= reddrumP915, y= pred2)) + geom_point() + geom_smooth(loess=TRUE) + standard_theme
  print(plot1)
}
```

#### Year is important:

```{r}
df <- df_CPUE_length_wide_both
sample_size_both = floor(0.8*nrow(df))
picked_both = sample(seq_len(nrow(df)),size = sample_size_both) 
df_test = df[-picked_both,]
df_train = df[picked_both,]

reddrum_env <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor), family= tw(), data=df_train)

df2 <- as.data.frame(predict(reddrum_env), newdata= df_test, type= "response")
colnames(df2) <- "prediction"
df2 <- df2 %>% mutate(pred2= exp(prediction))
r2_general(df2$pred2, df_train$reddrumP915)
```

#### Explore weird residuals: still just bad at predicting

```{r}
df <- df_CPUE_length_wide_both
sample_size_both = floor(0.8*nrow(df_CPUE_length_wide_both))
picked = sample(seq_len(nrow(df)),size = sample_size_both) 
df2 <- df %>% mutate(logsmallbluecrabP120= log(smallbluecrabP120+1))

test = df2[-picked,]
train = df2[picked,]

#Load cross-validation functions 
library(gtools)

pastePerm<- function(row, names){
  keep<- which(row==1)
  if(length(keep)==0){
    return('1')
  }else{
    return(paste(names[keep],collapse='+'))
  }
}
my_sqrt <- function(var1){
  sqrt(var1) #take square root of variable 
} #construct model formulas 

dredgeform<- function(pred, covars, alwaysIn='Yearfactor'){ #always in is set to empty string
  p<- length(covars) #number of independent variables
  perm.tab<- permutations(2, p, v=c(0,1), repeats.allowed=T) #for different combinations of predictor variables
  myforms<- NULL #store formulas 
  for(j in 1:nrow(perm.tab)){
    myforms[j]<- pastePerm(perm.tab[j,], covars) #function above
  }
  myforms<- paste0(pred, '~',myforms) #predicted variable and formula
  return(myforms)
}


allformulas_reddrum <- dredgeform(pred = "reddrumP915", covars = c("s(avgdepth)", "s(avgssal)", "s(avgstemp)", "s(avgsdo)", "s(NoFishRest)", "s(logsmallbluecrabP120)"))

compare_var_tw_reddrum <- as.data.frame(matrix(ncol = 2, nrow = 0))
colnames(compare_var_tw_reddrum) <- c("formula", "AIC")
for (i in 1:length(allformulas_reddrum)) {
model_tw_reddrum <- gam(as.formula(allformulas_reddrum[i]), data=train, family= tw(link= "log"))
compare_var_tw_reddrum[i, 1] <- allformulas_reddrum[i]
compare_var_tw_reddrum[i, 2] <- AIC(model_tw_reddrum)
print(i)
}

compare_var_tw_reddrum %>% arrange(AIC) %>% .[1,1]

real_gam <- gam(reddrumP915~s(avgstemp)+s(logsmallbluecrabP120), data=train, family= tw(link= "log"))


df2 <- as.data.frame(predict(real_gam), newdata= test, type= "response")
colnames(df2) <- "prediction"
df2 <- df2 %>% mutate(pred2= exp(prediction))
r2_general(df2$pred2, train$reddrumP915)


gam.check(real_gam)
```
