---
title: "GAM_CV"
format: html
editor: visual
---

```{r}
source("~/Documents/GitHub/NCBlueCrab_Predators/Scripts/Load.SDM.Final.R")
```

-Parsnip details: https://www.tidymodels.org/learn/develop/models/

```{r}
#Define model 
gam_mod <- gen_additive_mod() %>%
set_engine(engine = 'mgcv', family= tw(link= "log")) %>% set_mode('regression')
```

```{r}
folds <- vfold_cv(df_CPUE_length_wide_both, v= 5, strata= reddrumP915, repeats= 100) #5 fold cross-validation repeated 100 times on the dataset
#strata: create a stratified CV object, too little data to stratify by Year 
```

#### Red drum

```{r}
#Environment
reddrum_env_wf <- workflow() %>% add_variables(outcomes= reddrumP915, predictors= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest)) %>% add_model(gam_mod, formula= reddrumP915 ~ s(avgdepth) + s(avgssal) + s(avgstemp) + s(avgsdo) + s(NoFishRest)) %>% fit(data= df_CPUE_length_wide_both) 

reddrum_env_cv <- reddrum_env_wf %>% fit_resamples(folds)
reddrum_env_cv2 <- collect_metrics(reddrum_env_cv)
combined_df <- do.call(rbind, reddrum_env_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/reddrum_env_cv.csv")
write.csv(reddrum_env_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/reddrum_env_cv2.csv")

#BC
reddrum_bc_wf <- workflow() %>% add_variables(outcomes= reddrumP915, predictors= c(logsmallbluecrabP120)) %>% add_model(gam_mod, formula= reddrumP915 ~ s(logsmallbluecrabP120)) %>% fit(data= df_CPUE_length_wide_both) 
reddrum_bc_cv <- reddrum_bc_wf %>% fit_resamples(folds)
reddrum_bc_cv2 <- collect_metrics(reddrum_bc_cv)
combined_df <- do.call(rbind, reddrum_bc_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/reddrum_bc_cv.csv")
write.csv(reddrum_bc_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/reddrum_bc_cv2.csv")

#Forage
reddrum_forage_wf <- workflow() %>% add_variables(outcomes= reddrumP915, predictors= c(logreddrumP915forageP915, logreddrumP915forageP120)) %>% add_model(gam_mod, formula= reddrumP915 ~ s(logreddrumP915forageP915) + s(logreddrumP915forageP120)) %>% fit(data= df_CPUE_length_wide_both) 

reddrum_forage_cv <- reddrum_forage_wf %>% fit_resamples(folds)
reddrum_forage_cv2 <- collect_metrics(reddrum_forage_cv)
combined_df <- do.call(rbind, reddrum_forage_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/reddrum_forage_cv.csv")
write.csv(reddrum_forage_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/reddrum_forage_cv2.csv")

#Environment + bc
reddrum_env_bc_wf <- workflow() %>% add_variables(outcomes= reddrumP915, predictors= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, logsmallbluecrabP120)) %>% add_model(gam_mod, formula= reddrumP915 ~ s(avgdepth) + s(avgssal) + s(avgstemp) + s(avgsdo) + s(NoFishRest) + s(logsmallbluecrabP120)) %>% fit(data= df_CPUE_length_wide_both) 

reddrum_env_bc_cv <- reddrum_env_bc_wf %>% fit_resamples(folds)
reddrum_env_bc_cv2 <- collect_metrics(reddrum_env_bc_cv)
combined_df <- do.call(rbind, reddrum_env_bc_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/reddrum_env_bc_cv.csv")
write.csv(reddrum_env_bc_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/reddrum_env_bc_cv2.csv")

reddrum_env_bc_cv_unsumm <- collect_metrics(reddrum_env_bc_cv, summarize= FALSE)
write.csv(reddrum_env_bc_cv_unsumm, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/reddrum_env_bc_cv_unsumm.csv")

#Environment + forage
reddrum_env_forage_wf <- workflow() %>% add_variables(outcomes= reddrumP915, predictors= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, logreddrumP915forageP915, logreddrumP915forageP120)) %>% add_model(gam_mod, formula= reddrumP915 ~ s(avgdepth) + s(avgssal) + s(avgstemp) + s(avgsdo) + s(NoFishRest) + s(logreddrumP915forageP915) + s(logreddrumP915forageP120)) %>% fit(data= df_CPUE_length_wide_both) 

reddrum_env_forage_cv <- reddrum_env_forage_wf %>% fit_resamples(folds)
reddrum_env_forage_cv2 <- collect_metrics(reddrum_env_forage_cv)
combined_df <- do.call(rbind, reddrum_env_forage_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/reddrum_env_forage_cv.csv")
write.csv(reddrum_env_forage_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/reddrum_env_forage_cv2.csv")

reddrum_env_forage_cv_unsumm <- collect_metrics(reddrum_env_forage_cv, summarize= FALSE)
write.csv(reddrum_env_bc_cv_unsumm, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/reddrum_env_forage_cv_unsumm.csv")

#Environment + bc + forage 
reddrum_env_bc_forage_wf <- workflow() %>% add_variables(outcomes= reddrumP915, predictors= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, logreddrumP915forageP915, logreddrumP915forageP120, logsmallbluecrabP120)) %>% add_model(gam_mod, formula= reddrumP915 ~ s(avgdepth) + s(avgssal) + s(avgstemp) + s(avgsdo) + s(NoFishRest) + s(logreddrumP915forageP915) + s(logreddrumP915forageP120) + s(logsmallbluecrabP120)) %>% fit(data= df_CPUE_length_wide_both) 

reddrum_env_bc_forage_cv <- reddrum_env_bc_forage_wf %>% fit_resamples(folds)
reddrum_env_bc_forage_cv2 <- collect_metrics(reddrum_env_bc_forage_cv)
combined_df <- do.call(rbind, reddrum_env_bc_forage_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/reddrum_env_bc_forage_cv.csv")
write.csv(reddrum_env_bc_forage_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/reddrum_env_bc_forage_cv2.csv")

reddrum_env_bc_forage_cv_unsumm <- collect_metrics(reddrum_env_bc_forage_cv, summarize= FALSE)
write.csv(reddrum_env_bc_forage_cv_unsumm, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/reddrum_env_bc_forage_cv_unsumm.csv")
```

#### Southern kingfish

```{r}
folds <- vfold_cv(df_CPUE_length_wide_both, v= 5, strata= southernkingfishP915, repeats= 100)
```

```{r}
#Environment
southernkingfish_env_wf <- workflow() %>% add_variables(outcomes= southernkingfishP915, predictors= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest)) %>% add_model(gam_mod, formula= southernkingfishP915 ~ s(avgdepth) + s(avgssal) + s(avgstemp) + s(avgsdo) + s(NoFishRest)) %>% fit(data= df_CPUE_length_wide_both) 
southernkingfish_env_cv <- southernkingfish_env_wf %>% fit_resamples(folds)
southernkingfish_env_cv2 <- collect_metrics(southernkingfish_env_cv)
combined_df <- do.call(rbind, southernkingfish_env_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/southernkingfish_env_cv.csv")
write.csv(southernkingfish_env_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/southernkingfish_env_cv2.csv")

#BC
southernkingfish_bc_wf <- workflow() %>% add_variables(outcomes= southernkingfishP915, predictors= c(logsmallbluecrabP120)) %>% add_model(gam_mod, formula= southernkingfishP915 ~ s(logsmallbluecrabP120)) %>% fit(data= df_CPUE_length_wide_both) 

southernkingfish_bc_cv <- southernkingfish_bc_wf %>% fit_resamples(folds)
southernkingfish_bc_cv2 <- collect_metrics(southernkingfish_bc_cv)
combined_df <- do.call(rbind, southernkingfish_bc_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/southernkingfish_bc_cv.csv")
write.csv(southernkingfish_bc_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/southernkingfish_bc_cv2.csv")

#Forage
southernkingfish_forage_wf <- workflow() %>% add_variables(outcomes= southernkingfishP915, predictors= c(logsouthernkingfishP915forageP915, logsouthernkingfishP915forageP120)) %>% add_model(gam_mod, formula= southernkingfishP915 ~ s(logsouthernkingfishP915forageP915) + s(logsouthernkingfishP915forageP120)) %>% fit(data= df_CPUE_length_wide_both) 

southernkingfish_forage_cv <- southernkingfish_forage_wf %>% fit_resamples(folds)
southernkingfish_forage_cv2 <- collect_metrics(southernkingfish_forage_cv)
combined_df <- do.call(rbind, southernkingfish_forage_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/southernkingfish_forage_cv.csv")
write.csv(southernkingfish_forage_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/southernkingfish_forage_cv2.csv")

#Environment + bc
southernkingfish_env_bc_wf <- workflow() %>% add_variables(outcomes= southernkingfishP915, predictors= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, logsmallbluecrabP120)) %>% add_model(gam_mod, formula= southernkingfishP915 ~ s(avgdepth) + s(avgssal) + s(avgstemp) + s(avgsdo) + s(NoFishRest) + s(logsmallbluecrabP120)) %>% fit(data= df_CPUE_length_wide_both) 

southernkingfish_env_bc_cv <- southernkingfish_env_bc_wf %>% fit_resamples(folds)
southernkingfish_env_bc_cv2 <- collect_metrics(southernkingfish_env_bc_cv)
combined_df <- do.call(rbind, southernkingfish_env_bc_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/southernkingfish_env_bc_cv.csv")
write.csv(southernkingfish_env_bc_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/southernkingfish_env_bc_cv2.csv")

southernkingfish_env_bc_cv_unsumm <- collect_metrics(southernkingfish_env_bc_cv, summarize= FALSE)
write.csv(southernkingfish_env_bc_cv_unsumm, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/southernkingfish_env_bc_cv_unsumm.csv")

#Environment + forage
southernkingfish_env_forage_wf <- workflow() %>% add_variables(outcomes= southernkingfishP915, predictors= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, logsouthernkingfishP915forageP915, logsouthernkingfishP915forageP120)) %>% add_model(gam_mod, formula= southernkingfishP915 ~ s(avgdepth) + s(avgssal) + s(avgstemp) + s(avgsdo) + s(NoFishRest) + s(logsouthernkingfishP915forageP915) + s(logsouthernkingfishP915forageP120)) %>% fit(data= df_CPUE_length_wide_both) 

southernkingfish_env_forage_cv <- southernkingfish_env_forage_wf %>% fit_resamples(folds)
beep(sound=8)
southernkingfish_env_forage_cv2 <- collect_metrics(southernkingfish_env_forage_cv)
combined_df <- do.call(rbind, southernkingfish_env_forage_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/southernkingfish_env_forage_cv.csv")
write.csv(southernkingfish_env_forage_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/southernkingfish_env_forage_cv2.csv")

southernkingfish_env_forage_cv_unsumm <- collect_metrics(southernkingfish_env_forage_cv, summarize= FALSE)
write.csv(southernkingfish_env_forage_cv_unsumm, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/southernkingfish_env_forage_cv_unsumm.csv")

#Environment + bc + forage 
southernkingfish_env_bc_forage_wf <- workflow() %>% add_variables(outcomes= southernkingfishP915, predictors= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, logsouthernkingfishP915forageP915, logsouthernkingfishP915forageP120, logsmallbluecrabP120)) %>% add_model(gam_mod, formula= southernkingfishP915 ~ s(avgdepth) + s(avgssal) + s(avgstemp) + s(avgsdo) + s(NoFishRest) + s(logsouthernkingfishP915forageP915) + s(logsouthernkingfishP915forageP120) + s(logsmallbluecrabP120)) %>% fit(data= df_CPUE_length_wide_both) 

southernkingfish_env_bc_forage_cv <- southernkingfish_env_bc_forage_wf %>% fit_resamples(folds)
beep(sound=8)
southernkingfish_env_bc_forage_cv2 <- collect_metrics(southernkingfish_env_bc_forage_cv)
combined_df <- do.call(rbind, southernkingfish_env_bc_forage_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/southernkingfish_env_bc_forage_cv.csv")
write.csv(southernkingfish_env_bc_forage_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/southernkingfish_env_bc_forage_cv2.csv")

southernkingfish_env_bc_forage_cv_unsumm <- collect_metrics(southernkingfish_env_bc_forage_cv, summarize= FALSE)
write.csv(southernkingfish_env_bc_forage_cv_unsumm, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/southernkingfish_env_bc_forage_cv_unsumm.csv")
```

#### Black drum

```{r}
folds <- vfold_cv(df_CPUE_length_wide_both, v= 5, strata= blackdrumP915, repeats= 100)
```

```{r}
#Environment
blackdrum_env_wf <- workflow() %>% add_variables(outcomes= blackdrumP915, predictors= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest)) %>% add_model(gam_mod, formula= blackdrumP915 ~ s(avgdepth) + s(avgssal) + s(avgstemp) + s(avgsdo) + s(NoFishRest)) %>% fit(data= df_CPUE_length_wide_both) 
blackdrum_env_cv <- blackdrum_env_wf %>% fit_resamples(folds)
blackdrum_env_cv2 <- collect_metrics(blackdrum_env_cv)
combined_df <- do.call(rbind, blackdrum_env_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/blackdrum_env_cv.csv")
write.csv(blackdrum_env_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/blackdrum_env_cv2.csv")

#BC
blackdrum_bc_wf <- workflow() %>% add_variables(outcomes= blackdrumP915, predictors= c(logsmallbluecrabP120)) %>% add_model(gam_mod, formula= blackdrumP915 ~ s(logsmallbluecrabP120)) %>% fit(data= df_CPUE_length_wide_both) 

blackdrum_bc_cv <- blackdrum_bc_wf %>% fit_resamples(folds)
blackdrum_bc_cv2 <- collect_metrics(blackdrum_bc_cv)
combined_df <- do.call(rbind, blackdrum_bc_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/blackdrum_bc_cv.csv")
write.csv(blackdrum_bc_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/blackdrum_bc_cv2.csv")

#Forage
blackdrum_forage_wf <- workflow() %>% add_variables(outcomes= blackdrumP915, predictors= c(logblackdrumP915forageP120)) %>% add_model(gam_mod, formula= blackdrumP915 ~ s(logblackdrumP915forageP120)) %>% fit(data= df_CPUE_length_wide_both) 

blackdrum_forage_cv <- blackdrum_forage_wf %>% fit_resamples(folds)
blackdrum_forage_cv2 <- collect_metrics(blackdrum_forage_cv)
combined_df <- do.call(rbind, blackdrum_forage_cv)
write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/blackdrum_forage_cv.csv")
write.csv(blackdrum_forage_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/blackdrum_forage_cv2.csv")

#Environment + bc
blackdrum_env_bc_wf <- workflow() %>% add_variables(outcomes= blackdrumP915, predictors= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, logsmallbluecrabP120)) %>% add_model(gam_mod, formula= blackdrumP915 ~ s(avgdepth) + s(avgssal) + s(avgstemp) + s(avgsdo) + s(NoFishRest) + s(logsmallbluecrabP120)) %>% fit(data= df_CPUE_length_wide_both) 

blackdrum_env_bc_cv <- blackdrum_env_bc_wf %>% fit_resamples(folds)
# blackdrum_env_bc_cv2 <- collect_metrics(blackdrum_env_bc_cv)
# combined_df <- do.call(rbind, blackdrum_env_bc_cv)
# write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/blackdrum_env_bc_cv.csv")
# write.csv(blackdrum_env_bc_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/blackdrum_env_bc_cv2.csv")

blackdrum_env_bc_cv_unsumm <- collect_metrics(blackdrum_env_bc_cv, summarize= FALSE)
write.csv(blackdrum_env_bc_cv_unsumm, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/blackdrum_env_bc_cv_unsumm.csv")

#Environment + forage
blackdrum_env_forage_wf <- workflow() %>% add_variables(outcomes= blackdrumP915, predictors= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, logblackdrumP915forageP120)) %>% add_model(gam_mod, formula= blackdrumP915 ~ s(avgdepth) + s(avgssal) + s(avgstemp) + s(avgsdo) + s(NoFishRest) + s(logblackdrumP915forageP120)) %>% fit(data= df_CPUE_length_wide_both) 

blackdrum_env_forage_cv <- blackdrum_env_forage_wf %>% fit_resamples(folds)
# blackdrum_env_forage_cv2 <- collect_metrics(blackdrum_env_forage_cv)
# combined_df <- do.call(rbind, blackdrum_env_forage_cv)
# write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/blackdrum_env_forage_cv.csv")
# write.csv(blackdrum_env_forage_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/blackdrum_env_forage_cv2.csv")

blackdrum_env_forage_cv_unsumm <- collect_metrics(blackdrum_env_forage_cv, summarize= FALSE)
write.csv(blackdrum_env_forage_cv_unsumm, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/blackdrum_env_forage_cv_unsumm.csv")

#Environment + bc + forage 
blackdrum_env_bc_forage_wf <- workflow() %>% add_variables(outcomes= blackdrumP915, predictors= c(avgdepth, avgssal, avgstemp, avgsdo, NoFishRest, logblackdrumP915forageP120, logsmallbluecrabP120)) %>% add_model(gam_mod, formula= blackdrumP915 ~ s(avgdepth) + s(avgssal) + s(avgstemp) + s(avgsdo) + s(NoFishRest) + s(logblackdrumP915forageP120) + s(logsmallbluecrabP120)) %>% fit(data= df_CPUE_length_wide_both) 

blackdrum_env_bc_forage_cv <- blackdrum_env_bc_forage_wf %>% fit_resamples(folds)
# blackdrum_env_bc_forage_cv2 <- collect_metrics(blackdrum_env_bc_forage_cv)
# combined_df <- do.call(rbind, blackdrum_env_bc_forage_cv)
# write.csv(combined_df, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/blackdrum_env_bc_forage_cv.csv")
# write.csv(blackdrum_env_bc_forage_cv2, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/blackdrum_env_bc_forage_cv2.csv")

blackdrum_env_bc_forage_cv_unsumm <- collect_metrics(blackdrum_env_bc_forage_cv, summarize= FALSE)
write.csv(blackdrum_env_bc_forage_cv_unsumm, "/Users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/CV/Summary/blackdrum_env_bc_forage_cv_unsumm.csv")
beep(sound=8)
```
