---
title: "GAMs_final_real"
format: html
editor: visual
---

```{r}
source("~/Documents/GitHub/NCBlueCrab_Predators/Scripts/Load.SDM.Final.R")
```

-https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/tweedie_link_power.html 
-Used tweedie with log link: https://www.ccamlr.org/ru/system/files/science_journal_papers/04candy.pdf

#### Red drum

##### Models: all model types 

```{r}
#Red drum 
reddrum_env <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor), family= tw(link= "log"), data=df_CPUE_length_wide_both)
summary(reddrum_env)

reddrum_env_bc <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(smallbluecrabP120), family= tw(link= "log",), data=df_CPUE_length_wide_both)
summary(reddrum_env_bc)

reddrum_env_forage <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(reddrumP915forageP915) + s(reddrumP915forageP120), family= tw(link= "log"), data=df_CPUE_length_wide_both)
summary(reddrum_env_forage)

reddrum_env_bc_forage <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp) + s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(reddrumP915forageP120) + s(reddrumP915forageP915) + s(smallbluecrabP120), family= tw(link= "log"),  data=df_CPUE_length_wide_both)
summary(reddrum_env_bc_forage)

AIC(reddrum_env, reddrum_env_bc, reddrum_env_forage, reddrum_env_bc_forage) %>% arrange(AIC)

#tw(): p is estimated during fitting, will report this 
```

##### Diagnostics

-Interpret partial effect plots: https://towardsdatascience.com/producing-insights-with-generalized-additive-models-gams-cf2b68b1b847

```{r}
gam.check(reddrum_env)
gam.check(reddrum_env_bc)
gam.check(reddrum_env_forage)
gam.check(reddrum_env_bc_forage)

vif(reddrum_env)
vif(reddrum_env_bc)
vif(reddrum_env_forage)
vif(reddrum_env_bc_forage)

cor(df_CPUE_length_wide_both %>% dplyr::select(avgdepth,avgssal, avgstemp, avgsdo, NoFishRest, reddrumP915forageP915, reddrumP915forageP120))

#Partial effect plots
plot(reddrum_env, shade= "true") 
plot(reddrum_env_bc, shade= "true") 
plot(reddrum_env_forage, shade= "true") 
plot(reddrum_env_bc_forage, shade= "true") 

#Predictions 

#Environment only 
reddrum_env_pred <- as.data.frame(predict(reddrum_env), df_CPUE_length_wide_both, type= "response")
colnames(reddrum_env_pred) <- "prediction"
reddrum_env_pred <- reddrum_env_pred %>% mutate(pred2= exp(prediction)) #get predictions on correct scale 
df_env <- df_CPUE_length_wide_both %>% dplyr::select(avgdepth, avgssal, avgstemp, avgsdo, SAVkm, NoFishRest, Yearfactor, reddrumP915)
df_env <- bind_cols(df_env, reddrum_env_pred)
df_env_long <- df_env %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, SAVkm, NoFishRest, reddrumP915), names_to= "predictor")
df_env_long %>% ggplot(aes(x= value, y= pred2)) + geom_point() + geom_smooth(loess=TRUE) + facet_wrap(~predictor, scales= "free") + standard_theme + ylab("Predicted red drum CPUE")
df_env %>% ggplot(aes(x= reddrumP915, y= pred2)) + geom_point() + geom_smooth(loess=TRUE) + standard_theme

#Environment + BC 
reddrum_env_bc_pred <- as.data.frame(predict(reddrum_env_bc), df_CPUE_length_wide_both, type= "response")
colnames(reddrum_env_bc_pred) <- "prediction"
reddrum_env_bc_pred <- reddrum_env_bc_pred %>% mutate(pred2= exp(prediction)) #get predictions on correct scale 
df_env_bc <- df_CPUE_length_wide_both %>% dplyr::select(avgdepth, avgssal, avgstemp, avgsdo, SAVkm, NoFishRest, Yearfactor, reddrumP915, smallbluecrabP120)
df_env_bc <- bind_cols(df_env_bc, reddrum_env_bc_pred)
df_env_bc_long <- df_env_bc %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, SAVkm, NoFishRest, reddrumP915, smallbluecrabP120), names_to= "predictor")
df_env_bc_long %>% ggplot(aes(x= value, y= pred2)) + geom_point() + geom_smooth(loess=TRUE) + facet_wrap(~predictor, scales= "free") + standard_theme + ylab("Predicted red drum CPUE")
df_env_bc %>% ggplot(aes(x= reddrumP915, y= pred2)) + geom_point() + geom_smooth(loess=TRUE) + standard_theme

#Environment + total forage
reddrum_env_forage_pred <- as.data.frame(predict(reddrum_env_forage), df_CPUE_length_wide_both, type= "response")
colnames(reddrum_env_forage_pred) <- "prediction"
reddrum_env_forage_pred <- reddrum_env_forage_pred %>% mutate(pred2= exp(prediction)) #get predictions on correct scale 
df_env_forage <- df_CPUE_length_wide_both %>% dplyr::select(avgdepth, avgssal, avgstemp, avgsdo, SAVkm, NoFishRest, Yearfactor, reddrumP915, reddrumP915forageP915, reddrumP915forageP120)
df_env_forage <- bind_cols(df_env_forage, reddrum_env_forage_pred)
df_env_forage_long <- df_env_forage %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, SAVkm, NoFishRest, reddrumP915, reddrumP915forageP915, reddrumP915forageP120), names_to= "predictor")
df_env_forage_long %>% ggplot(aes(x= value, y= pred2)) + geom_point() + geom_smooth(loess=TRUE) + facet_wrap(~predictor, scales= "free") + standard_theme + ylab("Predicted red drum CPUE")
df_env_forage %>% ggplot(aes(x= reddrumP915, y= pred2)) + geom_point() + geom_smooth(loess=TRUE) + standard_theme

#Environment + bc + total forage
reddrum_env_bc_forage_pred <- as.data.frame(predict(reddrum_env_bc_forage), df_CPUE_length_wide_both, type= "response")
colnames(reddrum_env_bc_forage_pred) <- "prediction"
reddrum_env_bc_forage_pred <- reddrum_env_bc_forage_pred %>% mutate(pred2= exp(prediction)) #get predictions on correct scale 
df_env_bc_forage <- df_CPUE_length_wide_both %>% dplyr::select(avgdepth, avgssal, avgstemp, avgsdo, SAVkm, NoFishRest, Yearfactor, reddrumP915, smallbluecrabP120, reddrumP915forageP915, reddrumP915forageP120)
df_env_bc_forage <- bind_cols(df_env_bc_forage, reddrum_env_bc_forage_pred)
df_env_bc_forage_long <- df_env_bc_forage %>% pivot_longer(cols= c(avgdepth, avgssal, avgstemp, avgsdo, SAVkm, NoFishRest, reddrumP915, smallbluecrabP120, reddrumP915forageP915, reddrumP915forageP120), names_to= "predictor")
df_env_bc_forage_long %>% ggplot(aes(x= value, y= pred2)) + geom_point() + geom_smooth(loess=TRUE) + facet_wrap(~predictor, scales= "free") + standard_theme + ylab("Predicted red drum CPUE")
df_env_bc_forage %>% ggplot(aes(x= reddrumP915, y= pred2)) + geom_point() + geom_smooth(loess=TRUE) + standard_theme

#partial effect plots: show component effect of each of smooth or linear terms in model, centered around mean: increase or decrease in y axis is reflected in average predicted value of response, if above 0 than higher than average, decrease in ssal decreases # of reddrum  

#Removal of SAVDistkm
reddrum_env2 <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(SAVkm), family= tw(link= "log",), data=df_CPUE_length_wide_both)
summary(reddrum_env2)

vif(reddrum_env2)
cor(df_CPUE_length_wide_both %>% dplyr::select(avgdepth,avgssal, avgstemp, avgsdo, SAVkm, NoFishRest)) #SAVkm correlated by 0.40 with avgssal 
```

##### Models: best
```{r}
#Predictions matter her e
allformulas_reddrum <- dredgeform(pred = "reddrumP915", covars = c("s(avgdepth)", "s(avgssal)", "s(avgstemp)", "s(avgsdo)", "s(SAVkm)", "s(NoFishRest)"))

compare_var_tw_reddrum <- as.data.frame(matrix(ncol = 2, nrow = 0))
colnames(compare_var_tw_reddrum) <- c("formula", "AIC")
for (i in 1:length(allformulas_reddrum)) {
model_tw_reddrum <- gam(as.formula(allformulas_reddrum[i]), data=df_inf_train, family= tw(link= "log"))
compare_var_tw_reddrum[i, 1] <- allformulas_reddrum[i]
compare_var_tw_reddrum[i, 2] <- AIC(model_tw_reddrum)
print(i)
}

write.csv(compare_var_tw_reddrum, "/users/sallydowd/Desktop/Ch1Data/Final_results/GAMs/Env/compare_var_tw_reddrum_both_env.csv")
```

#### Southern kingfish

##### Models

```{r}
southernkingfish_env <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor), family= tw(link= "log"), data=df_CPUE_length_wide_both)
summary(southernkingfish_env)

southernkingfish_env_bc <- gam(southernkingfishP915 ~ s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(smallbluecrabP120), family= tw(link= "log"), data=df_CPUE_length_wide_both)
summary(southernkingfish_env_bc)

southernkingfish_env_forage <- gam(southernkingfishP915 ~ s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(southernkingfishP915forageP915) + s(southernkingfishP915forageP120), family= tw(link= "log"), data=df_CPUE_length_wide_both)
summary(southernkingfish_env_forage)

southernkingfish_env_bc_forage <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp) + s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(southernkingfishP915forageP120) + s(southernkingfishP915forageP915) + s(smallbluecrabP120), family= tw(link= "log"), data=df_CPUE_length_wide_both)
summary(southernkingfish_env_bc_forage)

AIC(southernkingfish_env, southernkingfish_env_bc, southernkingfish_env_forage, southernkingfish_env_bc_forage) %>% arrange(AIC)
```

#### Black drum
##### Models 
```{r}
#Black drum
blackdrum_env <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor), family= tw(link= "log"), data=df_CPUE_length_wide_both)
summary(blackdrum_env)

blackdrum_env_bc <- gam(blackdrumP915 ~ s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(smallbluecrabP120), family= tw(link= "log"), data=df_CPUE_length_wide_both)
summary(blackdrum_env_bc)

blackdrum_env_forage <- gam(blackdrumP915 ~ s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(blackdrumP915forageP120), family= tw(link= "log"), data=df_CPUE_length_wide_both)
summary(blackdrum_env_forage)

blackdrum_env_bc_forage <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp) + s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(blackdrumP915forageP120) + s(smallbluecrabP120), family= tw(link= "log"), data=df_CPUE_length_wide_both)
summary(blackdrum_env_bc_forage)

AIC(blackdrum_env, blackdrum_env_bc, blackdrum_env_forage, blackdrum_env_bc_forage) %>% arrange(AIC)
```
