---
title: "gJam_inference1_burnin"
format: html
editor: visual
---

```{r}
source("~/Documents/GitHub/NCBlueCrab_Predators/Scripts/Load.SDM.Final.R")

df <- df_CPUE_length_wide_both
```

#### Red drum

##### Modo1

```{r}
#5000, 800
xdata <- df %>% dplyr::select(avgdepth, avgstemp, avgssal, avgsdo, NoFishRest, Yearfactor)
ydata <- df %>% dplyr::select(reddrumP915, logsmallbluecrabP120, logreddrumP915forageP120, logreddrumP915forageP915) 
ml <- list(ng = 5000, burnin = 800, typeNames = 'CA')
formula_str <- paste("~", paste(colnames(xdata), collapse = " + "))
modo1 <- gjam(formula= as.formula(formula_str), xdata = xdata, ydata = ydata, modelList = ml)
save(modo1, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Red_drum/Env_bc_forage/modo1/modo1.RData")
plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = '/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Red_drum/Env_bc_forage/modo1')
gjamPlot(output = modo1, plotPars = plot)

#Not great 
```

##### Modo2

```{r}
#10,000, 400
xdata <- df %>% dplyr::select(avgdepth, avgstemp, avgssal, avgsdo, NoFishRest, Yearfactor)
ydata <- df %>% dplyr::select(reddrumP915, logsmallbluecrabP120, logreddrumP915forageP120, logreddrumP915forageP915) 
ml <- list(ng = 10000, burnin = 400, typeNames = 'CA')
formula_str <- paste("~", paste(colnames(xdata), collapse = " + "))
modo2 <- gjam(formula= as.formula(formula_str), xdata = xdata, ydata = ydata, modelList = ml)
save(modo2, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Red_drum/Env_bc_forage/modo2/modo2.RData")
plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = '/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Red_drum/Env_bc_forage/modo2')
gjamPlot(output = modo2, plotPars = plot)
#A bit better
```

##### Modo3

```{r}
#20,000, 8,000
xdata <- df %>% dplyr::select(avgdepth, avgstemp, avgssal, avgsdo, NoFishRest, Yearfactor)
ydata <- df %>% dplyr::select(reddrumP915, logsmallbluecrabP120, logreddrumP915forageP120, logreddrumP915forageP915) 
ml <- list(ng = 20000, burnin = 8000, typeNames = 'CA')
formula_str <- paste("~", paste(colnames(xdata), collapse = " + "))
modo3 <- gjam(formula= as.formula(formula_str), xdata = xdata, ydata = ydata, modelList = ml)
save(modo3, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Red_drum/Env_bc_forage/modo3/modo3.RData")
plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = '/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Red_drum/Env_bc_forage/modo3')
gjamPlot(output = modo3, plotPars = plot)
```

##### Modo4

```{r}
#60,000, 10,000
xdata <- df %>% dplyr::select(avgdepth, avgstemp, avgssal, avgsdo, NoFishRest, Yearfactor)
ydata <- df %>% dplyr::select(reddrumP915, logsmallbluecrabP120, logreddrumP915forageP120, logreddrumP915forageP915) 
ml <- list(ng = 60000, burnin = 10000, typeNames = 'CA')
formula_str <- paste("~", paste(colnames(xdata), collapse = " + "))
modo4 <- gjam(formula= as.formula(formula_str), xdata = xdata, ydata = ydata, modelList = ml)
save(modo4, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Red_drum/Env_bc_forage/modo4/modo4.RData")
plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = '/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Red_drum/Env_bc_forage/modo4')
gjamPlot(output = modo4, plotPars = plot)
```

#### Black drum

```{r}
df <- df_CPUE_length_wide_both

df <- df %>% mutate(logsmallbluecrabP120= log(smallbluecrabP120+1), logblackdrumP915forageP120= log(blackdrumP915forageP120+1))
```

##### Modo2

```{r}
#10,000, 400
xdata <- df %>% dplyr::select(avgdepth, avgstemp, avgssal, avgsdo, NoFishRest, Yearfactor)
ydata <- df %>% dplyr::select(blackdrumP915, logsmallbluecrabP120, logblackdrumP915forageP120) 
ml <- list(ng = 10000, burnin = 400, typeNames = 'CA')
formula_str <- paste("~", paste(colnames(xdata), collapse = " + "))
modo2 <- gjam(formula= as.formula(formula_str), xdata = xdata, ydata = ydata, modelList = ml)
save(modo2, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/black_drum/Env_bc_forage/modo2/modo2.RData")
plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = '/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/black_drum/Env_bc_forage/modo2')
gjamPlot(output = modo2, plotPars = plot)
```

##### Modo3

```{r}
#20,000, 8000
xdata <- df %>% dplyr::select(avgdepth, avgstemp, avgssal, avgsdo, NoFishRest, Yearfactor)
ydata <- df %>% dplyr::select(blackdrumP915, logsmallbluecrabP120, logblackdrumP915forageP120) 
ml <- list(ng = 20000, burnin = 8000, typeNames = 'CA')
formula_str <- paste("~", paste(colnames(xdata), collapse = " + "))
modo3 <- gjam(formula= as.formula(formula_str), xdata = xdata, ydata = ydata, modelList = ml)
save(modo3, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/black_drum/Env_bc_forage/modo3/modo3.RData")
plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = '/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/black_drum/Env_bc_forage/modo3')
gjamPlot(output = modo3, plotPars = plot)
```

##### Modo4

```{r}
#60,000, 10,000
xdata <- df %>% dplyr::select(avgdepth, avgstemp, avgssal, avgsdo, NoFishRest, Yearfactor)
ydata <- df %>% dplyr::select(blackdrumP915, logsmallbluecrabP120, logblackdrumP915forageP120) 
ml <- list(ng = 60000, burnin = 10000, typeNames = 'CA')
formula_str <- paste("~", paste(colnames(xdata), collapse = " + "))
modo4 <- gjam(formula= as.formula(formula_str), xdata = xdata, ydata = ydata, modelList = ml)
save(modo4, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/black_drum/Env_bc_forage/modo4/modo4.RData")
plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = '/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/black_drum/Env_bc_forage/modo4')
gjamPlot(output = modo4, plotPars = plot)
```

#### Southern kingfish

```{r}
df <- df_CPUE_length_wide_both

df <- df %>% mutate(logsmallbluecrabP120= log(smallbluecrabP120+1), logsouthernkingfishP915forageP915= log(southernkingfishP915forageP915+1), logsouthernkingfishP915forageP120= log(southernkingfishP915forageP120+1))
```

##### Modo3

```{r}
#20,000, 8,000
xdata <- df %>% dplyr::select(avgdepth, avgstemp, avgssal, avgsdo, NoFishRest, Yearfactor)
ydata <- df %>% dplyr::select(southernkingfishP915, logsmallbluecrabP120, logsouthernkingfishP915forageP120, logsouthernkingfishP915forageP915) 
ml <- list(ng = 20000, burnin = 8000, typeNames = 'CA')
formula_str <- paste("~", paste(colnames(xdata), collapse = " + "))
modo3 <- gjam(formula= as.formula(formula_str), xdata = xdata, ydata = ydata, modelList = ml)
save(modo3, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Southern_kingfish/Env_bc_forage/modo3/modo3.RData")
plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = '/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Southern_kingfish/Env_bc_forage/modo3')
gjamPlot(output = modo3, plotPars = plot)
library(beepr)
beep(sound=8)
```

#### Both ind

##### Modo2

```{r}
df <- df_CPUE_length_wide_both 
xdata <- df %>% dplyr::select(avgdepth, avgstemp, avgssal, avgsdo, NoFishRest, Yearfactor)
ydata <- df %>% dplyr::select(smallatlanticcroakerP915, smallatlanticmenhadenP915, blackdrumP915, pinfishP915, reddrumP915, smallsouthernflounderP915, southernkingfishP915, smallspotP915, smallatlanticcroakerP120, smallbluecrabP120, brownshrimpP120, whiteshrimpP120, pinkshrimpP120, pinfishP120, southernflounderP120, smallspotP120, atlanticmenhadenP120)
species <- gjamTrimY(ydata, 50, OTHER = FALSE)$y %>% colnames() #minimum # of non-zero observations: 50
ydata <- ydata[, species] %>% as.data.frame() #filter out rare species
tot <- cbind(xdata, ydata)
set.seed(123)
smp_size <- floor(0.70 * nrow(df))
train_ind <- sample(seq_len(nrow(tot)), size = smp_size)
train <- tot[train_ind, ]
test <- tot[-train_ind, ]
xdata_train <- train[,colnames(xdata)]
ydata_train <- train[,colnames(ydata)]
xdata_test <- test[,colnames(xdata)]
ydata_test <- test[,colnames(ydata)]
```

```{r}
#10,000, 400
ml <- list(ng = 10000, burnin = 400, typeNames = 'CA')

both_ind_burn2 <- gjam(~avgdepth + avgstemp + avgssal + avgsdo + NoFishRest + Yearfactor, xdata = xdata_train, ydata = ydata_train, modelList = ml)

save(both_ind_burn2, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Both_ind/modo2/both_ind_burn2.RData")

plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Both_ind/modo2")
gjamPlot(output = both_ind_burn2, plotPars = plot)
```

##### Modo3

```{r}
#20,000, 8,000
ml <- list(ng = 20000, burnin = 8000, typeNames = 'CA')

both_ind_burn3 <- gjam(~avgdepth + avgstemp + avgssal + avgsdo + NoFishRest + Yearfactor, xdata = xdata_train, ydata = ydata_train, modelList = ml)

save(both_ind_burn3, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Both_ind/modo3/both_ind_burn3.RData")

plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Both_ind/modo3")
gjamPlot(output = both_ind_burn3, plotPars = plot)
beep(sound=8)
```

#### One ind

```{r}
#May and June, 2001-2019
df <- df_CPUE_length_wide_P915
                                          
xdata <- df %>% dplyr::select(avgdepth, avgstemp, avgssal, avgsdo, NoFishRest, Yearfactor)
ydata <- df %>% dplyr::select(smallatlanticcroakerP915, smallatlanticmenhadenP915, blackdrumP915, pinfishP915, reddrumP915, smallsouthernflounderP915, southernkingfishP915, smallspotP915)
species <- gjamTrimY(ydata, 50, OTHER = FALSE)$y %>% colnames() #minimum # of non-zero observations: 50
ydata <- ydata[, species] %>% as.data.frame() #filter out rare species

tot <- cbind(xdata, ydata)

set.seed(123)
smp_size <- floor(0.70 * nrow(df))
train_ind <- sample(seq_len(nrow(tot)), size = smp_size)
train <- tot[train_ind, ]
test <- tot[-train_ind, ]

xdata_train <- train[,colnames(xdata)]
ydata_train <- train[,colnames(ydata)]
xdata_test <- test[,colnames(xdata)]
ydata_test <- test[,colnames(ydata)]
```

##### Modo 2

```{r}
#10,000, 400
ml <- list(ng = 10000, burnin = 400, typeNames = 'CA')

one_ind_burn2 <- gjam(~avgdepth + avgstemp + avgssal + avgsdo + NoFishRest + Yearfactor, xdata = xdata_train, ydata = ydata_train, modelList = ml)

save(one_ind_burn2, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/One_ind/modo2/one_ind_burn2.RData")

plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/One_ind/modo2")
gjamPlot(output = one_ind_burn2, plotPars = plot)
```

##### Modo 3

```{r}
#20,000, 8,000
ml <- list(ng = 20000, burnin = 8000, typeNames = 'CA')

one_ind_burn3 <- gjam(~avgdepth + avgstemp + avgssal + avgsdo + NoFishRest + Yearfactor, xdata = xdata_train, ydata = ydata_train, modelList = ml)

save(one_ind_burn3, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/One_ind/modo3/one_ind_burn3.RData")

plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/One_ind/modo3")
gjamPlot(output = one_ind_burn3, plotPars = plot)
beep(sound=8)
```

#### Non-averaged

```{r}
#May and June, 2001-2019
df <- df_CPUE_length_wide_indP915
                                          
xdata <- df %>% dplyr::select(Depth, Stemp, Ssal, Sdo, NoFishRest, Yearfactor)
ydata <- df %>% dplyr::select(smallatlanticcroakerP915, smallatlanticmenhadenP915, blackdrumP915, pinfishP915, reddrumP915, smallsouthernflounderP915, southernkingfishP915, smallspotP915)
species <- gjamTrimY(ydata, 50, OTHER = FALSE)$y %>% colnames() #minimum # of non-zero observations: 50
ydata <- ydata[, species] %>% as.data.frame() #filter out rare species

tot <- cbind(xdata, ydata)

set.seed(123)
smp_size <- floor(0.70 * nrow(df))
train_ind <- sample(seq_len(nrow(tot)), size = smp_size)
train <- tot[train_ind, ]
test <- tot[-train_ind, ]

xdata_train <- train[,colnames(xdata)]
ydata_train <- train[,colnames(ydata)]
xdata_test <- test[,colnames(xdata)]
ydata_test <- test[,colnames(ydata)]
```

##### Modo 1

```{r}
#5,000 800
ml <- list(ng = 5000, burnin = 800, typeNames = 'CA')

non_avg1 <- gjam(~Depth + Stemp + Ssal + Sdo + NoFishRest + Yearfactor, xdata = xdata_train, ydata = ydata_train, modelList = ml)

save(non_avg1, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Non_avg/modo1/non_avg1.RData")

plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Non_avg/modo1")
gjamPlot(output = non_avg1, plotPars = plot)
beep(sound=8)
```

##### Modo 2

```{r}
#10,000, 400
ml <- list(ng = 10000, burnin = 400, typeNames = 'CA')

non_avg2 <- gjam(~Depth + Stemp + Ssal + Sdo + NoFishRest + Yearfactor, xdata = xdata_train, ydata = ydata_train, modelList = ml)

save(non_avg2, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Non_avg/modo2/non_avg2.RData")

plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Non_avg/modo2")
gjamPlot(output = non_avg2, plotPars = plot)
```

##### Modo 3

```{r}
#20,000, 8,000
ml <- list(ng = 20000, burnin = 8000, typeNames = 'CA')

non_avg3 <- gjam(~Depth + Stemp + Ssal + Sdo + NoFishRest + Yearfactor, xdata = xdata_train, ydata = ydata_train, modelList = ml)

save(non_avg3, file= "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Non_avg/modo3/non_avg3.RData")

plot <- list(SMALLPLOTS = T, GRIDPLOTS=T, 
                        SAVEPLOTS = T, PLOTALLY = T, 
                        outFolder = "/users/sallydowd/Desktop/Ch1Data/Final_results/gJam/Burnin/Non_avg/modo3")
gjamPlot(output = non_avg3, plotPars = plot)
```
