---
title: "P195_EDA"
format: html
editor: visual
---

#### Overall data set description

P195 is a stratified-random trawl survey that has collected both biotic and abiotic information since 1987 in both June and September in Pamlico Sound and its tributaries. In 1990, all sampling in the Albemarle Sound and the March and December sampling in Pamlico Sound was elmiinated. The survey uses two 30-foot head rope demersal mongoose trawls to sample waters within Pamlico Sound as well as the Pamlico, Neuse, and Pungo rivers (4 areas). As there are both deep and shallow sampling sites for the two locations in Pamlico Sound, the survey area is divided into seven strata. Since the survey is stratified-random, fifty-four stations are selected at random from the seven strata for June and September. The fishing effort is kept consistent with 20 minute tows at a speed of 2.5 knots to cover 87,750 square feet. The catch from the two nets are combined to form a single sample.

The survey collects total abundance and weight for each species found, environmental information at the site, and additional length data for target species. A total number and weight is recorded for each species. For target species, at least 30 individuals are measured and total weights are recorded. Water clarity started to be recorded in 2008 with a Secchi disk and shoreline and sediment data started to be recorded in 2009.

On 07/07/23, I downloaded Abundance and Biomass & Event Information from the SEAMAP website for the Pamlico Sound Survey and processed it in Toclean.R. The downloaded files had all years available, all locations, latitudes, were for Summer (June, July, and August) as well as Fall (September, October, and November), and contained all species. Although I had downloaded it in April to use it for BIOL 562 project, I decided it would be better to redownload for the purpose of this study.
