---
title: "SchoenersD"
output: html_document
date: "2024-03-19"
---

Schoener's D is a niche equivalency metric that measures how equally predator and prey use space relative to its availability. One downside to this is that it will return a high value of overlap in cases where both species co-occur across large areas at low densities or probabilities of occurrence. 

This index considers the frequencies for species X and Y for the ith category. Originally, i were the prey sizes. With species distribution modeling, they would be regions along an environmental gradient and frequencies are the fitted values from an SDM. 

Schoener's D quantifies the extent to which a pair of species may interact in the same space (both likely to be present together in a location). This doesn't tell us how they respond to that gradient. Species that have completely opposite responses to the environment may still have relatively high niche overlap, D. Warren's D uses Hellinger distance and is a modification of Schoener's D. 

Species may occupy similar locations along an environmental gradient while having very different responses to that gradient

-Resource here: https://plantarum.ca/2021/12/02/schoenersd/
```{r}
library(ggplot2)
library(grid)

olaps <- function(sp1, sp2){
  sp1 <- sp1/sum(sp1) ## scale the values for each species 0:1
  sp2 <- sp2/sum(sp2)
  
  plot.table <- data.frame(
    species = c(rep("sp1", length(sp1)),
                rep("sp2", length(sp2))),
    env = c(seq(1:length(sp1)), seq(1:length(sp2))),
    suitability = c(sp1, sp2))

  D = 1 - sum(abs(sp1 - sp2))/2
  I = 1 - sum((sqrt(sp1) - sqrt(sp2))^2)/2
  cor = cor(sp1, sp2, method = "spearman")

  grob <- grobTree(textGrob(paste("D =", round(D, 2),
                                 "  I =", round(I, 2),
                                 "  Cor =", round(cor, 2)),
                           x = 0.1,  y = 0.95, hjust = 0,
                           gp = gpar(fontsize = 15)))
  
  suitplot = qplot(env, suitability, data = plot.table,
                   col = species, geom = "line") +
    annotation_custom(grob)

  return(list(
    D = D, I = I, cor = cor, suitplot = suitplot
  ))
  
}

olaps(df_CPUE_length_wide_both$smallbluecrabP120, df_CPUE_length_wide_both$southernflounderP120)
```

