---
title: "R Notebook"
output: html_notebook
---

```{r}
source("~/Documents/GitHub/NCBlueCrab_Predators/Final/Scripts/Load.SDM.Final.R")
```

### Red drum

#### Random effects
```{r}
reddrum_env_re <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+ s(Yearfactor, bs = "re"), family= tw(), data=df_CPUE_length_wide_both)

reddrum_bc_re <- gam(reddrumP915~ s(logsmallbluecrabP120) + s(Yearfactor, bs = "re"), family= tw(), data=df_CPUE_length_wide_both)

reddrum_forage_re <- gam(reddrumP915~ s(logreddrumP915forageP915) + s(logreddrumP915forageP120) + s(Yearfactor, bs = "re"), family= tw(), data=df_CPUE_length_wide_both)

reddrum_env_bc_re <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+ s(Yearfactor, bs = "re") + s(logsmallbluecrabP120), family= tw(), data=df_CPUE_length_wide_both)

reddrum_env_forage_re <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+ s(Yearfactor, bs = "re") + s(logreddrumP915forageP915+1) + s(logreddrumP915forageP120+1), family= tw(), data=df_CPUE_length_wide_both)

reddrum_env_bc_forage_re <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp) + s(avgsdo)+s(NoFishRest)+ s(Yearfactor, bs = "re") + s(logreddrumP915forageP120+1) + s(logreddrumP915forageP915+1) + s(logsmallbluecrabP120+1), family= tw(),  data=df_CPUE_length_wide_both)

AIC(reddrum_env_re, reddrum_bc_re, reddrum_forage_re, reddrum_env_bc_re, reddrum_env_forage_re, reddrum_env_bc_forage_re) %>% arrange(AIC)
```

#### Compare 
```{r}
reddrum_env_bc <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(logsmallbluecrabP120), family= tw(), data=df_CPUE_length_wide_both)
reddrum_bc <- gam(reddrumP915~ s(logsmallbluecrabP120) + factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

summary(reddrum_env_bc)
summary(reddrum_env_bc_re)

summary(reddrum_bc_re)
summary(reddrum_bc)
```

### Southern kingfish

#### Random effects
```{r}
southernkingfish_env_re <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+ s(Yearfactor, bs = "re"), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_bc_re <- gam(southernkingfishP915~ s(logsmallbluecrabP120) + s(Yearfactor, bs = "re"), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_forage_re <- gam(southernkingfishP915~ s(logsouthernkingfishP915forageP915) + s(logsouthernkingfishP915forageP120) + s(Yearfactor, bs = "re"), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_env_bc_re <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+ s(Yearfactor, bs = "re") + s(logsmallbluecrabP120), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_env_forage_re <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+ s(Yearfactor, bs = "re") + s(logsouthernkingfishP915forageP915) + s(logsouthernkingfishP915forageP120), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_env_bc_forage_re <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp) + s(avgsdo)+s(NoFishRest)+ s(Yearfactor, bs = "re")+ s(logsouthernkingfishP915forageP120) + s(logsouthernkingfishP915forageP915) + s(logsmallbluecrabP120), family= tw(),  data=df_CPUE_length_wide_both)

AIC(southernkingfish_env_re, southernkingfish_bc_re, southernkingfish_forage_re, southernkingfish_env_bc_re, southernkingfish_env_forage_re, southernkingfish_env_bc_forage_re) %>% arrange(AIC)
```

```{r}
southernkingfish_env_forage <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(logsouthernkingfishP915forageP915) + s(logsouthernkingfishP915forageP120), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_env_bc_forage <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp) + s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(logsouthernkingfishP915forageP120) + s(logsouthernkingfishP915forageP915) + s(logsmallbluecrabP120), family= tw(),  data=df_CPUE_length_wide_both)

summary(southernkingfish_env_forage_re)
summary(southernkingfish_env_forage)

summary(southernkingfish_env_bc_forage_re)
summary(southernkingfish_env_bc_forage)
```

### Black drum

#### Random effects
```{r}
blackdrum_env_re <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+ s(Yearfactor, bs = "re"), family= tw(), data=df_CPUE_length_wide_both)

blackdrum_bc_re <- gam(blackdrumP915~ s(log(smallbluecrabP120+1)) + s(Yearfactor, bs = "re"), family= tw(), data=df_CPUE_length_wide_both)

blackdrum_forage_re <- gam(blackdrumP915~ s(log(blackdrumP915forageP120+1)) + s(Yearfactor, bs = "re"), family= tw(), data=df_CPUE_length_wide_both)

blackdrum_env_bc_re <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+ s(Yearfactor, bs = "re")+ s(log(smallbluecrabP120+1)), family= tw(), data=df_CPUE_length_wide_both)

blackdrum_env_forage_re <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+ s(Yearfactor, bs = "re") + s(log(blackdrumP915forageP120+1)), family= tw(), data=df_CPUE_length_wide_both)

blackdrum_env_bc_forage_re <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp) + s(avgsdo)+s(NoFishRest)+ s(Yearfactor, bs = "re") + s(log(blackdrumP915forageP120+1)) + s(log(smallbluecrabP120+1)), family= tw(),  data=df_CPUE_length_wide_both)

AIC(blackdrum_env_re, blackdrum_bc_re, blackdrum_forage_re, blackdrum_env_bc_re, blackdrum_env_forage_re, blackdrum_env_bc_forage_re) %>% arrange(AIC)
```

```{r}
blackdrum_env_forage <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(log(blackdrumP915forageP120+1)), family= tw(), data=df_CPUE_length_wide_both)

blackdrum_env_bc <- gam(blackdrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(log(smallbluecrabP120+1)), family= tw(), data=df_CPUE_length_wide_both)

summary(blackdrum_env_forage_re)
summary(blackdrum_env_forage)

summary(blackdrum_env_bc_re)
summary(blackdrum_env_bc)
```


