---
title: "GAM_sd"
format: html
editor: visual
---

#### Load packages, CPUE datasets, and filter them
```{r}
#Load packages and functions 
packages <- c("ggplot2", "tidyverse", "lubridate", "sf", "sp", "dplyr", "rnaturalearth", "readr", "readxl", "spatialEco", "rstatix", "viridis")
invisible(lapply(packages, library, character.only= TRUE))

world <- ne_countries(scale = "medium", returnclass = "sf")

standard_theme <- theme_bw() + theme(panel.border = element_rect(fill=NA, colour = "black")) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.text.align= 0, legend.title= element_text(size = 12), legend.text = element_text(size= 10), axis.text=element_text(size=10), axis.title=element_text(size=12))

#Load CPUE datasets
setwd("~/Documents/GitHub/NCBlueCrab_Predators")
p915_CPUE <- read_csv("Data/P915/Finalized/p915_CPUE.csv")
p120_CPUE <- read_csv("Data/P120/Finalized/p120_CPUE.csv")
p195_CPUE <- read_csv("Data/P195/Finalized/p195_CPUE.csv")

##Filter datasets: to note- add back in Sedsize and Btmcomp once this is fixed! and add back in secchi, don't know if Depthstart is actual depth but called it this in P195 
p915_CPUEedt <- p915_CPUE %>% select(-...1, -Obs, -Weather, -Winddir, -Windspd, -Sedsize, -Btmcomp, -doy, -Wbdytype, -Wbd, -Sample, -Sedsize_new, -Btmcomp_new, -Secchi) %>% filter(Speciescommonname %in% c("atlantic croaker", "black drum", "red drum", "southern flounder", "southern kingfish", "striped bass")) %>% filter(Year >= 2008) %>% rename("Location" = "Area", "Strata/station"= "Strata", "Depthzone"= "Quad") #added in species of focus for now (still waiting on data) 
p120_CPUEedt <- p120_CPUE %>% filter(Core== 1|Core==2) %>% select(-...1, -Program, -Nbrrec3, -Time, -Duration, -doy, -Core, -Sedsize, -Secchi) %>% filter(Year >= 2008) %>% rename("Strata/station"= "Station") %>% mutate(Depthzone= "Constant") #still don't have btmcomp or sedsize 
p195_CPUEedt <- p195_CPUE %>% select(-...1, -Timestart, -Duration, -Depthend, -Wbdytype, -Wbd, -Speciesscientificname, -Sedsize_new, -Btmcomp_new) %>% rename("Ssal" = "Salinitysurface", "Bsal"= "Salinitybottom", "Stemp"= "Tempsurface", "Btemp"= "Tempbottom", "Latitude"= "Latitudestart", "Longitude"= "Longitudestart", "Colnum"= "Numbertotal_new", "Control1"= "Eventname", "Strata/station"= "Stationcode", "Depth"= "Depthstart") %>% filter(Year >= 2008)
p195_CPUEedt$Depthzone[p195_CPUEedt$Depthzone %in% NA] <- "Constant"

colnames(p915_CPUEedt)
colnames(p120_CPUEedt) #only difference: Sedsize vs. Sedsize_new and BtmComp vs. Btmcomp_new
colnames(p195_CPUEedt)

column_diff <- setdiff(names(p120_CPUEedt), names(p195_CPUEedt))

##Get rid of NAs
summary(is.na(p915_CPUEedt)) #No NAs where it doesn't make sense
summary(is.na(p120_CPUEedt)) #Almost no NAs in general
summary(is.na(p195_CPUEedt)) #A good amount of NAs for Sedsize_new and Btmcomp_new b/c isn't greater than 2008 

p915_CPUEedt <- p915_CPUEedt %>% drop_na() #drops 6914 data points
p915_CPUEedt$Survey <- "P915"
p120_CPUEedt <- p120_CPUEedt %>% drop_na() #drops 564 data points 
p120_CPUEedt$Survey <- "P120"
p195_CPUEedt <- p195_CPUEedt %>% drop_na() #drops 1137 data points 
p195_CPUEedt$Survey <- "P195"
```

#### Grid coordinates: 
```{r}
#Add grid cells in 
p915_latlon <- p915_CPUEedt %>% select(Latitude, Longitude) %>% mutate(lat_lon = paste(Latitude, Longitude, sep= "_"))
p120_latlon <- p120_CPUEedt %>% select(Latitude, Longitude) %>% mutate(lat_lon = paste(Latitude, Longitude, sep= "_"))
p195_latlon <- p195_CPUEedt %>% select(Latitude, Longitude) %>% mutate(lat_lon = paste(Latitude, Longitude, sep= "_"))

lat_lon_combo <- rbind(p915_latlon, p120_latlon, p195_latlon)
lat_lon_combo <- lat_lon_combo %>% distinct(lat_lon, .keep_all= TRUE) 

world <- ne_countries(scale = "medium", returnclass = "sf")
# make an object the size and shape of the output you want
globe_bb <- matrix(c(-78.900147,33.802938,
                      -78.900147,36.672128,
                      -75.263672,36.672128,
                     -75.263672, 33.802938,
                     -78.900147,33.802938), byrow = TRUE, ncol = 2) %>% list() %>% st_polygon() %>% st_sfc(., crs = 4326)

globe_grid_30 <- st_make_grid(x= globe_bb, n = c(30,30), crs = 4326, what = 'polygons') %>% st_sf('geometry' = ., data.frame('ID' = 1:length(.))) #grid is 0.13째 by 0.13째 (14.4 km)

degrees_per_km = 1/111.0 #1 degree is 111 km 
degress <- 14.4*degrees_per_km #0.129
distance_km <- 14.4
degrees <- distance_km * 111

#ggplot(data = world) + geom_sf() + geom_sf(data = globe_grid_30, fill = NA) + coord_sf(xlim=c(-85, -70), ylim=c(25,40), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + geom_point(data = lat_lon_combo2, aes(x = Longitude, y = Latitude, color= Survey), size = .2) + coord_sf(xlim=c(-78, -75), ylim=c(33.5,37), expand = TRUE)

fish_spat <- as.data.frame(lat_lon_combo)
fish_spat$rowID <- 1:nrow(fish_spat)

coordinates(fish_spat) <- ~ Longitude + Latitude
fish_spat <- st_as_sf(fish_spat)
fish_spat <- st_set_crs(fish_spat, 4326)
grid <- globe_grid_30

fish_extract <- st_intersection(fish_spat, grid)
fish_extract_2 <- as.data.frame(fish_extract)

#Group to get rid of duplicates (there are times when a point is overlapping two grid cells)
fish_extract_2_2 <- fish_extract_2[!duplicated(fish_extract_2[c("rowID")]),] #this should be the same size as fish spat, it is 5 observations less, thinking this is bc a few datapoints might be outside of grid cells, didn't change in size from fish_extract_2
fish_extract_2_2$gridID <- fish_extract_2_2$ID
fish_extract_2_2edt <- fish_extract_2_2[,-c(2,3, 4)]

unique(fish_extract_2_2edt$gridID)
write.csv(fish_extract_2_2edt, "~/Documents/GitHub/NCBlueCrab_Predators/Data/SDM.grids.csv") #updated on 08/01/23
```

#### Predictor variables: coordinates

```{r}
#Load predictor variable datasets
setwd("~/Documents/GitHub/NCBlueCrab_Predators/Data/Predictor_variables")
inlet_coords <- st_read("Inlet.points.kml")
coords2 <- st_coordinates(inlet_coords)
inlet_coords$Latitude <- coords2[, "Y"]
inlet_coords$Longitude <- coords2[, "X"]
inlet_coords <- inlet_coords %>% select(-Description)
inlet_coords <- st_transform(inlet_coords) #NC CRS

NC_watersheds <- st_read("NC_watersheds/HUC_10.shp")
NC_watersheds <- st_transform(NC_watersheds, crs = 4326)

library(sf)
SAV_08 <- st_read("SAV/SAV_2006_2008/SAV_2006-2008_Mapping_Revised.shp")
SAV_08 <- st_transform(SAV_08, crs = 4326) #it was already in WGS 84 
SAV_14 <- st_read("SAV/SAV_2012_2014/SAV_2012-2014_Mapping.shp")
SAV_14 <- st_transform(SAV_14, crs = 4326)
SAV_20 <- st_read("SAV/SAV_2019_2020/SAV_2019_2020_Mapping.shp")
SAV_20 <- st_transform(SAV_20, crs = 4326)

#Add in other metrics to coordinates
##Distance to inlet 
coords_survey <- rbind(p915_CPUEedt %>% select(Latitude, Longitude, Survey), p120_CPUEedt %>% select(Latitude, Longitude, Survey), p195_CPUEedt %>% select(Latitude, Longitude, Survey))
coords_surveyedt <- coords_survey %>% distinct(Latitude, Longitude, .keep_all= TRUE) %>% select(-Survey)
coords_surveysf <- st_as_sf(coords_surveyedt, coords= c("Longitude", "Latitude"), crs= 4326)
coords_inlet_nearest <- st_nearest_feature(coords_surveysf, inlet_coords)
dist_inlets = st_distance(coords_surveysf, inlet_coords[coords_inlet_nearest,], by_element=TRUE)
dist_inlets <- as.numeric(dist_inlets)
coords_surveysf <- coords_surveysf %>% mutate(dist_inlets= dist_inlets)

##Wbd 
intersections <- st_intersection(coords_surveysf, NC_watersheds)
unique(intersections$HU_10_NAME)

intersections_edt <- intersections %>% mutate(Wbd = ifelse(HU_10_NAME %in% "Brunswick River-Cape Fear River"|HU_10_NAME %in% "Goshen Swamp"|HU_10_NAME %in% "Liliput Creek-Cape Fear River"|HU_10_NAME %in% "Harrisons Creek-Northeast Cape Fear River", "Cape Fear River", ifelse(HU_10_NAME %in% "South Creek-Pamlico River"|HU_10_NAME %in% "Chocowinity Bay-Pamlico River", "Pamlico River", ifelse(HU_10_NAME %in% "Pantego Creek"|HU_10_NAME %in% "Headwaters Pungo River"| HU_10_NAME %in% "Intracoastal Waterway-Pungo River"| HU_10_NAME %in% "Outlet Pungo River", "Pungo River", ifelse(HU_10_NAME %in% "Pamlico Sound-Ocracoke Inlet"|HU_10_NAME %in% "Pamlico Sound-Hatteras Inlet"| HU_10_NAME %in% "Cape Lookout Shoals-Core Banks"|HU_10_NAME %in% "Neuse River-Pamlico Sound"|HU_10_NAME %in% "Oyster Creek-Jarrett Bay"|HU_10_NAME %in% "Bogue Banks-Shackleford Banks"|HU_10_NAME %in% "Lake Mattamuskeet-Rose Bay"|HU_10_NAME %in% "Jones Bay-Bay River", "Pamlico Sound", ifelse(HU_10_NAME %in% "Headwaters New River"|HU_10_NAME %in% "New River Inlet", "New River", ifelse(HU_10_NAME %in% "Upper Broad Creek-Neuse River"|HU_10_NAME %in% "Cherry Point-Neuse River"|HU_10_NAME %in% "Town of Oriental-Neuse River", "Neuse River", intersections$HU_10_NAME)))))))

predictors_df <- intersections_edt %>% select(geometry, dist_inlets, Wbd, HU_10_NAME)

##Wbd type
predictors_df <- predictors_df %>% mutate(Wbd_type= ifelse(grepl("River", Wbd), "River", ifelse(grepl("Sound", Wbd), "Sound", predictors_df$Wbd))) #this worked! 

##Check if it worked on a subset of data: it did!
coords2 <- st_coordinates(predictors_df)
predictors_df$Latitude <- coords2[, "Y"]
predictors_df$Longitude <- coords2[, "X"] #Add coordinates back in

ggplot(data= world) + geom_sf() + geom_point(data= predictors_df[1000:2000,], aes(x= Longitude, y= Latitude, color= HU_10_NAME)) + coord_sf(xlim=c(-78, -75), ylim=c(33,37), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + labs(x= "Longitude", y= "Latitude") #it works! just need to do it with less data

ggplot(data= world) + geom_sf() + geom_point(data= predictors_df[100:200,], aes(x= Longitude, y= Latitude, color= dist_inlets)) + geom_point(data= inlet_coords, aes(x= Longitude, y= Latitude)) + coord_sf(xlim=c(-78, -75), ylim=c(33,37), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + labs(x= "Longitude", y= "Latitude") + scale_color_viridis() #it works! just need to do it with less data 

##Join predictors, gridded, and CPUE datasets
###Predictors with gridID
predictors_df$lat_lon <- paste(predictors_df$Latitude, predictors_df$Longitude, sep = "_") 
predictors_df_edt <- st_drop_geometry(predictors_df)
gridded_coords <- read.csv("~/Documents/GitHub/NCBlueCrab_Predators/Data/SDM.grids.csv")
predictors_gridded <- predictors_df_edt %>% left_join(gridded_coords, by= "lat_lon") %>% select(lat_lon, gridID, dist_inlets, Wbd, Wbd_type)
#write.csv(predictors_gridded,"~/Documents/GitHub/NCBlueCrab_Predators/Data/Predictor_variables/predictors_gridded.csv") #updated on 08/02/23

###Predictors and gridID with gridID geometry
pred_gridd_geom <- predictors_gridded %>% left_join(globe_grid_30 %>% rename("gridID"= "ID"), by= "gridID")
pred_gridd_geom <- st_as_sf(pred_gridd_geom)

ggplot(data = world) + geom_sf() + geom_sf(data =pred_gridd_geom, fill = NA) + coord_sf(xlim=c(-78, -75), ylim=c(33.5,37), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + standard_theme + geom_point(data = lat_lon_combo2, aes(x = Longitude, y = Latitude, color= Survey), size = .2) 

###Predictors with CPUE data
CPUE_dfs <- rbind(p915_CPUEedt, p195_CPUEedt, p120_CPUEedt)
CPUE_dfs$lat_lon <- paste(CPUE_dfs$Latitude, CPUE_dfs$Longitude, sep = "_") 
CPUE_dfs_gridded <- CPUE_dfs %>% left_join(pred_gridd_geom, by= "lat_lon") #49 gridIDs with NA are out of the study area (out of sound or Antartica)
CPUE_dfs_gridded_final <- CPUE_dfs_gridded %>% drop_na() #removed 49 rows

write.csv(CPUE_dfs_gridded_final, "~/Documents/GitHub/NCBlueCrab_Predators/Data/CPUE_dfs_gridded_final.csv")
```

#### Outlier analysis
```{r}
predictors_gridded <- read.csv("~/Documents/GitHub/NCBlueCrab_Predators/Data/fish_extract_2_2.csv")



globe_grid_30 <- st_make_grid(x= globe_bb, n = c(30,30), crs = 4326, what = 'polygons') %>% st_sf('geometry' = ., data.frame('ID' = 1:length(.))) #grid is 0.13째 by 0.13째 (14.4 km)






#Outliers
t<- p915_CPUEedt %>% identify_outliers(Latitude)
t2 <-t[which(t$is.extreme %in% TRUE), ]

lower_bound_SummerFlounder <- quantile(P195JuneSDMDATAREDO_SummerFlounderF$SummerFlounderCount, 0.01)
upper_bound_SummerFlounder <- quantile(P195JuneSDMDATAREDO_SummerFlounderF$SummerFlounderCount, 0.99)
outlier_ind_SummerFlounder <- which(P195JuneSDMDATAREDO_SummerFlounderF$SummerFlounderCount < lower_bound_SummerFlounder | P195JuneSDMDATAREDO_SummerFlounderF$SummerFlounderCount> upper_bound_SummerFlounder)
View(P195JuneSDMDATAREDO_SummerFlounderF[outlier_ind_SummerFlounder, ])
```

#### CPUE calculation

```{r}
#P120: 
summary(p120_CPUE$Duration) #All tows are 1 minute speed in duration
#Adjusted to cover 75 yards, headrope is 10.5 feet, so area covered in one tow is 0.02195 hectares
p120_CPUEedt$Effort= 0.02195
p120_CPUEedt$CPUE=p120_CPUEedt$Colnum/p120_CPUEedt$Effort

#P195 
##Effort in p195_abund is 1.812, double rigged trawl, duration is 20 mins at a speed of 2.5 knots to cover 87,750 square feet.
p195_CPUEedt$Effort = 1.812
p195_CPUEedt$CPUE=p195_CPUEedt$Colnum/p195_CPUEedt$Effort

#P915
p915_CPUEedt <- p915_CPUEedt %>% mutate("Soak_time" = ifelse(Area == 'CAPEF' & Month  %in% c(04, 05, 06, 07, 08, 09), 240, ifelse(Area == 'NEWR' & Month %in% c(04, 05, 06, 07, 08, 09), 240, 720))) #add in standard soak time, max is 12 hours, soak time 4 hours for CAPEF and NEWR b/w April and September
p915_CPUEedt$CPUE= p915_CPUEedt$Colnum/p915_CPUEedt$Soak_time #calculate CPUE

t <- p915_CPUEedt %>% filter(Area %in% "DARE2", Strata %in% "MANT2")


```

#### Predictor variables: grid

```{r}
#visualize btmcomp and sedsize
```

```{r}
globe_bb <- matrix(c(-78.900147,33.802938,
                      -78.900147,36.672128,
                      -75.263672,36.672128,
                     -75.263672, 33.802938,
                     -78.900147,33.802938), byrow = TRUE, ncol = 2) %>% list() %>% st_polygon() %>% st_sfc(., crs = 4326)

globe_grid_20 <- st_make_grid(x= globe_bb, n = c(30,30), crs = 4326, what = 'polygons') %>% st_sf('geometry' = ., data.frame('ID' = 1:length(.))) #0.13 degrees

degrees_per_km = 1/111.0 #1 degree is 111 km 
degress <- 14.4*degrees_per_km #0.129

ggplot(data = world) + geom_sf() + geom_sf(data = globe_grid_20, fill = NA) + coord_sf(xlim=c(-85, -70), ylim=c(25,40), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + geom_point(data = coords_survey, aes(x = Longitude, y = Latitude, color= Survey), size = .2) + coord_sf(xlim=c(-78, -75), ylim=c(33,37), expand = TRUE)
ggsave("Users/sallydowd/Desktop.savedIT.png")
```

```{r}
setwd("~/Documents/GitHub/NCBlueCrab_Predators")
grid_t <- read.csv("Data/SDM.grids.csv")



Btm_test <- rbind(p915_CPUEedt %>% select(Btmcomp_new, Sedsize_new, Latitude, Longitude) %>% mutate(Survey= "P915"), p195_CPUEedt %>% select(Btmcomp_new, Sedsize_new, Latitude, Longitude) %>% mutate(Survey= "P195"))

ggplot(data= world) + geom_sf() + geom_sf(data = globe_grid_20, fill = NA) + coord_sf(xlim=c(-78, -75), ylim=c(34,37), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + geom_point(data = Btm_test, aes(x = Longitude, y = Latitude, colour = Survey), size = .2)
```
