---
title: "Part1Inference"
format: html
editor: visual
---

```{r}
source("~/Documents/GitHub/NCBlueCrab_Predators/Scripts/Load.SDM.Final.R")
```

### Generalized additive models
#### Red drum

##### Models

```{r}
reddrum_env <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

reddrum_bc <- gam(reddrumP915~ s(logsmallbluecrabP120) + factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

reddrum_forage <- gam(reddrumP915~ s(logreddrumP915forageP915) + s(logreddrumP915forageP120) + factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

reddrum_env_bc <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(logsmallbluecrabP120), family= tw(), data=df_CPUE_length_wide_both)

reddrum_env_forage <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(logreddrumP915forageP915+1) + s(logreddrumP915forageP120+1), family= tw(), data=df_CPUE_length_wide_both)

reddrum_env_bc_forage <- gam(reddrumP915~s(avgdepth)+s(avgssal)+s(avgstemp) + s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(logreddrumP915forageP120+1) + s(logreddrumP915forageP915+1) + s(logsmallbluecrabP120+1), family= tw(),  data=df_CPUE_length_wide_both)

AIC(reddrum_env, reddrum_bc, reddrum_forage, reddrum_env_bc, reddrum_env_forage, reddrum_env_bc_forage) %>% arrange(AIC)
```

##### Diagnostics
```{r}
summary(reddrum_env)
summary(reddrum_bc)
summary(reddrum_forage)
summary(reddrum_env_bc)
summary(reddrum_env_forage)
summary(reddrum_env_bc_forage)

#check p-value for anova across years 
anova(reddrum_env)
anova(reddrum_bc)
anova(reddrum_forage)
anova(reddrum_env_bc)
anova(reddrum_env_forage)
anova(reddrum_env_bc_forage)

gam.check(reddrum_env)
gam.check(reddrum_bc)
gam.check(reddrum_forage)
gam.check(reddrum_env_bc)
gam.check(reddrum_env_forage)
gam.check(reddrum_env_bc_forage)

vif(reddrum_env)
vif(reddrum_bc)
vif(reddrum_forage)
vif(reddrum_env_bc)
vif(reddrum_env_forage)
vif(reddrum_env_bc_forage)

cor(df_CPUE_length_wide_both %>% dplyr::select(avgdepth,avgssal, avgstemp, avgsdo, NoFishRest, reddrumP915forageP915, reddrumP915forageP120, smallbluecrabP120))

#Partial effect plots
plot(reddrum_env, shade= "true") 
plot(reddrum_bc, shade= "true") 
plot(reddrum_forage, shade= "true") 
plot(reddrum_env_bc, shade= "true") 
plot(reddrum_env_forage, shade= "true") 
plot(reddrum_env_bc_forage, shade= "true") 
```

#### Southern kingfish

##### Models

```{r}
southernkingfish_env <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_bc <- gam(southernkingfishP915~ s(logsmallbluecrabP120) + factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_forage <- gam(southernkingfishP915~ s(logsouthernkingfishP915forageP915) + s(logsouthernkingfishP915forageP120) + factor(Yearfactor), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_env_bc <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(logsmallbluecrabP120), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_env_forage <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp)+s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(logsouthernkingfishP915forageP915) + s(logsouthernkingfishP915forageP120), family= tw(), data=df_CPUE_length_wide_both)

southernkingfish_env_bc_forage <- gam(southernkingfishP915~s(avgdepth)+s(avgssal)+s(avgstemp) + s(avgsdo)+s(NoFishRest)+factor(Yearfactor) + s(logsouthernkingfishP915forageP120) + s(logsouthernkingfishP915forageP915) + s(logsmallbluecrabP120), family= tw(),  data=df_CPUE_length_wide_both)

AIC(southernkingfish_env, southernkingfish_bc, southernkingfish_forage, southernkingfish_env_bc, southernkingfish_env_forage, southernkingfish_env_bc_forage) %>% arrange(AIC)
```


