---
title: "CPUELengthFinal"
format: html
editor: visual
---

#### Load packages, functions, datasets

```{r}
packages <- c("ggplot2", "tidyverse", "lubridate", "sf", "sp", "dplyr", "rnaturalearth", "readr", "readxl", "spatialEco", "geosphere")
invisible(lapply(packages, library, character.only= TRUE))

standard_theme <- theme_bw() + theme(panel.border = element_rect(fill=NA, colour = "black")) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.text.align= 0, legend.title= element_text(size = 12), legend.text = element_text(size= 10), axis.text=element_text(size=10), axis.title=element_text(size=12))

#CPUEs 
p915_CPUE <- read_csv("/users/sallydowd/Desktop/Ch1Data/P915/p915_CPUE_new.csv")
setwd("~/Documents/GitHub/NCBlueCrab_Predators")
p120_CPUE <- read_csv("Data/P120/Finalized/p120_CPUE.csv") #98472 rows/14 species = 7053 unique sampling events 
p195_CPUE <- read_csv("Data/P195/Finalized/p195_CPUE.csv")

#Length 
p915_len_f <- read.csv("~/Desktop/Ch1Data/P915/p915_length_final.csv")
p915_len_f <- p915_len_f %>% dplyr::select(-X)
P120_bioledt <- read_csv("~/Desktop/Ch1Data/P120/p120_biol_new.csv")
P120_bioledt <- P120_bioledt %>% filter(Core==1|Core==2)
p195_lengthfreq <- read_csv("~/Documents/GitHub/NCBlueCrab_Predators/Data/P195/Finalized/p195_lengthfreq.csv")
```

#### Diagnostics

```{r}
#P915
length(unique(p915_len_f$Sample)) #13611
length(unique(p915_CPUE$Sample)) #13947
length(unique(p915_len_f$Control1)) #19910
length(unique(p915_CPUE$Control1)) #13947

#How many SampleIDs are the same between datasets? 
lets_look <- p915_len_f %>% dplyr::select(Speciescommonname, Colnum, Length, Sample) 
merged_df <- merge(p915_CPUE, lets_look, by = "Sample")
length(unique(merged_df$Sample)) #13611 same Samples, all samples in length dataset are in CPUE dataset 

#P120 
length(unique(P120_bioledt$Control1)) #9668
length(unique(p120_CPUE$Control1)) #7053
```

#### P915

##### Divide length

```{r}
#Species to divide up length for in Final length divisions
other_species <- p915_len_f %>% filter(Speciescommonname %in% c("atlantic croaker", "atlantic menhaden", "spot", "southern flounder")) %>% dplyr::select(Sample, Speciescommonname, Colnum, Length, Control2, Linenum) #Control2 depends on Control1 and replicate, replicate (1-8) corresponds to mesh size and aggregate count of each specis across mesh sizes, breaks out catch by mesh size

##Assign age class
other_species <- other_species %>% mutate(Age_class = ifelse(Speciescommonname %in% "atlantic menhaden" & Length <= 250, "S", ifelse(Speciescommonname %in% "atlantic croaker" & Length <= 173, "S", ifelse(Speciescommonname %in% "spot" & Length <= 134, "S", ifelse(Speciescommonname %in% "southern flounder" & Length <= 200, "S", "L")))))
               
##Count # of individuals in an age class for a mesh size, sum_count as # of individuals in both age classes 
other_species2 <- other_species %>% group_by(Sample, Colnum, Age_class, Control2, Speciescommonname) %>% summarize(count= n()) %>% ungroup() %>% group_by(Sample, Colnum, Control2, Speciescommonname) %>% mutate(sum_count= sum(count)) 

##Counted # of observations in each age class for a sample, computed a frequency, multiplied frequency by total Colnum
other_species2_freq <- other_species2 %>% group_by(Sample, Colnum, Control2, Speciescommonname) %>% mutate(Freq= count/sum_count) %>% ungroup() %>% mutate(Number= Freq*Colnum) 
other_species2_freq <- other_species2_freq %>% group_by(Sample, Age_class, Speciescommonname) %>% summarize(Num_sum = sum(Number))

##Make each Sample have small and large associated with it in CPUE file
length_samples <- unique(p915_len_f$Sample)
other_species_CPUE <- p915_CPUE %>% filter(Speciescommonname %in% c("atlantic menhaden", "atlantic croaker", "spot", "southern flounder")) %>% group_by(Sample) %>% slice(rep(1:n(), each = 2)) %>% mutate(Age_class = rep(c("S", "L"), length.out = n())) #n(): for each sample observation, duplicate each row for sample one with J and one with adult

##Join together CPUE and length-frequency analysis
combo <- other_species_CPUE %>% left_join(other_species2_freq, by= c("Sample", "Age_class", "Speciescommonname")) #add length to original CPUE dataset 

##Filter for true 0s only
combo %>% filter(! Sample %in% length_samples)
combo %>% filter(!Sample %in% length_samples & Colnum > 0) #Control1: 1119763, remove this 
#2,688 rows with SampleIDs present in CPUE and not in length, these are almost all where Colnum= 0 
#Only 4 rows with Colnum= 1 or 2, lengths weren't recorded even though species were present 
#These columns will become Colnum= 0 with line of code below 
#Need to remove samples that were not there in length dataset where Colnum > 0
combo2 <- combo %>% filter(!Control1 == 1119763) #removes 8 rows (S and L for 4 species for one Control1)

##Once you've established 0s are true, fill the NAs with 0
combo2$Num_sum[combo2$Num_sum %in% NA] <- 0 #dataset size of 334716 makes sense 
#once filtered CPUE dataset for species of interest, had 13946 Samples*4 species*2(S and L)= 111568, # of rows in combo

length(unique(other_species2_freq$Sample)) #12790 
length(unique(p915_CPUE$Sample)) #13947
#This code was used in Length.qmd as there were difference in Sample IDs b/w CPUE and length dataset- there isn't any here so we do have true 0s 
# unmerged_df <- anti_join(p915_CPUE, combo, by = "Sample")
# length(unique(unmerged_df$Sample)) #0 samples that aren't present in p915_len_f
# diff_samples <- unique(unmerged_df$Sample)
# off_samples <- combo %>% filter(Sample %in% diff_samples & Colnum > 0)
# off_samplesID <- unique(off_samples$Sample)
# combo2 <- combo %>% filter(!(Sample %in% off_samplesID)) #drops 132 rows
```

##### Verification

```{r}
check <- combo2 %>% group_by(Sample, Speciescommonname) %>% mutate(sum_count = sum(Num_sum)) %>% distinct(sum_count, .keep_all= TRUE) %>% dplyr::select(Sample, sum_count, Speciescommonname) %>% rename("Colnum"= "sum_count")
with <- p915_CPUE %>% filter(Speciescommonname %in% c("atlantic menhaden", "atlantic croaker", "southern flounder", "spot")) %>% dplyr::select(Sample, Colnum, Speciescommonname)
#0 differences in SampleID
differences <- anti_join(check, with, by = c("Sample")) 

#Check other differences
check$Sample <- trimws(check$Sample)
check$Speciescommonname <- trimws(check$Speciescommonname)
check$Colnum <- trimws(check$Colnum)
with$Sample <- trimws(with$Sample)
with$Speciescommonname <- trimws(with$Speciescommonname)
with$Colnum <- trimws(with$Colnum) #remove white space 

merged_df <- inner_join(check, with, by = c('Sample', "Speciescommonname"))
merged_df$Colnum.x <- gsub("\\s", "", merged_df$Colnum.x)
merged_df$Colnum.y <- gsub("\\s", "", merged_df$Colnum.y)
merged_df$Colnum_match <- merged_df$Colnum.x == merged_df$Colnum.y #there are a bunch of differences
merged_df <- merged_df %>% mutate(across(c(Colnum.x, Colnum.y), as.numeric))
merged_df$diff <- merged_df$Colnum.x - merged_df$Colnum.y
merged_df %>% filter(!diff == 0)

#Number of sampling events by Species with different values 
length_diff <- merged_df %>% group_by(Speciescommonname) %>% filter(!diff %in% 0) %>% summarize(count= n())
write.csv(length_diff, "~/Desktop/P915length_diff.csv")

#Magnitude of difference by species 
merged_df %>% group_by(Speciescommonname) %>% filter(!diff %in% 0) %>% ggplot() + geom_histogram(aes(x= diff)) + facet_wrap(~Speciescommonname)
merged_df %>% ungroup() %>% filter(!diff %in% 0) %>% distinct(Sample) %>% summarize(count= n()) 

#Mean difference for species
mean_diff <- merged_df %>% group_by(Speciescommonname) %>% filter(!diff %in% 0) %>% summarize(mean_diff= mean(diff))

#Percent error
perc_error <- merged_df %>% group_by(Speciescommonname) %>% summarize(percent_error= sum(diff != 0)/n()*100)
```

##### Final dataset

```{r}
#combo2 is length dataset only with species in length dataset, need to relabel species here as small and large
length(unique(combo2$Sample))
length(unique(combo2$Speciescommonname)) #4 species, 2 age classes, 13946 Samples, 4*2*13947= 111568, number of rows

combo2_edt <- combo2 %>% mutate(Speciescommonname = ifelse(Age_class == "S", paste("small", Speciescommonname), paste("large", Speciescommonname))) %>% dplyr::select(-c(Colnum, Age_class)) %>% rename("Colnum"= "Num_sum")

#Check to see if same # of Sample IDs for P915 and length dataset
p915_no_length <- p915_CPUE %>% filter(!Speciescommonname %in% other_species$Speciescommonname, !Control1 == 1119763) #Remove SampleID that was inconsistent from CPUE dataset

length(unique(p915_no_length$Sample)) #13946
length(unique(combo2_edt$Sample)) #13946
test <- rbind(p915_no_length, combo2_edt)

#Did this work? 
length(unique(test$Sample)) #13946
length(unique(test$Speciescommonname)) #41
#41*13946= 571786, # of rows in this dataset, one row for each sample for each species 

test$doy <- yday(test$Date)
test$Photoperiod <- daylength(lat= test$Latitude, doy= test$doy)
test$Season <- ifelse(test$Month==4 | test$Month==5 | test$Month==6, "Spring", ifelse(test$Month==9 |test$Month==10 | test$Month==11 | test$Month==12, "Fall", ifelse(test$Month==7 |test$Month==8, "Summer", "Winter")))
test$Ym_date <- format(test$Date, "%Y-%m")

p915_CPUE_length <- test 
write.csv(p915_CPUE_length, "/users/sallydowd/Desktop/Ch1Data/P915/p915_CPUE_length_multi.csv")
```

##### Vertification 2

```{r}
p915_CPUE_length_multi <- read.csv("/users/sallydowd/Desktop/Ch1Data/P915/p915_CPUE_length_multi.csv")
p915_CPUE <- read_csv("/users/sallydowd/Desktop/Ch1Data/P915/p915_CPUE_new.csv")

length_total <- p915_CPUE_length_multi %>% group_by(Speciescommonname) %>% summarize(total_count= sum(Colnum))
write.csv(length_total, "/users/sallydowd/Desktop/P915length_total.csv")
nonlength_total <- p915_CPUE %>% group_by(Speciescommonname) %>% summarize(total_count= sum(Colnum))
write.csv(nonlength_total, "/users/sallydowd/Desktop/P915nonlength_total.csv")
```


#### P120

##### Divide length
```{r}
#Deal with length 
P120_other_species <- P120_bioledt %>% filter(Speciescommonname %in% c( "atlantic croaker", "blue crab")) %>% dplyr::select(Control1, Date, Location, Colnum, Samnum, Subnum, Linenum, Frequenc, Length, Speciescommonname) %>% drop_na(Colnum, Length) #Length-frequency excel shows justification 

P120_other_species_edt <- P120_other_species %>% group_by(Control1, Colnum, Length, Speciescommonname) %>% uncount(weights=Frequenc, .remove= FALSE) %>% mutate(Frequenc_new = 1) #duplicates rows according to Frequency

#assign length 
P120_other_species_edt <- P120_other_species_edt %>% mutate(Age_class =  ifelse(Speciescommonname %in% "atlantic croaker" & Length <= 173, "J", ifelse(Speciescommonname %in% "blue crab" & Length <= 50, "J", "A")))

P120_os_prop <- P120_other_species_edt %>% group_by(Control1, Age_class, Colnum, Speciescommonname) %>% mutate(Count= n()) %>% distinct(Count, .keep_all= TRUE) %>% ungroup() %>% group_by(Control1, Colnum, Speciescommonname) %>% mutate(Total_sampled= sum(Count)) %>% ungroup() %>% mutate(Proportion= Count/Total_sampled) %>% dplyr::select(Control1, Date, Speciescommonname, Colnum, Age_class, Count, Total_sampled, Proportion) #don't need to group_by Date/Location/Station here as blue crabs weren't in the diff_values below after 2008

#Now apply proportion to Colnum 
P120_os_prop_edt <- P120_os_prop %>% mutate(Number= Colnum*Proportion) %>% group_by(Control1, Age_class, Speciescommonname) %>% mutate(Number_new = sum(Number)) %>% distinct(Number_new) #this is an important change: sometimes there were multiple Colnums for one sample, processed them differently but in the end added the numbers up from same age class 
#Don't need to group by date doesn't change dataset 

#Combine age class and Speciescommonname
P120_os_prop_edt2 <- P120_os_prop_edt %>% mutate(Speciescommonname = ifelse(Age_class == "J", paste("small", Speciescommonname), paste("large", Speciescommonname))) 

#Checking: this shows that we don't have one Control1 for each juvenile and adult of each species, does this still work? that's standard for this stage
length(unique(P120_os_prop$Control1)) #6931 in overall dataset 
length(unique(P120_os_prop_edt$Speciescommonname)) #4

#This data doesn't have juvenile and adult for each Control1 yet
```

##### Verification

```{r}
#Check if it worked
check <- P120_os_prop_edt %>% group_by(Control1, Speciescommonname) %>% mutate(sum_count = sum(Number_new)) %>% distinct(sum_count, .keep_all= TRUE) %>% select(Control1, sum_count, Speciescommonname) %>% rename("Colnum"= "sum_count") #combine adult and juvenile

unique(check$Speciescommonname)
with <- p120_CPUE %>% filter(Speciescommonname %in% c("atlantic croaker", "blue crab")) %>% select(Control1, Colnum, Speciescommonname)

check$Control1 <- trimws(check$Control1)
check$Speciescommonname <- trimws(check$Speciescommonname)
check$Colnum <- trimws(check$Colnum)
with$Control1 <- trimws(with$Control1)
with$Speciescommonname <- trimws(with$Speciescommonname)

merged_df <- inner_join(check, with, by = c('Control1', "Speciescommonname"))

merged_df$Colnum.x <- gsub("\\s", "", merged_df$Colnum.x)
merged_df$Colnum.y <- gsub("\\s", "", merged_df$Colnum.y)
merged_df$Colnum_match <- merged_df$Colnum.x == merged_df$Colnum.y #there are a bunch of differences
merged_df <- merged_df %>% mutate(across(c(Colnum.x, Colnum.y), as.numeric))
merged_df$diff <- merged_df$Colnum.x - merged_df$Colnum.y

#Number of sampling events by Species with different values 
length_diff <- merged_df %>% group_by(Speciescommonname) %>% filter(!diff %in% 0) %>% summarize(count= n())

#Magnitude of difference by species 
merged_df %>% group_by(Speciescommonname) %>% filter(!diff %in% 0) %>% ggplot() + geom_histogram(aes(x= diff)) + facet_wrap(~Speciescommonname)
merged_df %>% ungroup() %>% filter(!diff %in% 0) %>% distinct(Sample) %>% summarize(count= n())

#Mean difference for species
mean_diff <- merged_df %>% group_by(Speciescommonname) %>% filter(!diff %in% 0) %>% summarize(mean_diff= mean(diff))

#Percent error
perc_error <- merged_df %>% group_by(Speciescommonname) %>% summarize(percent_error= sum(diff != 0)/n()*100)
```

##### Final dataset
```{r}
#Create CPUE dataset with length data 
##These need to be species not in length dataset 
select_spp <- c("bay anchovy", "brown shrimp", "pink shrimp", "white shrimp", "pinfish", "silver perch", "striped anchovy", "weakfish",  "atlantic menhaden", "spotted seatrout", "spot", "southern flounder")

##Form a haul dataset where every row is one haul 
summary(is.na(P120_bioledt$Sciname)) #10 NAs for Sciname
P120_bioledt <- P120_bioledt %>% drop_na(Sciname)
P120_bioledt$Speciescommonname[P120_bioledt$Speciescommonname == "northern brown shrimp"] <- "brown shrimp"
haul <- P120_bioledt %>% group_by(Date, Location, Station, Control1) %>% mutate(ID=row_number()) %>% filter(ID==1) %>% as.data.frame() #row every haul: Dan suggested grouping by Date, Location, Control1 Station b/c location is waterbody at large and some stations have the same name (need Location), needed to exclude any non-core sampling, had to group by Control1, SPB1 was pulled twice on 11/9/2021
#this doesn't consider species, it's only haul  
length(unique(haul$Control1)) #7053
length(unique(P120_bioledt$Control1)) #7053

##Create dummy column for species of focus
haul$Species=NA #create a dummy column first
haul$Species=rep_along(haul$Species, c("bay anchovy", "brown shrimp", "pink shrimp", "white shrimp", "pinfish", "silver perch", "striped anchovy", "weakfish", "spot", "atlantic menhaden", "spotted seatrout", "small atlantic croaker", "large atlantic croaker", "small blue crab", "large blue crab", "southern flounder")) #this repeats these species common names for the entirety of the length of the haul df

haul_df <- haul %>% dplyr::select(Control1, Program, Year, Month, Day, Date, Location, Nbrrec3, Station, Time, Duration, Sedsize, Btmcomp, Sedsize_new, Btmcomp_new, Depth, Stemp, Btemp, Ssal, Bsal, Sdo, Bdo, Secchi, Latitude, Longitude, Core, Species)
haul_df_all <- haul_df %>% tidyr::expand(Species,Control1) ##using expand to make all species associated with each collection number, is 13x (# of species) larger so it worked
haul=haul_df %>% dplyr::select(-Species) #drop dummy species common name from hauldf

#now can merge haul.all and haul to create a df with a row for species associated with each collection number
haul_final=left_join(haul_df_all,haul,by="Control1")%>%as.data.frame() %>% rename("Speciescommonname"= "Species")
length(unique(haul_final$Species)) #15 species
length(unique(haul_final$Control1)) #7053 Control1, 15*7053= 105795 or # of rows 

#Factor in length 
sel_spp_120 <- P120_bioledt %>% filter(Speciescommonname %in% select_spp) %>% dplyr::select(Control1,Speciescommonname,Colnum) #select data for non-lengthed species
P120_os_prop_edt_tojoin <- P120_os_prop_edt2 %>% ungroup() %>% dplyr::select(Control1, Speciescommonname, Number_new) %>% rename("Colnum"= "Number_new") 
sel_spp_120join <- rbind(sel_spp_120, P120_os_prop_edt_tojoin)
sel_spp_120joinedt <- sel_spp_120join %>% group_by(Speciescommonname,Control1)%>% mutate(id=row_number()) %>% filter(id==1) %>%ungroup()%>%as.data.frame() 
#id should always be 1 for lengthed species b/c have distinct rows
#this is not the case for non-lengthed species, there are repeats of Colnum with Control1 and Speciescommonname b/c of length measurements

sel_spp_120joinedt = sel_spp_120joinedt %>% dplyr::select(-id)
haul_sel_spp <- left_join(haul_final, sel_spp_120joinedt, by= c("Speciescommonname", "Control1")) %>% as.data.frame() 

length(unique(haul_sel_spp$Speciescommonname))
length(unique(haul_sel_spp$Control1)) #it worked! df is 122848 rows, 7053 rows for each species (16 species)

haul_sel_spp$Colnum[haul_sel_spp$Colnum %in% NA] <- 0 #If there is an NA this is because there was no data there 

names_join <- P120_bioledt %>% select(Speciescommonname, Sciname) %>% distinct(Speciescommonname, .keep_all= T)
haul_sel_spp <- haul_sel_spp %>% left_join(names_join) %>% mutate(Sciname = ifelse(Speciescommonname == "brown shrimp", "F. aztecus", Sciname)) #brown shrimp went to NA for Sciname
haul_sel_spp$Sciname <- ifelse(haul_sel_spp$Speciescommonname %in% "small blue crab"|haul_sel_spp$Speciescommonname %in% "large blue crab", "C. sapidus", haul_sel_spp$Sciname)

haul_sel_spp$doy <- yday(haul_sel_spp$Date)
haul_sel_spp$Photoperiod <- daylength(lat= haul_sel_spp$Latitude, doy= haul_sel_spp$doy)
haul_sel_spp$Season <- ifelse(haul_sel_spp$Month==4 | haul_sel_spp$Month==5 | haul_sel_spp$Month==6, "Spring", ifelse(haul_sel_spp$Month==9 |haul_sel_spp$Month==10 | haul_sel_spp$Month==11 | haul_sel_spp$Month==12, "Fall", ifelse(haul_sel_spp$Month==7 |haul_sel_spp$Month==8, "Summer", "Winter")))
haul_sel_spp$Ym_date <- format(haul_sel_spp$Date, "%Y-%m")

write.csv(haul_sel_spp, "/Users/sallydowd/Documents/GitHub/NCBlueCrab_Predators/Data/P120/Finalized/p120_CPUE_length_multi.csv")
```

##### Verification #2
```{r}
setwd("/Users/sallydowd/Documents/GitHub/NCBlueCrab_Predators/Data/P120/Finalized")
p120_CPUE <- read_csv("p120_CPUE.csv")
p120_CPUE_length_multi <-read.csv("p120_CPUE_length_multi.csv")

##P120 multi length 
length_total <- p120_CPUE_length_multi %>% group_by(Speciescommonname) %>% summarize(total_count= sum(Colnum))
write.csv(length_total, "/users/sallydowd/Desktop/P120length_total_multi.csv")
nonlength_total <- p120_CPUE %>% group_by(Speciescommonname) %>% summarize(total_count= sum(Colnum))
write.csv(nonlength_total, "/users/sallydowd/Desktop/P120nonlength_total.csv")

###test with P120 CPUE
p120_CPUE_test <- p120_CPUE %>% filter(!Speciescommonname %in% "blue crab")
p120_CPUEBC_test <- p120_CPUE_lengthBC %>% filter(!Speciescommonname %in% "small blue crab", !Speciescommonname %in% "large blue crab") %>% select(any_of(colnames(p120_CPUE_test)))#datasets are same # of rows

library(arsenal)
summary(comparedf(p120_CPUE_test, p120_CPUEBC_test))
```

