---
title: "Length"
format: html
editor: visual
---

#### Load packages, functions, datasets

```{r}
packages <- c("ggplot2", "tidyverse", "lubridate", "sf", "sp", "dplyr", "rnaturalearth", "readr", "readxl", "spatialEco", "geosphere")
invisible(lapply(packages, library, character.only= TRUE))

standard_theme <- theme_bw() + theme(panel.border = element_rect(fill=NA, colour = "black")) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.text.align= 0, legend.title= element_text(size = 12), legend.text = element_text(size= 10), axis.text=element_text(size=10), axis.title=element_text(size=12))

#CPUEs 
p915_CPUE <- read_csv("/users/sallydowd/Desktop/Ch1Data/P915/p915_CPUE_new.csv")
setwd("~/Documents/GitHub/NCBlueCrab_Predators")
p120_CPUE <- read_csv("Data/P120/Finalized/p120_CPUE.csv") #98472 rows/14 species = 7053 unique sampling events 
p195_CPUE <- read_csv("Data/P195/Finalized/p195_CPUE.csv")

#Length 
p915_len_f <- read.csv("~/Desktop/Ch1Data/P915/p915_length_final.csv")
p915_len_f <- p915_len_f %>% dplyr::select(-X)
P120_bioledt <- read_csv("~/Desktop/Ch1Data/P120/p120_biol_new.csv")
P120_bioledt <- P120_bioledt %>% filter(Core==1|Core==2)
p195_lengthfreq <- read_csv("~/Documents/GitHub/NCBlueCrab_Predators/Data/P195/Finalized/p195_lengthfreq.csv")
```

#### P915

```{r}
#Diagnostics 
##Compare w/ CPUE dataset
length(unique(p915_len_f$Sample)) #13611
length(unique(p915_CPUE$Sample)) #13947
length(unique(p915_len_f$Control1)) #19910
length(unique(p915_CPUE$Control1)) #13947

combo <- p915_len_f %>% dplyr::select(Speciescommonname, Colnum, Length, Sample) 
# merged_df <- merge(p915_CPUE, combo, by = "Sample")
# length(unique(merged_df$Sample)) #13611 same Samples
unmerged_df <- anti_join(p915_CPUE, combo, by = "Sample")
length(unique(unmerged_df$Sample)) #336 of different ones that aren't present in p915_len_f
diff_samples <- unique(unmerged_df$Sample)
#sample_combo <- merged_df$Sample
yep <- p915_len_f %>% filter(!Sample %in% sample_combo)
```

##### Menhaden e.g.

```{r}
#Sub-sampled data
##Test with atlantic menhaden 
tryit2 <- p915_len_f %>% filter(Speciescommonname %in% "atlantic menhaden") %>% dplyr::select(Sample, Speciescommonname, Colnum, Length, Control2, Linenum)
tryit2$Age_class <- ifelse(tryit2$Length <= 250, "J", "A") #assign age class
test2 <- tryit2 %>% group_by(Sample, Colnum, Age_class, Control2) %>% summarize(count= n()) %>% ungroup() %>% group_by(Sample, Colnum, Control2) %>% mutate(sum_count= sum(count))
test2_freq <- test2 %>% group_by(Sample, Colnum, Control2) %>% mutate(Freq= count/sum_count) %>% ungroup() %>% mutate(Number= Freq*Colnum) #counted # of observations in each age class for a sample, computed a frequency, multiplied frequency by total Colnum
test2_edt <- test2_freq %>% group_by(Sample, Age_class) %>% summarize(Num_sum = sum(Number)) #sum number of individuals in each age class, 10797 samples 

length_test <- p915_CPUE %>% filter(Speciescommonname %in% "atlantic menhaden") %>% group_by(Sample) %>% slice(rep(1:n(), each = 2)) %>% mutate(Age_class = rep(c("J", "A"), length.out = n())) #n(): for each sample observation, duplicate each row for sample one with J and one with adult
combo <- length_test %>% filter(Speciescommonname %in% "atlantic menhaden") %>% left_join(test2_edt, by= c("Sample", "Age_class"))
combo$Num_sum[combo$Num_sum %in% NA] <- 0

#Check if worked: 
##Joining 
sel_to_combo <- combo %>% filter(!Num_sum %in% NA) #10797 samples with no NA, the joining worked
length(unique(sel_to_combo$Sample))

##Create length CPUE
check <- combo %>% group_by(Sample) %>% mutate(sum_count = sum(Num_sum)) %>% distinct(sum_count, .keep_all= TRUE) %>% select(Sample, sum_count) %>% rename("Colnum"= "sum_count")
# check$Colnum <- format(check$Colnum, nsmall = 0)
with <- p915_CPUE %>% filter(Speciescommonname %in% "atlantic menhaden") %>% select(Sample, Colnum)
differences <- anti_join(check, with, by = "Sample") #0, same samples 
#unique(differences$Speciescommonname) 

combo %>% filter(Sample %in% "17117NEUSE2260.")
test2_edt %>% filter(Sample %in% "17117NEUSE2260.")
t2 <- p915_CPUE %>% filter(Sample %in% "17117NEUSE2260.", Speciescommonname %in% "atlantic menhaden")
write.csv(t2, "~/Desktop/p915_CPUE.csv")
t <- p915_len_f %>% filter(Speciescommonname %in% "atlantic menhaden", Sample %in% "17117NEUSE2260.")
write.csv(t, "~/Desktop/p915_len_f.csv")
merged_df <- inner_join(check, with, by = 'Sample')
merged_df$Colnum.x <- gsub("\\s", "", merged_df$Colnum.x)
merged_df$Colnum.y <- gsub("\\s", "", merged_df$Colnum.y)
merged_df$Colnum_match <- merged_df$Colnum.x == merged_df$Colnum.y #there are a bunch of differences
merged_df <- merged_df %>% mutate(across(c(Colnum.x, Colnum.y), as.numeric))
merged_df$diff <- merged_df$Colnum.x - merged_df$Colnum.y #300 out of 13,947 with differences, ranging from 
ggplot() + geom_histogram(data= merged_df, aes(x= diff)) + standard_theme
```

```{r}
#Form menhaden dataset 
menhaden <- p915_len_f %>% filter(Speciescommonname %in% "atlantic menhaden") %>% dplyr::select(Sample, Speciescommonname, Colnum, Length, Control2, Linenum)
##Assign age class
menhaden$Age_class <- ifelse(menhaden$Length <= 250, "J", "A") 
##Count # of individuals in an age class for a mesh size, sum_count as # of individuals in both age classes 
menhaden2 <- menhaden %>% group_by(Sample, Colnum, Age_class, Control2) %>% summarize(count= n()) %>% ungroup() %>% group_by(Sample, Colnum, Control2) %>% mutate(sum_count= sum(count))

##Counted # of observations in each age class for a sample, computed a frequency, multiplied frequency by total Colnum
menhaden2_freq <- menhaden2 %>% group_by(Sample, Colnum, Control2) %>% mutate(Freq= count/sum_count) %>% ungroup() %>% mutate(Number= Freq*Colnum) 
menhaden2_freq <- menhaden2_freq %>% group_by(Sample, Age_class) %>% summarize(Num_sum = sum(Number)) #sum number of individuals in each age class, 10797 samples 

##Make each Sample have juvenile and adult associated with it in CPUE file
length_samples <- unique(p915_len_f$Sample)
mehnaden_CPUE <- p915_CPUE %>% filter(Speciescommonname %in% "atlantic menhaden") %>% group_by(Sample) %>% slice(rep(1:n(), each = 2)) %>% mutate(Age_class = rep(c("J", "A"), length.out = n())) #n(): for each sample observation, duplicate each row for sample one with J and one with adult
combo <- mehnaden_CPUE %>% filter(Speciescommonname %in% "atlantic menhaden") %>% left_join(menhaden2_freq, by= c("Sample", "Age_class")) %>% filter(Sample %in% length_samples) #27894 --> 27222 when sample (drops 672 rows)
combo$Num_sum[combo$Num_sum %in% NA] <- 0
```

##### Divide length

```{r}
#Non-subsampled data
other_species <- p915_len_f %>% filter(Speciescommonname %in% c("atlantic croaker", "black drum", "bonnethead shark", "red drum", "sheepshead", "southern flounder", "southern kingfish", "spot", "spotted seatrout", "striped bass", "striped mullet", "atlantic menhaden")) %>% dplyr::select(Sample, Speciescommonname, Colnum, Length, Control2, Linenum) #Control2

##Assign age class
other_species <- other_species %>% mutate(Age_class = ifelse(Speciescommonname %in% "atlantic menhaden" & Length <= 250, "J", ifelse(Speciescommonname %in% "atlantic croaker" & Length <= 173, "J", ifelse(Speciescommonname %in% "black drum" & Length <= 350, "J", ifelse(Speciescommonname %in% "red drum" & Length <= 400, "J", ifelse(Speciescommonname %in% "sheepshead" & Length <= 250, "J", ifelse(Speciescommonname %in% "southern flounder" & Length <= 345.44, "J", ifelse(Speciescommonname %in% "southern kingfish" & Length <= 177, "J", ifelse(Speciescommonname %in% "spot" & Length <= 203.2, "J", ifelse(Speciescommonname %in% "spotted seatrout" & Length <= 260.8, "J", ifelse(Speciescommonname %in% "striped bass" & Length <= 500, "J", ifelse(Speciescommonname %in% "striped mullet" & Length <= 380, "J", "A"))))))))))))
                                
##Count # of individuals in an age class for a mesh size, sum_count as # of individuals in both age classes 
other_species2 <- other_species %>% group_by(Sample, Colnum, Age_class, Control2, Speciescommonname) %>% summarize(count= n()) %>% ungroup() %>% group_by(Sample, Colnum, Control2, Speciescommonname) %>% mutate(sum_count= sum(count)) 

##Counted # of observations in each age class for a sample, computed a frequency, multiplied frequency by total Colnum
other_species2_freq <- other_species2 %>% group_by(Sample, Colnum, Control2, Speciescommonname) %>% mutate(Freq= count/sum_count) %>% ungroup() %>% mutate(Number= Freq*Colnum) 
other_species2_freq <- other_species2_freq %>% group_by(Sample, Age_class, Speciescommonname) %>% summarize(Num_sum = sum(Number)) #sum number of individuals in each age class, 10797 samples 

##Make each Sample have juvenile and adult associated with it in CPUE file
length_samples <- unique(p915_len_f$Sample)
other_species_CPUE <- p915_CPUE %>% filter(Speciescommonname %in% c("atlantic menhaden", "atlantic croaker", "black drum", "red drum", "sheepshead", "southern flounder", "southern kingfish", "spot", "spotted seatrout", "striped bass", "striped mullet")) %>% group_by(Sample) %>% slice(rep(1:n(), each = 2)) %>% mutate(Age_class = rep(c("J", "A"), length.out = n())) #n(): for each sample observation, duplicate each row for sample one with J and one with adult

##Join together CPUE and length-frequency analysis
combo <- other_species_CPUE %>% left_join(other_species2_freq, by= c("Sample", "Age_class", "Speciescommonname"))

##Filter for true 0s only
combo %>% filter(! Sample %in% length_samples)
#7,392 rows with missing Sample IDs for length data, most of these are where Colnum= 0 (8052)
combo %>% filter(!Sample %in% length_samples & Colnum > 0)
#12 rows with Colnum = 1 or 2 
#Only remove Samples that wasn't there in length dataset has Colnum > 0, need to remove these for all species, assign everything

unmerged_df <- anti_join(p915_CPUE, combo, by = "Sample")
length(unique(unmerged_df$Sample)) #336 of different ones that aren't present in p915_len_f
diff_samples <- unique(unmerged_df$Sample)
off_samples <- combo %>% filter(Sample %in% diff_samples & Colnum > 0)
off_samplesID <- unique(off_samples$Sample)
combo2 <- combo %>% filter(!(Sample %in% off_samplesID)) #drops 132 rows 

##Once you've established 0s are true, fill the NAs with 0
combo2$Num_sum[combo2$Num_sum %in% NA] <- 0 #dataset size of 334716 makes sense 
#once filtered CPUE dataset for species of interest, had 167363 observations, *2 (A and J) to get 334728, 334728- 334716= 12, removed 12 rows
```

##### Verification

```{r}
#Check if it worked
check <- combo2 %>% group_by(Sample, Speciescommonname) %>% mutate(sum_count = sum(Num_sum)) %>% distinct(sum_count, .keep_all= TRUE) %>% select(Sample, sum_count, Speciescommonname) %>% rename("Colnum"= "sum_count")
with <- p915_CPUE %>% filter(Speciescommonname %in% c("atlantic menhaden", "atlantic croaker", "black drum", "red drum", "sheepshead", "southern flounder", "southern kingfish", "spot", "spotted seatrout", "striped bass", "striped mullet")) %>% select(Sample, Colnum, Speciescommonname)
differences <- anti_join(check, with, by = c("Sample")) #0 differences in Sample (same samples), this is b/c you joined datasets and dealt w/ different samples already

check$Sample <- trimws(check$Sample)
check$Speciescommonname <- trimws(check$Speciescommonname)
check$Colnum <- trimws(check$Colnum)
with$Sample <- trimws(with$Sample)
with$Speciescommonname <- trimws(with$Speciescommonname)
with$Colnum <- trimws(with$Colnum) #remove white space 

merged_df <- inner_join(check, with, by = c('Sample', "Speciescommonname"))
merged_df$Colnum.x <- gsub("\\s", "", merged_df$Colnum.x)
merged_df$Colnum.y <- gsub("\\s", "", merged_df$Colnum.y)
merged_df$Colnum_match <- merged_df$Colnum.x == merged_df$Colnum.y #there are a bunch of differences
merged_df <- merged_df %>% mutate(across(c(Colnum.x, Colnum.y), as.numeric))
merged_df$diff <- merged_df$Colnum.x - merged_df$Colnum.y

#Number of sampling events by Species with different values 
length_diff <- merged_df %>% group_by(Speciescommonname) %>% filter(!diff %in% 0) %>% summarize(count= n())
write.csv(length_diff, "~/Desktop/length_diff.csv")

#Magnitude of difference by species 
merged_df %>% group_by(Speciescommonname) %>% filter(!diff %in% 0) %>% ggplot() + geom_histogram(aes(x= diff)) + facet_wrap(~Speciescommonname)
merged_df %>% ungroup() %>% filter(!diff %in% 0) %>% distinct(Sample) %>% summarize(count= n())

#Mean difference for species
mean_diff <- merged_df %>% group_by(Speciescommonname) %>% filter(!diff %in% 0) %>% summarize(mean_diff= mean(diff))

#Percent error
perc_error <- merged_df %>% group_by(Speciescommonname) %>% summarize(percent_error= sum(diff != 0)/n()*100)
```

##### Final dataset formation

```{r}
#combo2 is length dataset only with species in length dataset, need to relabel species here as juvenile and adult 
length(unique(combo2$Sample))
length(unique(combo2$Speciescommonname)) #11 species, 2 age classes, 13947 Samples, 11*2*13947= 306834, number of rows

combo2_edt <- combo2 %>% mutate(Speciescommonname = ifelse(Age_class == "J", paste("small", Speciescommonname), paste("large", Speciescommonname))) %>% dplyr::select(-c(Colnum, Age_class)) %>% rename("Colnum"= "Num_sum")

#Check to see if same # of Sample IDs for P915 and length dataset
p915_no_length <- p915_CPUE %>% filter(!Speciescommonname %in% other_species, !Sample %in% off_samplesID) #remove those Sample IDs that were not true 0s, didn't drop rows here

length(unique(p915_no_length$Sample)) #13947
length(unique(combo2_edt$Sample)) #13947   
test <- rbind(p915_no_length, combo2_edt)

#Did this work? 
length(unique(test$Sample)) #13947
length(unique(test$Speciescommonname)) #59
#59*13941= 822873, # of rows in this dataset, one row for each sample for each species 

test$doy <- yday(test$Date)
test$Photoperiod <- daylength(lat= test$Latitude, doy= test$doy)
test$Season <- ifelse(test$Month==4 | test$Month==5 | test$Month==6, "Spring", ifelse(test$Month==9 |test$Month==10 | test$Month==11 | test$Month==12, "Fall", ifelse(test$Month==7 |test$Month==8, "Summer", "Winter")))
test$Ym_date <- format(test$Date, "%Y-%m")

p915_CPUE_length <- test 
write.csv(p915_CPUE_length, "/users/sallydowd/Desktop/Ch1Data/P915/p915_CPUE_length.csv")
```

```{r}
#Exploratory figures
sum_num <- combo2_edt %>% group_by(Speciescommonname) %>% filter(!Colnum %in% 0) %>% summarize(total= round(sum(Colnum),2), mean= round(mean(Colnum),2))
write.csv(sum_num, "/Users/sallydowd/Desktop/sum_numP915.csv")
```

##### Justification figures

```{r}
other_species <- p915_len_f %>% filter(Speciescommonname %in% c("atlantic croaker", "black drum", "red drum", "sheepshead", "southern flounder", "southern kingfish", "spot", "spotted seatrout", "striped bass", "striped mullet", "atlantic menhaden")) %>% dplyr::select(Sample, Speciescommonname, Colnum, Length, Control2, Linenum)

##Count # of individuals of a species a mesh size
other_species2 <- other_species %>% group_by(Sample, Colnum, Control2, Speciescommonname) %>% summarize(count= n()) %>% distinct(count, .keep_all= TRUE)

##Counted # of observations in each age class for a sample, computed a frequency, multiplied frequency by total Colnum
other_species2_freq <- other_species2 %>% group_by(Sample, Colnum, Control2, Speciescommonname) %>% mutate(Freq= count/sum_count) %>% ungroup() %>% mutate(Number= Freq*Colnum) 
other_species2_freq <- other_species2_freq %>% group_by(Sample, Age_class, Speciescommonname) %>% summarize(Num_sum = sum(Number)) #sum number of individuals in each age class, 10797 samples 
```

### P120

```{r}
#Diagnostics 
##Compare w/ CPUE dataset: differences b/c of cores and years, fine with this 
length(unique(P120_bioledt$Control1)) #9668
length(unique(p120_CPUE$Control1)) #7053

P120_bioledt$Control1 <- trimws(P120_bioledt$Control1)
p120_CPUE$Control1 <- trimws(p120_CPUE$Control1)

combo <- P120_bioledt %>% dplyr::select(Speciescommonname, Colnum, Length, Control1) 
merged_df <- merge(p120_CPUE, combo, by = "Control1")

uniq_control1 <- merged_df$Control1
#Look at samples not in length dataset
look <- P120_bioledt %>% filter(!Control1 %in% uniq_control1)
```

##### Blue crab e.g.

```{r}
#Form blue crab dataset and make sure each blue crab in the subsample has their own row
P120_bc <- P120_bioledt %>% filter(Speciescommonname %in% "blue crab") %>% dplyr::select(Control1, Date, Location, Colnum, Samnum, Subnum, Linenum, Frequenc, Length, Speciescommonname) %>% drop_na(Colnum, Length)
P120_bc_edt <- P120_bc %>% group_by(Control1, Colnum, Length) %>% uncount(weights=Frequenc, .remove= FALSE) %>% mutate(Frequenc_new = 1) #duplicates rows according to Frequency 
#Bin length: define the breaks for the intervals
values <- 1:300
breaks <- seq(0, 300, by = 10)
assigned_values <- seq(10, 300, by = 10)
result <- cut(values, breaks, labels = assigned_values) #cut values based on cut points (breaks), labels for resulting category, default is (a, b)
result_numeric <- as.numeric(as.character(result))
df <- data.frame(Length = values, Assigned_length = result_numeric)

#Calculate proportion of juveniles and adults in each Eventname
P120_bc_prop <- P120_bc_edt %>% left_join(df, by= "Length")
P120_bc_prop$Age_class <- ifelse(P120_bc_prop$Assigned_length < 50, "J", "A") #assign juvenile if under 50 mm, 50.8 mm (2 inches) is harvestable length, blue crabs should reach this length in ~1 year when they become sexually mature
P120_bc_prop <- P120_bc_prop %>% group_by(Control1, Age_class, Colnum) %>% mutate(Count= n()) %>% distinct(Count, .keep_all= TRUE) %>% ungroup() %>% group_by(Control1, Colnum) %>% mutate(Total_sampled= sum(Count)) %>% ungroup() %>% mutate(Proportion= Count/Total_sampled) %>% dplyr::select(Control1, Date, Speciescommonname, Colnum, Age_class, Count, Total_sampled, Proportion) #don't need to group_by Date/Location/Station here as blue crabs weren't in the diff_values below after 2008

#Now apply proportion to Colnum 
P120_bc_prop <- P120_bc_prop %>% mutate(Number= round(Colnum*Proportion,0)) %>% group_by(Control1, Age_class) %>% mutate(Number_new = sum(Number)) %>% distinct(Number_new) #this is an important change: sometimes there were multiple Colnums for one sample, processed them differently but in the end added the numbers up from same age class 
P120_bc_prop$Number_new[P120_bc_prop$Number_new==0] <- 0.5 #Will have to check over this move, want it to be sampled but 
```

##### All species

```{r}
#Deal with length 
P120_other_species <- P120_bioledt %>% filter(Speciescommonname %in% c("atlantic menhaden", "atlantic croaker", "blue crab", "southern flounder", "spot", "spotted seatrout")) %>% dplyr::select(Control1, Date, Location, Colnum, Samnum, Subnum, Linenum, Frequenc, Length, Speciescommonname) %>% drop_na(Colnum, Length) #Length-frequency excel shows justification 

P120_other_species_edt <- P120_other_species %>% group_by(Control1, Colnum, Length, Speciescommonname) %>% uncount(weights=Frequenc, .remove= FALSE) %>% mutate(Frequenc_new = 1) #duplicates rows according to Frequency

#assign length 
P120_other_species_edt <- P120_other_species_edt %>% mutate(Age_class = ifelse(Speciescommonname %in% "atlantic menhaden" & Length <= 250, "J", ifelse(Speciescommonname %in% "atlantic croaker" & Length <= 173, "J", ifelse(Speciescommonname %in% "blue crab" & Length <= 50, "J", ifelse(Speciescommonname %in% "southern flounder" & Length <= 345.44, "J", ifelse(Speciescommonname %in% "spot" & Length <= 203.2, "J", ifelse(Speciescommonname %in% "spotted seatrout" & Length <= 260.8, "J", "A")))))))

P120_os_prop <- P120_other_species_edt %>% group_by(Control1, Age_class, Colnum, Speciescommonname) %>% mutate(Count= n()) %>% distinct(Count, .keep_all= TRUE) %>% ungroup() %>% group_by(Control1, Colnum, Speciescommonname) %>% mutate(Total_sampled= sum(Count)) %>% ungroup() %>% mutate(Proportion= Count/Total_sampled) %>% dplyr::select(Control1, Date, Speciescommonname, Colnum, Age_class, Count, Total_sampled, Proportion) #don't need to group_by Date/Location/Station here as blue crabs weren't in the diff_values below after 2008

#Now apply proportion to Colnum 
P120_os_prop_edt <- P120_os_prop %>% mutate(Number= Colnum*Proportion) %>% group_by(Control1, Age_class, Speciescommonname) %>% mutate(Number_new = sum(Number)) %>% distinct(Number_new) #this is an important change: sometimes there were multiple Colnums for one sample, processed them differently but in the end added the numbers up from same age class 
#Don't need to group by date doesn't change dataset 

#Combine age class and Speciescommonname
P120_os_prop_edt2 <- P120_os_prop_edt %>% mutate(Speciescommonname = ifelse(Age_class == "J", paste("small", Speciescommonname), paste("large", Speciescommonname))) 

#Checking: this shows that we don't have one Control1 for each juvenile and adult of each species, does this still work?
length(unique(P120_os_prop$Control1)) #6935/7053 in overall dataset 
length(unique(P120_os_prop_edt2$Speciescommonname)) #12
#12*9364 doesn't equal number of rows, haven't labeled J and A yet, haven't created one row for each sampling event for a species and an age class

#You have catch data for length for six species
#This data doesn't have juvenile and adult for each Control1 
```

##### Verification

```{r}
#Check if it worked
check <- P120_os_prop_edt %>% group_by(Control1, Speciescommonname) %>% mutate(sum_count = sum(Number_new)) %>% distinct(sum_count, .keep_all= TRUE) %>% select(Control1, sum_count, Speciescommonname) %>% rename("Colnum"= "sum_count") #combine adult and juvenile

unique(check$Speciescommonname)
with <- p120_CPUE %>% filter(Speciescommonname %in% c("atlantic menhaden", "atlantic croaker", "blue crab", "spot", "spotted seatrout", "southern flounder")) %>% select(Control1, Colnum, Speciescommonname)

check$Control1 <- trimws(check$Control1)
check$Speciescommonname <- trimws(check$Speciescommonname)
check$Colnum <- trimws(check$Colnum)
with$Control1 <- trimws(with$Control1)
with$Speciescommonname <- trimws(with$Speciescommonname)

merged_df <- inner_join(check, with, by = c('Control1', "Speciescommonname"))

merged_df$Colnum.x <- gsub("\\s", "", merged_df$Colnum.x)
merged_df$Colnum.y <- gsub("\\s", "", merged_df$Colnum.y)
merged_df$Colnum_match <- merged_df$Colnum.x == merged_df$Colnum.y #there are a bunch of differences
merged_df <- merged_df %>% mutate(across(c(Colnum.x, Colnum.y), as.numeric))
merged_df$diff <- merged_df$Colnum.x - merged_df$Colnum.y

#Number of sampling events by Species with different values 
length_diff <- merged_df %>% group_by(Speciescommonname) %>% filter(!diff %in% 0) %>% summarize(count= n())

#Magnitude of difference by species 
merged_df %>% group_by(Speciescommonname) %>% filter(!diff %in% 0) %>% ggplot() + geom_histogram(aes(x= diff)) + facet_wrap(~Speciescommonname)
merged_df %>% ungroup() %>% filter(!diff %in% 0) %>% distinct(Sample) %>% summarize(count= n())

#Mean difference for species
mean_diff <- merged_df %>% group_by(Speciescommonname) %>% filter(!diff %in% 0) %>% summarize(mean_diff= mean(diff))

#Percent error
perc_error <- merged_df %>% group_by(Speciescommonname) %>% summarize(percent_error= sum(diff != 0)/n()*100)
```

##### Final dataset

```{r}
#Create CPUE dataset with length data 
##These need to be species not in length dataset 
select_spp <- c("bay anchovy", "brown shrimp", "pink shrimp", "white shrimp", "pinfish", "silver perch", "striped anchovy", "weakfish", "spot")

##Form a haul dataset where every row is one haul 
summary(is.na(P120_bioledt$Sciname)) #10 NAs for Sciname
P120_bioledt <- P120_bioledt %>% drop_na(Sciname)
P120_bioledt$Speciescommonname[P120_bioledt$Speciescommonname == "northern brown shrimp"] <- "brown shrimp"
haul <- P120_bioledt %>% group_by(Date, Location, Station, Control1) %>% mutate(ID=row_number()) %>% filter(ID==1) %>% as.data.frame() #row every haul: Dan suggested grouping by Date, Location, Control1 Station b/c location is waterbody at large and some stations have the same name (need Location), needed to exclude any non-core sampling, had to group by Control1, SPB1 was pulled twice on 11/9/2021
#this doesn't consider species, it's only haul  
length(unique(haul$Control1)) #7053
length(unique(P120_bioledt$Control1)) #7053

##Create dummy column for species of focus
haul$Species=NA #create a dummy column first
haul$Species=rep_along(haul$Species, c("bay anchovy", "brown shrimp", "pink shrimp", "white shrimp", "pinfish", "silver perch", "striped anchovy", "weakfish", "small atlantic menhaden", "large atlantic menhaden", "small atlantic croaker", "large atlantic croaker", "small blue crab", "large blue crab", "small southern flounder", "large southern flounder", "small spotted seatrout", "juvenile spotted seatrout", "spot")) #this repeats these species common names for the entirety of the length of the haul df
haul_df <- haul %>% dplyr::select(Control1, Program, Year, Month, Day, Date, Location, Nbrrec3, Station, Time, Duration, Sedsize, Btmcomp, Sedsize_new, Btmcomp_new, Depth, Stemp, Btemp, Ssal, Bsal, Sdo, Bdo, Secchi, Latitude, Longitude, Core, Species)
haul_df_all <- haul_df %>% tidyr::expand(Species,Control1) ##using expand to make all species associated with each collection number, is 13x (# of species) larger so it worked
haul=haul_df %>% dplyr::select(-Species) #drop dummy species common name from hauldf

#now can merge haul.all and haul to create a df with a row for species associated with each collection number
haul_final=left_join(haul_df_all,haul,by="Control1")%>%as.data.frame() %>% rename("Speciescommonname"= "Species")
length(unique(haul_final$Species)) #19 species
length(unique(haul_final$Control1)) #9641 Control1, 19*9641= 183179 or # of rows 

#Factor in length 
sel_spp_120 <- P120_bioledt %>% filter(Speciescommonname %in% select_spp) %>% dplyr::select(Control1,Speciescommonname,Colnum) #select data for non-lengthed species
P120_os_prop_edt_tojoin <- P120_os_prop_edt2 %>% ungroup() %>% dplyr::select(Control1, Speciescommonname, Number_new) %>% rename("Colnum"= "Number_new") #already removed spot as had 9% error rate and all same size 
sel_spp_120join <- rbind(sel_spp_120, P120_os_prop_edt_tojoin)
sel_spp_120joinedt <- sel_spp_120join %>% group_by(Speciescommonname,Control1)%>% mutate(id=row_number()) %>% filter(id==1) %>%ungroup()%>%as.data.frame() 
#id should always be 1 for lengthed species b/c have distinct rows
#this is not the case for non-lengthed species, there are repeats of Colnum with Control1 and Speciescommonname b/c of length measurements

sel_spp_120joinedt = sel_spp_120joinedt %>% dplyr::select(-id)
haul_sel_spp <- left_join(haul_final, sel_spp_120joinedt, by= c("Speciescommonname", "Control1")) %>% as.data.frame() 

length(unique(haul_sel_spp$Speciescommonname))
length(unique(haul_sel_spp$Control1)) #it worked! df is 183179 rows, 9641 rows for each species (19 species)

haul_sel_spp$Colnum[haul_sel_spp$Colnum %in% NA] <- 0 #If there is an NA this is because there was no data there 

haul_sel_spp$doy <- yday(haul_sel_spp$Date)
haul_sel_spp$Photoperiod <- daylength(lat= haul_sel_spp$Latitude, doy= haul_sel_spp$doy)
haul_sel_spp$Season <- ifelse(haul_sel_spp$Month==4 | haul_sel_spp$Month==5 | haul_sel_spp$Month==6, "Spring", ifelse(haul_sel_spp$Month==9 |haul_sel_spp$Month==10 | haul_sel_spp$Month==11 | haul_sel_spp$Month==12, "Fall", ifelse(haul_sel_spp$Month==7 |haul_sel_spp$Month==8, "Summer", "Winter")))
haul_sel_spp$Ym_date <- format(haul_sel_spp$Date, "%Y-%m")

write.csv(haul_sel_spp, "/Users/sallydowd/Documents/GitHub/NCBlueCrab_Predators/Data/P120/Finalized/p120_CPUE_length.csv")
```

```{r}
#Explaratory figures 
sum_num <- p120_CPUE %>% group_by(Speciescommonname) %>% filter(!Colnum %in% 0) %>% summarize(total= round(sum(Colnum),2), mean= round(mean(Colnum),2))
write.csv(sum_num, "/Users/sallydowd/Desktop/sum_numP120.csv")
```

##### Blue crab only
```{r}
#Deal with length 
P120_other_species <- P120_bioledt %>% filter(Speciescommonname %in% "blue crab") %>% dplyr::select(Control1, Date, Location, Colnum, Samnum, Subnum, Linenum, Frequenc, Length, Speciescommonname) %>% drop_na(Colnum, Length) #Length-frequency excel shows justification 

P120_other_species_edt <- P120_other_species %>% group_by(Control1, Colnum, Length, Speciescommonname) %>% uncount(weights=Frequenc, .remove= FALSE) %>% mutate(Frequenc_new = 1) #duplicates rows according to Frequency

#assign length 
P120_other_species_edt <- P120_other_species_edt %>% mutate(Age_class = ifelse(Speciescommonname %in% "blue crab" & Length <= 75, "J", "A"))

P120_os_prop <- P120_other_species_edt %>% group_by(Control1, Age_class, Colnum, Speciescommonname) %>% mutate(Count= n()) %>% distinct(Count, .keep_all= TRUE) %>% ungroup() %>% group_by(Control1, Colnum, Speciescommonname) %>% mutate(Total_sampled= sum(Count)) %>% ungroup() %>% mutate(Proportion= Count/Total_sampled) %>% dplyr::select(Control1, Date, Speciescommonname, Colnum, Age_class, Count, Total_sampled, Proportion) #don't need to group_by Date/Location/Station here as blue crabs weren't in the diff_values below after 2008

#Now apply proportion to Colnum 
P120_os_prop_edt <- P120_os_prop %>% mutate(Number= Colnum*Proportion) %>% group_by(Control1, Age_class, Speciescommonname) %>% mutate(Number_new = sum(Number)) %>% distinct(Number_new) #this is an important change: sometimes there were multiple Colnums for one sample, processed them differently but in the end added the numbers up from same age class 
#Don't need to group by date doesn't change dataset 

#Combine age class and Speciescommonname
P120_os_prop_edt2 <- P120_os_prop_edt %>% mutate(Speciescommonname = ifelse(Age_class == "J", paste("small", Speciescommonname), paste("large", Speciescommonname))) 

#Checking: this shows that we don't have one Control1 for each juvenile and adult of each species, does this still work? that's standard for this stage
length(unique(P120_os_prop$Control1)) #4908 in overall dataset 
length(unique(P120_os_prop_edt$Speciescommonname)) #2

#This data doesn't have juvenile and adult for each Control1 
```

```{r}
#Create CPUE dataset with length data 
##These need to be species not in length dataset 
select_spp <- c("bay anchovy", "brown shrimp", "pink shrimp", "white shrimp", "pinfish", "silver perch", "striped anchovy", "weakfish", "spot", "atlantic menhaden", "atlantic croaker", "southern flounder", "spot", "spotted seatrout")

##Form a haul dataset where every row is one haul 
summary(is.na(P120_bioledt$Sciname)) #10 NAs for Sciname
P120_bioledt <- P120_bioledt %>% drop_na(Sciname)
P120_bioledt$Speciescommonname[P120_bioledt$Speciescommonname == "northern brown shrimp"] <- "brown shrimp"
haul <- P120_bioledt %>% group_by(Date, Location, Station, Control1) %>% mutate(ID=row_number()) %>% filter(ID==1) %>% as.data.frame() #row every haul: Dan suggested grouping by Date, Location, Control1 Station b/c location is waterbody at large and some stations have the same name (need Location), needed to exclude any non-core sampling, had to group by Control1, SPB1 was pulled twice on 11/9/2021
#this doesn't consider species, it's only haul  
length(unique(haul$Control1)) #7053
length(unique(P120_bioledt$Control1)) #7053

##Create dummy column for species of focus
haul$Species=NA #create a dummy column first
haul$Species=rep_along(haul$Species, c("bay anchovy", "brown shrimp", "pink shrimp", "white shrimp", "pinfish", "silver perch", "striped anchovy", "weakfish", "atlantic menhaden", "atlantic croaker", "small blue crab", "large blue crab", "southern flounder", "spotted seatrout", "spot")) #this repeats these species common names for the entirety of the length of the haul df

haul_df <- haul %>% dplyr::select(Control1, Program, Year, Month, Day, Date, Location, Nbrrec3, Station, Time, Duration, Sedsize, Btmcomp, Sedsize_new, Btmcomp_new, Depth, Stemp, Btemp, Ssal, Bsal, Sdo, Bdo, Secchi, Latitude, Longitude, Core, Species)
haul_df_all <- haul_df %>% tidyr::expand(Species,Control1) ##using expand to make all species associated with each collection number, is 13x (# of species) larger so it worked
haul=haul_df %>% dplyr::select(-Species) #drop dummy species common name from hauldf

#now can merge haul.all and haul to create a df with a row for species associated with each collection number
haul_final=left_join(haul_df_all,haul,by="Control1")%>%as.data.frame() %>% rename("Speciescommonname"= "Species")
length(unique(haul_final$Species)) #15 species
length(unique(haul_final$Control1)) #7053 Control1, 15*7053= 105795 or # of rows 

#Factor in length 
sel_spp_120 <- P120_bioledt %>% filter(Speciescommonname %in% select_spp) %>% dplyr::select(Control1,Speciescommonname,Colnum) #select data for non-lengthed species
P120_os_prop_edt_tojoin <- P120_os_prop_edt2 %>% ungroup() %>% dplyr::select(Control1, Speciescommonname, Number_new) %>% rename("Colnum"= "Number_new") 
sel_spp_120join <- rbind(sel_spp_120, P120_os_prop_edt_tojoin)
sel_spp_120joinedt <- sel_spp_120join %>% group_by(Speciescommonname,Control1)%>% mutate(id=row_number()) %>% filter(id==1) %>%ungroup()%>%as.data.frame() 
#id should always be 1 for lengthed species b/c have distinct rows
#this is not the case for non-lengthed species, there are repeats of Colnum with Control1 and Speciescommonname b/c of length measurements

sel_spp_120joinedt = sel_spp_120joinedt %>% dplyr::select(-id)
haul_sel_spp <- left_join(haul_final, sel_spp_120joinedt, by= c("Speciescommonname", "Control1")) %>% as.data.frame() 

length(unique(haul_sel_spp$Speciescommonname))
length(unique(haul_sel_spp$Control1)) #it worked! df is 105795 rows, 7053 rows for each species (15 species)

haul_sel_spp$Colnum[haul_sel_spp$Colnum %in% NA] <- 0 #If there is an NA this is because there was no data there 

haul_sel_spp$doy <- yday(haul_sel_spp$Date)
haul_sel_spp$Photoperiod <- daylength(lat= haul_sel_spp$Latitude, doy= haul_sel_spp$doy)
haul_sel_spp$Season <- ifelse(haul_sel_spp$Month==4 | haul_sel_spp$Month==5 | haul_sel_spp$Month==6, "Spring", ifelse(haul_sel_spp$Month==9 |haul_sel_spp$Month==10 | haul_sel_spp$Month==11 | haul_sel_spp$Month==12, "Fall", ifelse(haul_sel_spp$Month==7 |haul_sel_spp$Month==8, "Summer", "Winter")))
haul_sel_spp$Ym_date <- format(haul_sel_spp$Date, "%Y-%m")

write.csv(haul_sel_spp, "/Users/sallydowd/Documents/GitHub/NCBlueCrab_Predators/Data/P120/Finalized/p120_CPUE_lengthBC.csv")
```

#### Last check: both!

```{r}
#Load in new length and non-length CPUE datasets 
p915_CPUE_length <- read.csv("/users/sallydowd/Desktop/Ch1Data/P915/p915_CPUE_length.csv")
p915_CPUE <- read_csv("/users/sallydowd/Desktop/Ch1Data/P915/p915_CPUE_new.csv")
setwd("~/Documents/GitHub/NCBlueCrab_Predators")
p120_CPUE_length <- read.csv("/Users/sallydowd/Documents/GitHub/NCBlueCrab_Predators/Data/P120/Finalized/p120_CPUE_length.csv")
p120_CPUE <- read_csv("Data/P120/Finalized/p120_CPUE.csv")
p120_CPUE_lengthBC <-read.csv("/Users/sallydowd/Documents/GitHub/NCBlueCrab_Predators/Data/P120/Finalized/p120_CPUE_lengthBC.csv")

length_total <- p915_CPUE_length %>% group_by(Speciescommonname) %>% summarize(total_count= sum(Colnum))
write.csv(length_total, "/users/sallydowd/Desktop/P915length_total.csv")
nonlength_total <- p915_CPUE %>% group_by(Speciescommonname) %>% summarize(total_count= sum(Colnum))
write.csv(nonlength_total, "/users/sallydowd/Desktop/P915nonlength_total.csv")

length_total <- p120_CPUE_length %>% group_by(Speciescommonname) %>% summarize(total_count= sum(Colnum))
write.csv(length_total, "/users/sallydowd/Desktop/P120length_total.csv")
nonlength_total <- p120_CPUE %>% group_by(Speciescommonname) %>% summarize(total_count= sum(Colnum))
write.csv(nonlength_total, "/users/sallydowd/Desktop/P120nonlength_total.csv")

length_total <- p120_CPUE_lengthBC %>% group_by(Speciescommonname) %>% summarize(total_count= sum(Colnum))
write.csv(length_total, "/users/sallydowd/Desktop/P120length_totalBC.csv")
nonlength_total <- p120_CPUE %>% group_by(Speciescommonname) %>% summarize(total_count= sum(Colnum))
write.csv(nonlength_total, "/users/sallydowd/Desktop/P120nonlength_totalBC.csv")
```

### Length figures

##### Fig. 1: Length frequency overall
```{r}
#data processing 
##P915
other_species <- p915_len_f %>% filter(Speciescommonname %in% c("atlantic croaker", "black drum", "red drum", "sheepshead", "southern flounder", "southern kingfish", "spot", "spotted seatrout", "striped bass", "striped mullet", "atlantic menhaden")) %>% dplyr::select(Sample, Speciescommonname, Colnum, Length, Control2, Linenum) 

#unsure if this is correct 
other_species %>% drop_na(Length) %>% group_by(Speciescommonname) %>% ggplot() + geom_histogram(aes(x= Length)) + facet_wrap(~Speciescommonname, scale= "free_x") + standard_theme

##P120
P120_bioledt %>% filter(Year >=2001) %>% drop_na(Length) %>% group_by(Speciescommonname) %>% ggplot() + geom_histogram(aes(x= Length)) + facet_wrap(~Speciescommonname, scale= "free") + xlab("Length (in)") + ylab("Count") + standard_theme
```

```{r}
#figure formation 
##P915


##P120
```

##### Fig. 2: Length frequency upon division 
```{r}
#data processing
p915_CPUE_length <- read.csv("/users/sallydowd/Desktop/Ch1Data/P915/p915_CPUE_length.csv")
p120_CPUE_length <- read.csv("/Users/sallydowd/Documents/GitHub/NCBlueCrab_Predators/Data/P120/Finalized/p120_CPUE_length.csv")

p915_lengthspp <- unique(p915_CPUE_length$Speciescommonname[grepl("small|large", p915_CPUE_length$Speciescommonname, ignore.case = TRUE)])
p120_lengthspp <- unique(p120_CPUE_length$Speciescommonname[grepl("small|large", p120_CPUE_length$Speciescommonname, ignore.case = TRUE)])
```

```{r}
#figure formation 
##P915
darker_shade <- darken("#E69F00", 0.3) 
p915_CPUE_length %>% filter(Speciescommonname %in% p915_lengthspp, Colnum > 0) %>% mutate(Basespp = gsub("^(small|large) ", "", Speciescommonname)) %>%
ggplot() + geom_histogram(aes(x = Colnum, fill = grepl("small", Speciescommonname, ignore.case = TRUE)), bins = 15, alpha = 0.7) +
facet_wrap(~Basespp, scale = "free_x") + scale_fill_manual(values= c(darker_shade, "#E69F00"), name= "Size", labels= c("large", "small")) + standard_theme + labs(x= "Number collected", y= "Count") + guides(fill = guide_legend(reverse = TRUE))
ggsave("/users/sallydowd/Desktop/Ch1Data/Figures/P915_ls_length.jpeg")

##P120 
darker_shade <- darken("steelblue", 0.3) 
p120_CPUE_length %>% filter(Speciescommonname %in% p120_lengthspp, Colnum >0 ) %>% mutate(Basespp = gsub("^(small|large) ", "", Speciescommonname)) %>%
ggplot() + geom_histogram(aes(x = Colnum, fill = grepl("small", Speciescommonname, ignore.case = TRUE)), bins = 15, alpha = 0.7) +
facet_wrap(~Basespp, scale = "free_x") + scale_fill_manual(values= c(darker_shade, "steelblue"), name= "Size", labels= c("large", "small")) + standard_theme + labs(x= "Number collected", y= "Count") +
guides(fill = guide_legend(reverse = TRUE))
ggsave("/users/sallydowd/Desktop/Ch1Data/Figures/P120_ls_length.jpeg")
```
